/** 1970s CRT 광고 비트. t = ms from start. */
export const AD_DURATION_MS = 48000

export const AD_BEATS = [
  { t: 0, set: 'snow', latin: 'SIGNUM · AETHERIS', kicker: 'PAID PROGRAMMING  ·  1978', line: '', disclaimer: '' },
  {
    t: 900,
    set: 'family',
    latin: 'MATUTINA VITA',
    kicker: 'ECHOES BROADCAST',
    line: '오, 레이디 앤 젠틀맨! 아침마다 출근하기 힘드시죠?',
    disclaimer: '',
  },
  {
    t: 6200,
    set: 'officeTease',
    latin: 'DOMUS → OFFICIUM',
    kicker: 'SPECTACULUM',
    line: '짜-잔. 때로는 긴 설명보다… 눈으로 한 번 보는 게 더 와닿는 법이죠.',
    disclaimer: '',
  },
  {
    t: 11000,
    set: 'officeTease',
    latin: 'REMOTE LABORIS',
    kicker: 'ECHOES',
    line: '하하. 말이 길었죠? 이제 여러분은 회사에 직접 가지 않아도 괜찮습니다!',
    disclaimer: '',
  },
  {
    t: 15500,
    set: 'badge',
    latin: 'TESSELLA · ECHOVIS',
    kicker: 'NOVUM AEVUM',
    line: '새로운 시대의 직장 생활. 에코즈 시각 칩과 함께하세요!',
    disclaimer: '',
  },
  {
    t: 19800,
    set: 'tag',
    latin: 'TAGITUS',
    kicker: 'BEEP',
    line: '삑—',
    disclaimer: '',
  },
  {
    t: 21200,
    set: 'officeFull',
    latin: 'OFFICIUM PERFECTUM',
    kicker: 'ECHOVIS',
    line: '지정된 리더기에 사원증을 태그하는 순간, 눈앞에 완벽한 업무 환경이 펼쳐집니다!',
    disclaimer: '',
  },
  {
    t: 26800,
    set: 'officeFull',
    latin: 'MUNDITIA · DUCTUS · SALUS',
    kicker: 'PROMOTIO',
    line: '깨끗한 사무실! 편리한 안내 시스템! 더욱 쾌적하고 안전한 직장 생활!',
    disclaimer: '※ 본 제품은 시각 신경 칩과 연동됩니다.',
  },
  {
    t: 31800,
    set: 'officeFull',
    latin: 'ECHOVIS CHIP',
    kicker: 'PROJECT ECHOES',
    line: '에코즈칩. 당신의 일상을, 더 나은 일상으로.',
    disclaimer: '',
  },
  {
    t: 35500,
    set: 'legal',
    latin: 'CAVEAT EMPTOR',
    kicker: 'STATUTUM',
    line: '아. 주위에 날카로운 물건, 또는 굴곡을 주의하세요. 칩과 동봉되는 의자에 앉아 계셔야 합니다!',
    disclaimer:
      '칩 연동 상태에서 공간을 지각하지 못하고 입는 상해의 경우 에코즈 오피스에서 책임지지 않습니다. 사용자 과실 외의 상황에 대해서는 대부분 책임져 드리니, 너무 걱정 마시고 톡라인 코드로 연락 부탁드립니다!',
  },
  {
    t: 41500,
    set: 'logo',
    latin: 'PROJECT ECHOES',
    kicker: 'ECHOVIS',
    line: '',
    disclaimer: '',
  },
  {
    t: 43800,
    set: 'glitch',
    latin: 'RESONANTIA',
    kicker: '— SIGNAL LOSS —',
    line: '',
    disclaimer: '',
  },
  {
    t: 44800,
    set: 'officeFull',
    latin: 'ECHOVIS',
    kicker: 'ECHOES',
    line: '에코즈칩과 함께하세요!',
    disclaimer: '',
  },
  {
    t: 46800,
    set: 'black',
    latin: '',
    kicker: '',
    line: '',
    disclaimer: '',
  },
]
