export const KANG_ISOL_MORNING_BEATS = Object.freeze([
  { id: 'isol-m-01', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '좋은 아침입니다^^', next: 'isol-m-02' },
  { id: 'isol-m-02', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '처음부터 톡라인으로 연락 주셨으면 좋았을 텐데.', condition: { isolTalked: true }, next: 'isol-m-03' },
  { id: 'isol-m-03', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '뭐.', condition: { isolTalked: true }, next: 'isol-m-04' },
  { id: 'isol-m-04', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '배정된 자리는 어찌 잘 찾으셨네요.', next: 'isol-m-05' },
  { id: 'isol-m-05', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '잘 하셨어요.', next: 'isol-m-06' },
  { id: 'isol-m-06', type: 'dialogue', presentation: 'phone', speaker: '주인공', text: '빈 자리가 하나밖에 없던데요?', auto: true, noChoicePrompt: true, next: 'isol-m-07' },
  { id: 'isol-m-07', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '네? 그럴 리가요.', next: 'isol-m-08' },
  { id: 'isol-m-08', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '절전 모드를 키셨나요?', next: 'isol-m-09' },
  { id: 'isol-m-09', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '여기 엄청 넓은데...', next: 'isol-m-10' },
  { id: 'isol-m-10', type: 'dialogue', presentation: 'phone', speaker: '주인공', text: '착각했나 봐요.', auto: true, noChoicePrompt: true, next: 'isol-m-11' },
  { id: 'isol-m-11', type: 'dialogue', presentation: 'vn', speaker: '주인공', text: '... 어라?', next: 'isol-m-12' },
  { id: 'isol-m-12', type: 'dialogue', presentation: 'vn', speaker: '주인공', text: '내가 친 채팅 아닌데.', next: 'isol-m-13' },
  { id: 'isol-m-13', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '비몽사몽 하시면 그럴 수 있어요.', next: 'isol-m-14' },
  { id: 'isol-m-14', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '오늘 맡으실 일은 어렵지 않아요.', next: 'isol-m-15' },
  { id: 'isol-m-15', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '첫 날이니까.', next: 'isol-m-16' },
  { id: 'isol-m-16', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '회사 분위기 익히는 정도로만 생각하세요.', next: 'isol-m-17' },
  { id: 'isol-m-17', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '커피를 타고, 나눠드리고.', next: 'isol-m-18' },
  { id: 'isol-m-18', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '뭐 말을 걸고.', next: 'isol-m-19' },
  { id: 'isol-m-19', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '아까처럼 대충 기웃거리라는 소리가 아니라.', condition: { isolTalked: true }, next: 'isol-m-20' },
  { id: 'isol-m-20', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '제대로 눈 도장 찍어보자고요.', next: 'isol-m-21' },
  { id: 'isol-m-21', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '저는 커피를 잘 못 마셔요.', next: 'isol-m-22' },
  {
    id: 'isol-m-22',
    type: 'choice',
    presentation: 'phone',
    speaker: '주인공',
    text: null,
    choices: [{ id: 'then', text: '그러면...', next: 'isol-m-23' }],
  },
  { id: 'isol-m-23', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '일단 제 자리로 오세요.', next: 'isol-m-24' },
  { id: 'isol-m-24', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '귀가 잘 안들리셔도.', next: 'isol-m-25' },
  { id: 'isol-m-25', type: 'dialogue', presentation: 'phone', speaker: '강이솔', text: '업무 시간이니 텍스트로 연동 되잖아요?', next: 'isol-m-26' },
  { id: 'isol-m-26', type: 'transition', presentation: 'to-3d', speaker: null, text: null, next: null },
])
