import { CH01_ASSETS as ASSETS } from './assets.js'

const MAP_ASSET_DEFAULTS = {
  backgroundAssetId: ASSETS.bg.office,
  tilesetAssetId: ASSETS.tileset.office,
  playerSpriteAssetId: ASSETS.sprite.player,
  spriteFrame: { width: 32, height: 32 },
  tilesetMap: { 0: [0, 0], 1: [1, 0], 2: [2, 0], 3: [0, 1], 4: [1, 1] },
}

const rawChapter01Maps = {
  office7: {
    id: 'office7',
    label: '7F · 안내 구역',
    floorId: '7F',
    ambient: '라운지, 전임자 자리, 내부 메신저가 한 눈에 들어온다. 그루미가 말한 세 곳이 모두 여기 있다.',
    hint: '방향키/WASD로 이동 · ● 로 조사 · 회의실·복도 문도 맵에 표시돼 있습니다.',
    cols: 12,
    rows: 8,
    tileSize: 44,
    playerStart: { row: 6, col: 5, facing: { dr: -1, dc: 0 } },
    grid: [
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 3, 0, 0, 0, 0, 0, 3, 0, 2, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 3, 0, 0, 4, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    ],
    labels: {
      '2-2': '전임자 자리',
      '2-8': 'TalkLine 백로그',
      '2-10': '회의실',
      '4-4': '라운지',
      '4-7': '7F 복도',
    },
    triggers: {
      '2-2': 'investigate_desk',
      '2-8': 'investigate_chatlog',
      '2-10': 'meeting_entry',
      '4-4': 'investigate_lounge',
      '4-7': 'floor7_rpg',
    },
    investigation: {
      progressLabel: '안내 구역 조사',
      exitScene: 'floor7_rpg',
      spots: [
        { flag: 'ch1DeskInvestigationDone', label: '전임자 자리', tileKey: '2-2', trigger: 'investigate_desk', revisitScene: 'investigate_desk_done' },
        { flag: 'ch1ChatlogInvestigationDone', label: 'TalkLine 백로그', tileKey: '2-8', trigger: 'investigate_chatlog', revisitScene: 'investigate_chatlog_done' },
        { flag: 'ch1LoungeInvestigationDone', label: '라운지', tileKey: '4-4', trigger: 'investigate_lounge', revisitScene: 'investigate_lounge_done' },
      ],
    },
  },
  floor7: {
    id: 'floor7',
    label: '7F 복도',
    floorId: '7F',
    ambient: '창문 밖은 너무 밝고, 복도 안쪽은 유난히 조용하다.',
    hint: '방향키/WASD 이동 · ● 버튼으로 조사 · 아래에서 진척도와 나가기를 확인하세요.',
    cols: 14,
    rows: 9,
    tileSize: 44,
    backgroundAssetId: ASSETS.bg.office,
    playerStart: { row: 4, col: 1, facing: { dr: 0, dc: 1 } },
    grid: [
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 3, 0, 0, 3, 0, 0, 3, 0, 0, 3, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1],
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    ],
    labels: {
      '2-2': '게시판',
      '2-5': '냉장고',
      '2-8': '보안 포스터',
      '2-11': '박서이 사물함',
      '4-1': '안내 구역으로',
      '4-12': '엘리베이터 로그',
      '7-7': '회의실',
    },
    triggers: {
      '2-2': 'flavor_board',
      '2-5': 'flavor_fridge',
      '2-8': 'flavor_poster',
      '2-11': 'flavor_seoi_locker',
      '4-1': 'ch1_floor7_leave',
      '4-12': 'flavor_elevator',
      '7-7': 'meeting_entry',
    },
    investigation: {
      progressLabel: '7F 복도 조사',
      exitScene: 'ch1_floor7_leave',
      spots: [
        { flag: 'ch1CheckedMissingMemorialNotice', label: '게시판', tileKey: '2-2', trigger: 'flavor_board', revisitScene: 'flavor_board_done' },
        { flag: 'ch1FoundFridgeBatterySticker', label: '냉장고', tileKey: '2-5', trigger: 'flavor_fridge', revisitScene: 'flavor_fridge_done' },
        { flag: 'ch1ReadBadgeAuditPoster', label: '보안 포스터', tileKey: '2-8', trigger: 'flavor_poster', revisitScene: 'flavor_poster_done' },
        { flag: 'ch1FoundUnsignedNote', label: '박서이 사물함', tileKey: '2-11', trigger: 'flavor_seoi_locker', revisitScene: 'flavor_seoi_locker_done' },
        { flag: 'ch1NotedElevatorTime', label: '엘리베이터 로그', tileKey: '4-12', trigger: 'flavor_elevator', revisitScene: 'flavor_elevator_done' },
      ],
    },
  },
  meetingRoom: {
    id: 'meetingRoom',
    label: '7F 회의실',
    floorId: '7F',
    ambient: '프로젝터 팬 소리만 얇게 깔린다.',
    hint: '테이블 주변을 돌아다닌 뒤 회의를 시작하거나 복도로 나가세요.',
    cols: 13,
    rows: 9,
    tileSize: 44,
    backgroundAssetId: ASSETS.bg.meetingRoom,
    playerStart: { row: 5, col: 2, facing: { dr: -1, dc: 0 } },
    grid: [
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      [1, 0, 3, 0, 0, 0, 3, 0, 0, 0, 3, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1, 3, 0, 3, 1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1],
      [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
    ],
    labels: {
      '1-2': '화이트보드',
      '1-6': '프로젝터',
      '1-10': '창문',
      '4-5': '최민준 팀장',
      '4-7': '강이솔 선임',
      '7-6': '회의 시작',
      '8-6': '복도로 나가기',
    },
    triggers: {
      '1-2': 'flavor_whiteboard',
      '1-6': 'flavor_projector',
      '1-10': 'flavor_window',
      '4-5': 'flavor_choi_seat',
      '4-7': 'flavor_iseol_seat',
      '7-6': 'meeting_start_gate',
      '8-6': 'floor7_rpg',
    },
    investigation: {
      progressLabel: '회의실 조사',
      exitScene: 'floor7_rpg',
      spots: [
        { flag: 'ch1PhotographedWhiteboard', label: '화이트보드', tileKey: '1-2', trigger: 'flavor_whiteboard', revisitScene: 'flavor_whiteboard_done' },
        { flag: 'ch1FoundIncidentRehearsalFile', label: '프로젝터', tileKey: '1-6', trigger: 'flavor_projector', revisitScene: 'flavor_projector_done' },
        { flag: 'ch1NotedStairSensorBlink', label: '창문', tileKey: '1-10', trigger: 'flavor_window', revisitScene: 'flavor_window_done' },
        { flag: 'ch1CheckedChoiSeat', label: '최민준 팀장', tileKey: '4-5', trigger: 'flavor_choi_seat', revisitScene: 'flavor_choi_seat_done' },
        { flag: 'ch1SawIseolBlockMemo', label: '강이솔 선임', tileKey: '4-7', trigger: 'flavor_iseol_seat', revisitScene: 'flavor_iseol_seat_done' },
      ],
    },
    npcs: [
      {
        id: 'npc_choi',
        name: '최민준',
        label: '최민준 팀장',
        position: { row: 4, col: 5 },
        trigger: 'flavor_choi_seat',
      },
      {
        id: 'npc_iseol',
        name: '강이솔',
        label: '강이솔 선임',
        position: { row: 4, col: 7 },
        trigger: 'flavor_iseol_seat',
      },
    ],
  },
  floor3: {
    id: 'floor3',
    label: '3F 계단실',
    floorId: '3F',
    ambient: '발소리가 한 박자 늦게 되돌아온다. 위쪽 자료실 철문 너머로 공기가 무겁게 밀려 온다.',
    hint: '조용히 이동하세요. 단서를 확인한 뒤 비상구로 나가 결론을 내릴 수 있습니다.',
    cols: 12,
    rows: 9,
    tileSize: 44,
    backgroundAssetId: ASSETS.bg.stairwell,
    playerStart: { row: 7, col: 1, facing: { dr: 0, dc: 1 } },
    grid: [
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1],
      [1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
      [1, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1],
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    ],
    labels: {
      '5-5': '혈흔',
      '6-6': '꺼진 CCTV',
      '7-10': '비상구',
    },
    triggers: {
      '5-5': 'clue_blood',
      '6-6': 'clue_camera',
      '7-10': 'exit_floor3',
    },
    investigation: {
      progressLabel: '3F 계단실 조사',
      exitScene: 'deduction_chat',
      exitRequirements: [{ type: 'flag', flag: 'ch1ReachedFloor3Exit' }],
      spots: [
        { flag: 'ch1FoundStairwellBloodTrace', label: '혈흔', tileKey: '5-5', trigger: 'clue_blood', revisitScene: 'clue_blood_done' },
        { flag: 'ch1FoundDisabledCamera', label: '꺼진 CCTV', tileKey: '6-6', trigger: 'clue_camera', revisitScene: 'clue_camera_done' },
        { flag: 'ch1ReachedFloor3Exit', label: '비상구', tileKey: '7-10', trigger: 'exit_floor3', revisitScene: 'exit_floor3_done' },
      ],
    },
    ambientFlags: [
      { id: 'floor3.scanline', enabled: true, intensity: 0.65, overlayAssetId: 'overlay_scanline' },
    ],
  },
}

function decorateMap(map) {
  const eventTiles = Object.entries(map.triggers ?? {}).map(([key, trigger]) => ({
    id: `${map.id}.${key}`,
    key,
    trigger,
  }))

  return {
    ...MAP_ASSET_DEFAULTS,
    ...map,
    backgroundAssetId: map.backgroundAssetId ?? MAP_ASSET_DEFAULTS.backgroundAssetId,
    eventTiles,
    ambientFlags: map.ambientFlags ?? [],
  }
}

export const chapter01Maps = Object.fromEntries(
  Object.entries(rawChapter01Maps).map(([mapId, map]) => [mapId, decorateMap(map)]),
)
