import { EffectTypes, SceneModes } from '../../../engine/contracts.js'

export const chapter01Scenes = {
  rpg_floor7: {
    id: 'chapter-01.rpg_floor7',
    chapterId: 'chapter-01',
    localId: 'rpg_floor7',
    mode: SceneModes.RPG,
    mapId: 'floor7',
  },
  flavor_board: {
    id: 'chapter-01.flavor_board',
    chapterId: 'chapter-01',
    localId: 'flavor_board',
    mode: SceneModes.VN,
    returnTo: 'rpg_floor7',
    lines: [
      { char: 'system', text: '게시판에는 사내 동호회 모집글과 보안 교육 안내가 겹겹이 붙어 있다.', isNarration: true },
      { char: 'system', text: '가장 아래쪽 낡은 종이에 “3F 임시 폐쇄”라는 문구가 보인다.', isNarration: true, important: true },
    ],
  },
  flavor_fridge: {
    id: 'chapter-01.flavor_fridge',
    chapterId: 'chapter-01',
    localId: 'flavor_fridge',
    mode: SceneModes.VN,
    returnTo: 'rpg_floor7',
    lines: [
      { char: 'system', text: '공용 냉장고 안에는 이름표가 붙은 캔커피들이 줄지어 있다.', isNarration: true },
      { char: 'system', text: '박준혁 선임의 이름표가 붙은 캔 하나가 아직 차갑다.', isNarration: true, important: true },
    ],
  },
  flavor_poster: {
    id: 'chapter-01.flavor_poster',
    chapterId: 'chapter-01',
    localId: 'flavor_poster',
    mode: SceneModes.VN,
    returnTo: 'rpg_floor7',
    lines: [
      { char: 'system', text: '보안 포스터: “모든 접속 기록은 회사 자산입니다.”', isNarration: true },
      { char: 'system', text: '작은 글씨로 덧칠된 문구가 있다. “기록이 사람을 대신할 수는 없다.”', isNarration: true },
    ],
  },
  meeting_entry: {
    id: 'chapter-01.meeting_entry',
    chapterId: 'chapter-01',
    localId: 'meeting_entry',
    mode: SceneModes.VN,
    lines: [
      { char: 'system', text: '회의실 문 너머로 낮은 목소리들이 새어 나온다.', isNarration: true },
      { char: 'kim', text: '아, 오셨어요. 팀 미팅 딱 시작하려던 참이에요.' },
      { char: 'system', text: '김수진 대리의 웃음은 반 박자 늦다.', isNarration: true, important: true },
    ],
    next: 'rpg_meeting_room',
  },
  rpg_meeting_room: {
    id: 'chapter-01.rpg_meeting_room',
    chapterId: 'chapter-01',
    localId: 'rpg_meeting_room',
    mode: SceneModes.RPG,
    mapId: 'meetingRoom',
  },
  flavor_whiteboard: {
    id: 'chapter-01.flavor_whiteboard',
    chapterId: 'chapter-01',
    localId: 'flavor_whiteboard',
    mode: SceneModes.VN,
    returnTo: 'rpg_meeting_room',
    lines: [
      { char: 'system', text: '화이트보드에는 Q3 로드맵, “권한 분리”, “감사 로그 재처리”가 적혀 있다.', isNarration: true },
      { char: 'system', text: '한쪽 구석의 “TEMP BINDING” 문구만 급하게 지워져 있다.', isNarration: true, important: true },
    ],
  },
  flavor_projector: {
    id: 'chapter-01.flavor_projector',
    chapterId: 'chapter-01',
    localId: 'flavor_projector',
    mode: SceneModes.VN,
    returnTo: 'rpg_meeting_room',
    lines: [
      { char: 'system', text: '프로젝터 화면이 절전 모드로 깜빡인다.', isNarration: true },
      { char: 'system', text: '로그인 사용자는 아직 박준혁 선임으로 표시되어 있다.', isNarration: true },
    ],
  },
  flavor_window: {
    id: 'chapter-01.flavor_window',
    chapterId: 'chapter-01',
    localId: 'flavor_window',
    mode: SceneModes.VN,
    returnTo: 'rpg_meeting_room',
    lines: [
      { char: 'system', text: '창밖으로 3층 비상계단 난간이 작게 보인다.', isNarration: true },
      { char: 'system', text: '누군가 방금 지나간 듯, 반사광이 아주 잠깐 끊겼다.', isNarration: true, important: true },
    ],
  },
  flavor_choi_seat: {
    id: 'chapter-01.flavor_choi_seat',
    chapterId: 'chapter-01',
    localId: 'flavor_choi_seat',
    mode: SceneModes.CHAT,
    returnTo: 'rpg_meeting_room',
    lines: [
      { char: 'choi', text: '새로 오신 분이죠? 저장소 권한은 읽기 전용으로 열어 뒀습니다.' },
      { char: 'choi', text: '다만 3층 서버룸 관련 저장소는 접근하지 마세요. 감사 중입니다.' },
    ],
    choices: [{ text: '고개를 끄덕인다.', next: 'rpg_meeting_room' }],
  },
  flavor_kim_seat: {
    id: 'chapter-01.flavor_kim_seat',
    chapterId: 'chapter-01',
    localId: 'flavor_kim_seat',
    mode: SceneModes.CHAT,
    returnTo: 'rpg_meeting_room',
    lines: [
      { char: 'kim', text: '혹시 아까 3층 얘기, 너무 신경 쓰지 마세요.' },
      { char: 'kim', text: '제가 괜히 겁을 줬나 봐요.' },
      { char: 'kim', text: '…그래도 혼자 내려가진 마시고요.' },
    ],
    choices: [{ text: '알겠습니다.', next: 'rpg_meeting_room' }],
  },
  meeting_chat: {
    id: 'chapter-01.meeting_chat',
    chapterId: 'chapter-01',
    localId: 'meeting_chat',
    mode: SceneModes.CHAT,
    lines: [
      { char: 'kim', text: ({ nickname }) => `네, ${nickname}님이에요. 오늘부터 합류하셨어요.` },
      { char: 'choi', text: '어서 와요. Q3 로드맵 리뷰부터 같이 보겠습니다.' },
      { char: 'choi', text: '권한 이전은 HR 쪽 임시 카드 매핑으로 처리된 거죠?' },
      { char: 'kim', text: '네. 표시는 조금 이상할 수 있지만 업무에는 문제 없습니다.' },
    ],
    choices: [
      { text: '잘 부탁드립니다.', next: 'meeting_vn', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'politeMeeting' }] },
      { text: '임시 카드 매핑이 계속 걸립니다.', next: 'meeting_vn_suspicious', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'pressedBinding' }] },
    ],
  },
  meeting_vn_suspicious: {
    id: 'chapter-01.meeting_vn_suspicious',
    chapterId: 'chapter-01',
    localId: 'meeting_vn_suspicious',
    mode: SceneModes.VN,
    lines: [
      { char: 'choi', text: '시스템 이전기에는 흔한 일입니다. 너무 깊게 보지 마세요.' },
      { char: 'system', text: '최민준 팀장의 시선이 김수진 대리 쪽으로 아주 짧게 움직인다.', isNarration: true, important: true },
      { char: 'kim', text: '……' },
    ],
    next: 'meeting_chat2',
  },
  meeting_vn: {
    id: 'chapter-01.meeting_vn',
    chapterId: 'chapter-01',
    localId: 'meeting_vn',
    mode: SceneModes.VN,
    lines: [
      { char: 'choi', text: '오늘 안건은 Q3 로드맵 리뷰입니다.' },
      { char: 'choi', text: '먼저 개발팀 현황부터 공유하겠습니다.' },
      { char: 'kim', text: '……' },
      { char: 'system', text: '김수진 대리가 핸드폰을 내려다본다.', isNarration: true },
      { char: 'system', text: '표정이 굳어 있다.', isNarration: true, important: true },
    ],
    next: 'meeting_chat2',
  },
  meeting_chat2: {
    id: 'chapter-01.meeting_chat2',
    chapterId: 'chapter-01',
    localId: 'meeting_chat2',
    mode: SceneModes.CHAT,
    lines: [
      { char: 'kim', text: '저… 잠깐만요.' },
      { char: 'kim', text: '방금 경비팀한테 문자 왔는데요.' },
      { char: 'kim', text: '3층 비상구 카메라가 오늘 오전부터 꺼져 있대요.' },
      { char: 'kim', text: '그리고… 박준혁 선임이 아직 출근을 안 했어요.' },
    ],
    choices: [
      { text: '3층에 가봐야 할 것 같아요.', next: 'go_floor3', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'volunteeredFloor3' }] },
      { text: '경비팀에 신고하면 되지 않나요?', next: 'go_floor3_b', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'askedSecurity' }] },
      { text: '최 팀장에게 먼저 알려야 합니다.', next: 'go_floor3_c', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'askedChoi' }] },
    ],
  },
  go_floor3_b: {
    id: 'chapter-01.go_floor3_b',
    chapterId: 'chapter-01',
    localId: 'go_floor3_b',
    mode: SceneModes.CHAT,
    lines: [
      { char: 'kim', text: '경비팀이… 연락이 안 돼요.' },
      { char: 'kim', text: '아까부터 계속 통화 중이에요.' },
      { char: 'kim', text: '이상하죠. 회사 전화가 이렇게 오래 비는 일은 없는데.' },
    ],
    choices: [{ text: '직접 가보겠습니다.', next: 'go_floor3' }],
  },
  go_floor3_c: {
    id: 'chapter-01.go_floor3_c',
    chapterId: 'chapter-01',
    localId: 'go_floor3_c',
    mode: SceneModes.CHAT,
    lines: [
      { char: 'choi', text: '지금 회의 중입니다. 불확실한 경보 하나로 움직일 수는 없어요.' },
      { char: 'kim', text: '팀장님, 카메라가 꺼진 시간이 준혁 선임 마지막 접속 시간이랑 겹쳐요.' },
      { char: 'choi', text: '…확인만 하고 바로 올라오세요.' },
    ],
    choices: [{ text: '3층으로 내려간다.', next: 'go_floor3' }],
  },
  go_floor3: {
    id: 'chapter-01.go_floor3',
    chapterId: 'chapter-01',
    localId: 'go_floor3',
    mode: SceneModes.VN,
    lines: [
      { char: 'system', text: '-- 3층 계단실 --', isNarration: true },
      { char: 'system', text: '형광등 하나가 불규칙하게 깜빡이고 있다.', isNarration: true },
      { char: 'system', text: '복도 끝에서 뭔가 쓰러져 있는 것이 보인다.', isNarration: true, important: true },
      { char: 'unknown', text: '…보고 있으면 내려와.' },
    ],
    next: 'rpg_floor3',
  },
  rpg_floor3: {
    id: 'chapter-01.rpg_floor3',
    chapterId: 'chapter-01',
    localId: 'rpg_floor3',
    mode: SceneModes.RPG,
    mapId: 'floor3',
  },
  clue_camera: {
    id: 'chapter-01.clue_camera',
    chapterId: 'chapter-01',
    localId: 'clue_camera',
    mode: SceneModes.VN,
    returnTo: 'rpg_floor3',
    lines: [
      { char: 'system', text: 'CCTV 렌즈가 검은 테이프로 막혀 있다.', isNarration: true },
      { char: 'system', text: '테이프 가장자리에는 보안감사실 로고가 희미하게 찍혀 있다.', isNarration: true, important: true },
    ],
    effects: [{ type: EffectTypes.ADD_ITEM, item: 'cameraMemo' }],
  },
  clue_blood: {
    id: 'chapter-01.clue_blood',
    chapterId: 'chapter-01',
    localId: 'clue_blood',
    mode: SceneModes.VN,
    lines: [
      { char: 'system', text: '바닥에 짙은 얼룩이 있다.', isNarration: true },
      { char: 'system', text: '말라붙어 있다. 오래됐다.', isNarration: true, important: true },
      { char: 'unknown', text: '……' },
      { char: 'system', text: '복도 저 끝에서 발소리가 들린다.', isNarration: true, important: true },
    ],
    effects: [{ type: EffectTypes.ADD_ITEM, item: 'bloodTrace' }],
    next: 'clue_chat',
  },
  clue_chat: {
    id: 'chapter-01.clue_chat',
    chapterId: 'chapter-01',
    localId: 'clue_chat',
    mode: SceneModes.CHAT,
    lines: [
      { char: 'kim', text: '지금 어디예요?!' },
      { char: 'kim', text: '3층이에요??' },
      { char: 'kim', text: '빨리 올라와요.' },
      { char: 'kim', text: '제발.' },
    ],
    choices: [
      { text: '사진을 찍어 전송한다.', next: 'chapter_end', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'sentBloodPhoto' }] },
      { text: '증거를 더 살펴본다.', next: 'chapter_end', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'inspectedBlood' }] },
      { text: '아무 말 없이 뒤로 물러난다.', next: 'chapter_end', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'withdrewSilently' }] },
    ],
  },
  exit_floor3: {
    id: 'chapter-01.exit_floor3',
    chapterId: 'chapter-01',
    localId: 'exit_floor3',
    mode: SceneModes.VN,
    lines: [
      { char: 'system', text: '비상구 앞. 잠겨 있다.', isNarration: true },
      { char: 'system', text: '아래에서 발소리가 올라온다.', isNarration: true, important: true },
      { char: 'unknown', text: '그 카드는 아직 아래층 문을 열 수 없어.' },
    ],
    next: 'clue_chat',
  },
  chapter_end: {
    id: 'chapter-01.chapter_end',
    chapterId: 'chapter-01',
    localId: 'chapter_end',
    mode: SceneModes.END,
    title: '첫 번째 단서',
    nextChapterId: 'chapter-02',
  },
}
