export const koUiText = {
  modeBarChatDefault: 'CHAT MODE · TalkLine Internal',
  modeBarVnDefault: 'VN MODE',
  modeBarRpgDefault: 'RPG MODE',
  vnTapToContinue: '▶ 탭하여 계속',
  vnAutoOn: 'AUTO ON',
  vnAutoOff: 'AUTO OFF',
  vnSkip: 'SKIP',
  vnBacklog: 'BACKLOG',
  vnCloseBacklog: '닫기',
  chatNamePlaceholder: '표시 이름',
  chatSend: '전송',
  receiptUnread: '읽지 않음',
  receiptReadIn: '{seconds}초 후 읽음',
  deliveryStable: 'stable',
  deliveryDelayed: 'server delayed',
  deliveryMismatch: 'sync mismatch',
  roomTitleVn: '비주얼 기록 재생 중',
  roomTitleRpg: '사내 위치 조사',
  roomTitlePersonal: '그루미 개인 채널',
  sessionLabel: 'SESSION',
  chapterClearContinue: '계속',
  chapterClearRestart: '처음으로 다시',
  chapterClearRestartFromBeginning: '처음으로',
  rpgMinimap: 'MINIMAP',
  saveMenuAria: '세이브 슬롯 메뉴',
  tabChat: '채팅',
  tabChatBadge: 'Talk',
  tabProfile: '프로필',
  tabProfileBadge: 'ID',
  tabClues: '단서',
  tabCluesBadge: 'Log',
  tabSettings: '설정',
  tabSettingsBadge: 'Sys',
  bottomTabAria: 'GROOMY OFFICE 하단 탭',
  saveMenu: {
    title: '세션 관리',
    close: '닫기',
    empty: '비어 있음',
    save: '저장',
    load: '불러오기',
    delete: '삭제',
  },
}
