import { CH03_ASSETS as ASSETS } from './assets.js'

export const rawChapter03Maps = {
  deskArea: {
    id: 'deskArea',
    label: '7F · 박서이 책상',
    floorId: '7F',
    ambient: '형광등 아래, 아직 치워지지 않은 서랍과 액자가 조용히 놓여 있다.',
    hint: '서랍·액자·서랍 맨 아래를 모두 조사하세요. 네 가지 단서를 확인하면 이야기가 이어집니다.',
    cols: 10,
    rows: 6,
    tileSize: 40,
    spriteFrame: { width: 32, height: 32 },
    backgroundAssetId: ASSETS.bg.office,
    tilesetAssetId: ASSETS.tileset.desk,
    playerSpriteAssetId: ASSETS.sprite.player,
    tilesetMap: { 0: [0, 0], 1: [1, 0], 2: [2, 0], 3: [0, 1], 4: [1, 1] },
    playerStart: { row: 4, col: 4, facing: { dr: -1, dc: 0 } },
    grid: [
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 3, 0, 0, 0, 3, 0, 3, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    ],
    labels: {
      '3-2': '책상 서랍',
      '3-6': '가족사진 액자',
      '3-8': '서랍 맨 아래',
    },
    triggers: {
      '3-2': 'resignation_letter_clue',
      '3-6': 'family_photo_clue',
      '3-8': 'recorder_found_clue',
    },
    eventTiles: [
      { id: 'desk.drawer', key: '3-2', trigger: 'resignation_letter_clue' },
      { id: 'desk.photo', key: '3-6', trigger: 'family_photo_clue' },
      { id: 'desk.recorder', key: '3-8', trigger: 'recorder_found_clue' },
    ],
    ambientFlags: [
      { id: 'desk.scanline', enabled: true, intensity: 0.4, overlayAssetId: ASSETS.overlay.scanline },
    ],
    investigation: {
      progressLabel: '박서이 책상 조사',
      exitScene: 'guardian_recall_vn',
      exitRequirements: [{ type: 'flag', flag: 'ch3FoundRecorderNotPlayed' }],
      spots: [
        { flag: 'ch3FoundResignationLetter', label: '책상 서랍', tileKey: '3-2', trigger: 'resignation_letter_clue' },
        { flag: 'ch3_photoBranchResolved', label: '가족사진 액자', tileKey: '3-6', trigger: 'family_photo_clue' },
        { flag: 'ch3FoundRecorderNotPlayed', label: '서랍 맨 아래', tileKey: '3-8', trigger: 'recorder_found_clue' },
      ],
    },
  },
  storageRoom: {
    id: 'storageRoom',
    label: '3F · 자료보관실',
    floorId: '3F',
    ambient: '먼지 냄새와 오래된 종이 냄새가 섞인다. 보정 레이어가 이 층만 얇게 깔려 있다.',
    hint: '의자·사원증·구석을 조사하세요. 사원증 근처에서 일기를 확인할 수 있습니다. 녹음기를 찾으면 다음 장면으로 이어집니다.',
    cols: 10,
    rows: 7,
    tileSize: 40,
    spriteFrame: { width: 32, height: 32 },
    backgroundAssetId: ASSETS.bg.stairwell,
    tilesetAssetId: ASSETS.tileset.storage,
    playerSpriteAssetId: ASSETS.sprite.player,
    tilesetMap: { 0: [0, 0], 1: [1, 0], 2: [2, 0], 3: [0, 1], 4: [1, 1] },
    playerStart: { row: 5, col: 4, facing: { dr: -1, dc: 0 } },
    grid: [
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 3, 0, 0, 0, 0, 3, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 3, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    ],
    labels: {
      '2-2': '낡은 의자',
      '2-7': '떨어진 사원증 (벽 틈)',
      '4-4': '녹음기 (완본)',
    },
    triggers: {
      '2-2': 'storage_clue_chair',
      '2-7': 'storage_clue_idcard',
      '4-4': 'storage_clue_recorder_full',
    },
    eventTiles: [
      { id: 'storage.chair', key: '2-2', trigger: 'storage_clue_chair' },
      { id: 'storage.idcard', key: '2-7', trigger: 'storage_clue_idcard' },
      { id: 'storage.recorder', key: '4-4', trigger: 'storage_clue_recorder_full' },
    ],
    ambientFlags: [
      { id: 'storage.glitch', enabled: true, intensity: 0.8, overlayAssetId: ASSETS.overlay.glitchSoft },
    ],
    investigation: {
      progressLabel: '자료보관실 조사',
      exitScene: 'body_discovery_vn',
      exitRequirements: [{ type: 'flag', flag: 'ch3_foundRecorderFull' }],
      spots: [
        { flag: 'ch3_foundStorageChair', label: '낡은 의자', tileKey: '2-2', trigger: 'storage_clue_chair' },
        { flag: 'ch3_recoveredSeoiDiary', label: '떨어진 사원증', tileKey: '2-7', trigger: 'storage_clue_idcard' },
        { flag: 'ch3_foundRecorderFull', label: '녹음기 (완본)', tileKey: '4-4', trigger: 'storage_clue_recorder_full' },
      ],
    },
  },
}
