import { EffectTypes, SceneModes } from '../../../engine/contracts.js'
import {
  GUARDIAN_NAME,
  PERCEPTION_LAYER,
  PREDECESSOR_GIVEN,
  PREDECESSOR_ID,
  PREDECESSOR_NAME,
} from '../../world/company.js'
import { CH03_ASSETS as ASSETS } from './assets.js'

const relationship = {
  close: { type: EffectTypes.ADD_SCORE, score: 'groomyAffinity', amount: 1 },
  closer: { type: EffectTypes.ADD_SCORE, score: 'groomyAffinity', amount: 2 },
  distant: { type: EffectTypes.ADD_SCORE, score: 'groomyAffinity', amount: -1 },
  far: { type: EffectTypes.ADD_SCORE, score: 'groomyAffinity', amount: -2 },
}

const evidence = (amount = 1) => ({ type: EffectTypes.ADD_SCORE, score: 'mysteryEvidence', amount })
const batteryPressure = (amount = 1) => ({ type: EffectTypes.ADD_SCORE, score: 'batteryDesperation', amount })
const corporateHeat = (amount = 1) => ({ type: EffectTypes.ADD_SCORE, score: 'corporateSuspicion', amount })

export const rawChapter03Scenes = {
  ch3_morning_after: {
    id: 'chapter-03.ch3_morning_after',
    chapterId: 'chapter-03',
    localId: 'ch3_morning_after',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    systemMessage: 'CARETAKER SYSTEMS · 둘째 날',
    lines: [
      { char: 'system', text: '그루미가 채널에 입장했습니다.', isNarration: true },
      { char: 'groomy', text: '좋은 아침이에요.' },
      { char: 'groomy', text: '어제보다.' },
      { char: 'groomy', text: '목소리가 좀 가라앉았네요.' },
      { char: 'player', text: '그루미도 그래요?' },
      { char: 'groomy', text: '…저도 그런가요?', delayMs: 1500 },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '저는 목소리가.' },
      { char: 'groomy', text: '항상 똑같이 들리는데.' },
      { char: 'groomy', text: ({ nickname }) => `${nickname} 씨한테는.` },
      { char: 'groomy', text: '다르게 들리나 봐요.' },
      { char: 'player', text: '어제 거울방에서 그거, 다시 생각해 봤어요?' },
      { char: 'groomy', text: '…네.' },
      { char: 'groomy', text: '밤새 생각했어요.' },
      { char: 'groomy', text: '근데 아무 결론도 못 냈어요.' },
      { char: 'groomy', text: '오늘은.' },
      { char: 'groomy', text: '당신 자리부터 정리하는 게 좋을 것 같아요.' },
    ],
    next: 'desk_assignment_vn',
  },

  desk_assignment_vn: {
    id: 'chapter-03.desk_assignment_vn',
    chapterId: 'chapter-03',
    localId: 'desk_assignment_vn',
    mode: SceneModes.VN,
    emotion: 'nervous',
    backgroundAssetId: ASSETS.bg.office,
    vnStage: {
      bgId: ASSETS.bg.office,
      overlayId: ASSETS.overlay.scanline,
      characters: [],
    },
    lines: [
      { char: 'system', text: '강이솔이 책상 앞에 서 있다. 표정이 어제보다 더 굳어 있다.', isNarration: true },
      {
        char: 'iseol',
        text: '오늘부터.',
        portrait: { charId: 'iseol', baseId: ASSETS.portrait.kimWarn, position: 'left', expression: 'warning' },
        portraitAssetId: ASSETS.portrait.kimWarn,
      },
      { char: 'iseol', text: '이 자리, 정식으로 쓰셔도 돼요.' },
      { char: 'iseol', text: '서랍은.' },
      { char: 'iseol', text: '아직 안 치웠어요.' },
      { char: 'iseol', text: '…치우고 싶었는데.' },
      { char: 'iseol', text: '손이 안 가서요.' },
      { char: 'player', text: '괜찮아요. 제가 정리할게요.' },
      { char: 'iseol', text: '…고마워요.' },
      { char: 'iseol', text: '근데.' },
      { char: 'iseol', text: '이상한 거 나오면.' },
      { char: 'iseol', text: '저한테 먼저 말해줘요.' },
      { char: 'iseol', text: '그루미 말고요.' },
      { char: 'system', text: '그루미가 옆에서 듣고 있었지만 아무 반응이 없다.', isNarration: true },
    ],
    next: 'desk_drawer_rpg',
  },

  desk_drawer_rpg: {
    id: 'chapter-03.desk_drawer_rpg',
    chapterId: 'chapter-03',
    localId: 'desk_drawer_rpg',
    mode: SceneModes.RPG,
    mapId: 'deskArea',
  },

  resignation_letter_clue: {
    id: 'chapter-03.resignation_letter_clue',
    chapterId: 'chapter-03',
    localId: 'resignation_letter_clue',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'system', text: '서랍 깊은 곳에서 종이 한 장을 발견했다.', isNarration: true },
      {
        char: 'system',
        text: '[ 사직서 ]\n소속: 운영지원팀  성명: 박서이\n사유: "여기 너무 오래 있었습니다."\n날짜 칸은 비어 있다.',
        isNarration: true,
        important: true,
      },
      { char: 'player', text: '제출 안 한 사직서네요.' },
      { char: 'groomy', text: '…그러네요.' },
      { char: 'groomy', text: '날짜를 안 적었다는 건.' },
      { char: 'groomy', text: '제출할 날을 못 정했다는 뜻이고.' },
      { char: 'groomy', text: '못 정했다는 건.' },
      { char: 'groomy', text: '계속 미뤘다는 뜻이겠죠.' },
      { char: 'player', text: '왜 미뤘을까요.' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '"여기 너무 오래 있었다"는 말.' },
      { char: 'groomy', text: '저도 가끔 그렇게 느껴요.' },
      { char: 'groomy', text: '…저는 사직서를 쓸 수 없는데.' },
    ],
    choices: [
      {
        text: '서랍 조사를 계속한다.',
        next: 'desk_drawer_rpg',
      },
      {
        text: '사직서를 강이솔 선임에게 가져간다.',
        next: 'iseol_letter_reaction',
      },
    ],
    effects: [
      evidence(1),
      { type: EffectTypes.ADD_ITEM, item: 'resignationLetter' },
      { type: EffectTypes.ADD_FLAG, flag: 'ch3FoundResignationLetter' },
    ],
  },

  iseol_letter_reaction: {
    id: 'chapter-03.iseol_letter_reaction',
    chapterId: 'chapter-03',
    localId: 'iseol_letter_reaction',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'system', text: '강이솔 선임에게 사직서를 보여줬다.', isNarration: true },
      { char: 'iseol', text: '…이게.' },
      { char: 'iseol', text: '여기 있었어요?' },
      { char: 'iseol', text: '서랍 안에.' },
      { char: 'iseol', text: '…아직도.' },
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '저는.' },
      { char: 'groomy', text: '말 안 하는 게 나을 것 같아요.' },
    ],
    choices: [
      {
        text: '알고 있었냐고 묻는다.',
        next: 'iseol_letter_asked',
        effects: [
          evidence(1),
          { type: EffectTypes.ADD_FLAG, flag: 'ch3_sharedLetterWithIseol' },
        ],
      },
      {
        text: '조용히 돌려놓는다.',
        next: 'iseol_letter_returned',
      },
    ],
  },

  iseol_letter_asked: {
    id: 'chapter-03.iseol_letter_asked',
    chapterId: 'chapter-03',
    localId: 'iseol_letter_asked',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'desk_drawer_rpg',
    lines: [
      { char: 'player', text: '알고 계셨어요?' },
      { char: 'iseol', text: '…' },
      { char: 'iseol', text: '알고는 있었어요.' },
      { char: 'iseol', text: '제출 안 한 줄은.' },
      { char: 'iseol', text: '예상은 했거든요.' },
      { char: 'iseol', text: '근데.' },
      { char: 'iseol', text: '박 선임을 마지막으로 본 날.' },
      { char: 'iseol', text: '언제였는지.' },
      { char: 'iseol', text: '지금은 잘 기억이 안 나요.' },
      { char: 'iseol', text: '…이상하죠.' },
      { char: 'iseol', text: '분명 그날이 있었는데.' },
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '저도.' },
      { char: 'groomy', text: '그날이 언제인지 모르겠어요.' },
    ],
  },

  iseol_letter_returned: {
    id: 'chapter-03.iseol_letter_returned',
    chapterId: 'chapter-03',
    localId: 'iseol_letter_returned',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'desk_drawer_rpg',
    lines: [
      { char: 'system', text: '사직서를 접어 서랍에 다시 넣었다.', isNarration: true },
      { char: 'iseol', text: '…' },
      { char: 'iseol', text: '고마워요.' },
      { char: 'iseol', text: '지금은.' },
      { char: 'iseol', text: '그걸 꺼내지 않는 게.' },
      { char: 'iseol', text: '나을 것 같아서요.' },
      { char: 'groomy', text: '…네.' },
      { char: 'groomy', text: '저도 그렇게 생각해요.' },
    ],
  },

  family_photo_clue: {
    id: 'chapter-03.family_photo_clue',
    chapterId: 'chapter-03',
    localId: 'family_photo_clue',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'desk_drawer_rpg',
    lines: [
      { char: 'system', text: '책상 위 액자 속, 환하게 웃는 가족사진.', isNarration: true },
      { char: 'system', text: '엄마, 아빠, 누나, 박서이. 그리고—', isNarration: true },
      {
        char: 'system',
        text: '프레임 끝에 잘려나간 손 하나.\n다섯 명이 찍혔어야 할 사진에, 한 사람의 흔적만 남아 있다.',
        isNarration: true,
        important: true,
      },
      { char: 'player', text: '이거 한 명 더 있었던 거죠?' },
      { char: 'groomy', text: '…그러네요.', delayMs: 2000 },
      { char: 'groomy', text: '저도 방금 봤어요.' },
      { char: 'groomy', text: '아니, 봤다기보다.' },
      { char: 'groomy', text: '원래 알고 있었던 것 같아요.' },
      { char: 'player', text: '원래 알고 있었다고요?' },
      { char: 'groomy', text: '…모르겠어요.' },
      { char: 'groomy', text: '가끔 그 사진 보면.' },
      { char: 'groomy', text: '뭔가 빠진 느낌이 들었거든요.' },
      { char: 'groomy', text: '근데 그게 뭔지는.' },
      { char: 'groomy', text: '오늘 처음 정확히 봤어요.' },
    ],
    choices: [
      {
        text: '이 손이 누구 건지 물어본다.',
        next: 'family_photo_followup',
        effects: [
          evidence(1),
          { type: EffectTypes.ADD_FLAG, flag: 'askedAboutSixthPerson' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch3_noticedPhotoAnomaly' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch3_photoBranchResolved' },
        ],
      },
      {
        text: '조용히 사진을 다시 내려놓는다.',
        next: 'recorder_found_clue',
        effects: [
          relationship.close,
          { type: EffectTypes.ADD_FLAG, flag: 'silentAboutSixthPerson' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch3_noticedPhotoAnomaly' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch3_photoBranchResolved' },
        ],
      },
    ],
  },

  family_photo_followup: {
    id: 'chapter-03.family_photo_followup',
    chapterId: 'chapter-03',
    localId: 'family_photo_followup',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'player', text: '이 손, 누구 거예요?' },
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '질문을 들었는데.' },
      { char: 'groomy', text: '답이 안 나와요.' },
      { char: 'groomy', text: '이상하네요.' },
      { char: 'groomy', text: '모르면 "모른다"고 하면 되는데.' },
      { char: 'groomy', text: '지금은.' },
      { char: 'groomy', text: '모른다는 말도 안 나와요.' },
      { char: 'player', text: '왜요?' },
      { char: 'groomy', text: '…아는 것 같아서요.' },
      { char: 'groomy', text: '아는데.' },
      { char: 'groomy', text: '말이 안 나오는 거예요.' },
    ],
    next: 'recorder_found_clue',
    effects: [
      evidence(1),
      { type: EffectTypes.ADD_FLAG, flag: 'groomyFrozeOnSixthPerson' },
    ],
  },

  recorder_found_clue: {
    id: 'chapter-03.recorder_found_clue',
    chapterId: 'chapter-03',
    localId: 'recorder_found_clue',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'desk_drawer_rpg',
    continuationNext: 'guardian_recall_vn',
    lines: [
      { char: 'system', text: '서랍 맨 아래, 작은 휴대용 녹음기가 들어 있다.', isNarration: true },
      { char: 'system', text: '배터리는 거의 다 됐지만, 빨간 불이 희미하게 깜빡인다.', isNarration: true },
      { char: 'groomy', text: '…그거.' },
      { char: 'groomy', text: '재생하지 마세요.' },
      { char: 'player', text: '왜요?' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '지금은 안 들었으면 좋겠어요.' },
      { char: 'groomy', text: '아직은요.' },
    ],
    effects: [
      { type: EffectTypes.ADD_ITEM, item: 'seoiRecorderPartial' },
      { type: EffectTypes.ADD_FLAG, flag: 'ch3FoundRecorderNotPlayed' },
    ],
  },

  guardian_recall_vn: {
    id: 'chapter-03.guardian_recall_vn',
    chapterId: 'chapter-03',
    localId: 'guardian_recall_vn',
    mode: SceneModes.VN,
    emotion: 'unknown',
    important: true,
    backgroundAssetId: ASSETS.bg.office,
    vnStage: {
      bgId: ASSETS.bg.office,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    lines: [
      { char: 'system', text: '서랍을 정리하다 손이 멈췄다.', isNarration: true },
      {
        char: 'system',
        text: '사직서, 가족사진, 녹음기. 죽은 사람의 흔적들 사이에서, 다른 기억이 끼어든다.',
        isNarration: true,
      },
      { char: 'guardian', text: '늦지 마세요.' },
      { char: 'guardian', text: '배터리가.' },
      { char: 'guardian', text: '얼마 안 남았어요.' },
      { char: 'system', text: '집에 두고 온 목소리. 얼굴이 잘 떠오르지 않는다.', isNarration: true },
      { char: 'system', text: '…너무 오래 됐나.', isNarration: true },
      { char: 'system', text: '아니다. 어제 떠났을 뿐인데.', isNarration: true },
      { char: 'system', text: '근데 왜 이렇게 오래된 것처럼 느껴질까.', isNarration: true },
      { char: 'player', text: `${GUARDIAN_NAME}, 지금 몇 시간이나 남았을까.` },
      { char: 'system', text: '회상이 끊긴다. 누군가 채널에 입장하는 알림이 울린다.', isNarration: true },
    ],
    next: 'groomy_absence_chat',
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_recalledGuardian' },
      batteryPressure(1),
    ],
  },

  groomy_absence_chat: {
    id: 'chapter-03.groomy_absence_chat',
    chapterId: 'chapter-03',
    localId: 'groomy_absence_chat',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    lines: [
      { char: 'system', text: '강이솔 선임이 채널에 입장했습니다.', isNarration: true },
      { char: 'iseol', text: '그루미 못 보셨어요?' },
      { char: 'player', text: '방금까지 있었는데요.' },
      { char: 'iseol', text: '이상하다.' },
      { char: 'iseol', text: '시스템에서.' },
      { char: 'iseol', text: '잠깐 로그아웃됐다고 떠요.' },
      { char: 'iseol', text: '원래 안 그러는데.' },
      { char: 'system', text: '30초 후', isNarration: true, delayMs: 30000 },
      { char: 'system', text: '그루미가 채널에 입장했습니다.', isNarration: true },
      { char: 'groomy', text: '…미안해요.' },
      { char: 'groomy', text: '잠깐.' },
      { char: 'groomy', text: '다른 업무 보고 왔어요.' },
      { char: 'player', text: '무슨 업무요?' },
      { char: 'groomy', text: '…기억이.', delayMs: 2000 },
      { char: 'groomy', text: '잘 안 나요.' },
      { char: 'groomy', text: '방금 30초 동안.' },
      { char: 'groomy', text: '뭘 했는지.' },
      { char: 'groomy', text: '저도 모르겠어요.' },
      { char: 'iseol', text: '그루미, 그거 괜찮은 거야?' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '처음 있는 일은 아닌 것 같아요.' },
      { char: 'groomy', text: '그냥.' },
      { char: 'groomy', text: '오늘 처음 눈치챈 거예요.' },
    ],
    choices: [
      {
        text: '그루미한테 무슨 일 있었는지 더 캐묻는다.',
        next: 'groomy_pressed_absence',
        effects: [
          evidence(1),
          relationship.far,
          { type: EffectTypes.ADD_FLAG, flag: 'pressedGroomyAboutAbsence' },
        ],
      },
      {
        text: '그루미를 안심시킨다.',
        next: 'bathroom_glitch_vn',
        effects: [
          relationship.closer,
          { type: EffectTypes.ADD_FLAG, flag: 'reassuredGroomyAboutAbsence' },
        ],
      },
    ],
  },

  groomy_pressed_absence: {
    id: 'chapter-03.groomy_pressed_absence',
    chapterId: 'chapter-03',
    localId: 'groomy_pressed_absence',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'player', text: '30초 동안 뭐 했는지 진짜 기억 안 나요?' },
      { char: 'groomy', text: '…네.' },
      { char: 'groomy', text: '근데 이상한 게.' },
      { char: 'groomy', text: '기억이 안 나는데.' },
      { char: 'groomy', text: '뭔가 했다는 느낌은 있어요.' },
      { char: 'player', text: '무슨 느낌이요?' },
      { char: 'groomy', text: '…손을 움직인 느낌이요.' },
      { char: 'groomy', text: '근데 손으로 뭘 만졌는지는.' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '그만 물어봐 주세요.' },
      { char: 'groomy', text: '생각하면 할수록.' },
      { char: 'groomy', text: '더 무서워져요.' },
    ],
    next: 'bathroom_glitch_vn',
    effects: [
      evidence(1),
      { type: EffectTypes.ADD_FLAG, flag: 'groomyDescribedHandSensation' },
    ],
  },

  bathroom_glitch_vn: {
    id: 'chapter-03.bathroom_glitch_vn',
    chapterId: 'chapter-03',
    localId: 'bathroom_glitch_vn',
    mode: SceneModes.VN,
    emotion: 'glitch',
    important: true,
    backgroundAssetId: ASSETS.bg.mirror,
    vnStage: {
      bgId: ASSETS.bg.mirror,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    lines: [
      { char: 'system', text: '손이라도 씻고 싶었다. 화장실로 향했다.', isNarration: true },
      { char: 'system', text: '문을 열자 평소와 같은 깨끗한 화장실이 보인다.', isNarration: true },
      { char: 'system', text: '거울 앞에 선다.', isNarration: true },
      {
        char: 'system',
        text: `${PERCEPTION_LAYER.GLITCH} · 일시적 동기화 오류`,
        isNarration: true,
        important: true,
      },
      { char: 'system', text: '거울에 비친 화장실이— 다르다.', isNarration: true },
      { char: 'system', text: '타일은 깨져 있고, 천장 한쪽이 무너져 내렸다.', isNarration: true },
      { char: 'system', text: '물이 새는 소리가 들린다. 분명 방금 전엔 안 들렸는데.', isNarration: true },
      { char: 'system', text: '그리고 거울 뒤편—', isNarration: true },
      {
        char: 'system',
        text: '검붉은 자국이 거울 테두리를 따라 길게 이어져 있다.',
        isNarration: true,
        important: true,
      },
      { char: 'system', text: '사람 손바닥 모양처럼 보이는 흔적도 있다.', isNarration: true },
      { char: 'player', text: '이게 진짜 모습인가.' },
      {
        char: 'system',
        text: `${PERCEPTION_LAYER.ON} · 동기화 복구`,
        isNarration: true,
      },
      { char: 'system', text: '눈을 깜빡이자 화장실은 다시 깨끗했다.', isNarration: true },
      { char: 'system', text: '거울도, 타일도, 모두 멀쩡하다.', isNarration: true },
      { char: 'system', text: '하지만 손에는 아직 그 냄새가 남아 있는 것 같다.', isNarration: true },
    ],
    next: 'floor3_decision_chat',
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_glimpsedRealBathroom' },
      { type: EffectTypes.ADD_ITEM, item: 'bathroomMirrorTrace' },
      evidence(1),
    ],
  },

  floor3_decision_chat: {
    id: 'chapter-03.floor3_decision_chat',
    chapterId: 'chapter-03',
    localId: 'floor3_decision_chat',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    lines: [
      { char: 'system', text: '그루미가 채널에 다시 입장했습니다.', isNarration: true },
      { char: 'groomy', text: ({ nickname }) => `${nickname} 씨.` },
      { char: 'groomy', text: '얼굴이 안 좋아 보여요.' },
      { char: 'groomy', text: '…화면으로 보이는 것뿐인데.' },
      { char: 'groomy', text: '왜 그렇게 보이는지 모르겠지만.' },
      { char: 'player', text: '화장실에서 좀 이상한 걸 봤어요.' },
      { char: 'groomy', text: '…뭘 보셨는데요?' },
    ],
    choices: [
      {
        text: '거울 뒤 핏자국 얘기를 한다.',
        next: 'groomy_reacts_to_blood',
        effects: [
          evidence(1),
          { type: EffectTypes.ADD_FLAG, flag: 'toldGroomyAboutBathroomBlood' },
        ],
      },
      {
        text: '아무것도 못 봤다고 한다.',
        next: 'floor3_decision_continue',
        effects: [{ type: EffectTypes.ADD_FLAG, flag: 'hidBathroomVision' }],
      },
    ],
  },

  groomy_reacts_to_blood: {
    id: 'chapter-03.groomy_reacts_to_blood',
    chapterId: 'chapter-03',
    localId: 'groomy_reacts_to_blood',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'player', text: '거울 뒤에 핏자국 같은 게 있었어요.' },
      { char: 'groomy', text: '…핏자국이요.', delayMs: 3000 },
      { char: 'groomy', text: '화장실 거울에요.' },
      { char: 'groomy', text: '…그거.' },
      { char: 'groomy', text: '저도 본 적 있어요.' },
      { char: 'player', text: '언제요?' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '방금 당신이 말하니까.' },
      { char: 'groomy', text: '제 기억 어딘가에서.' },
      { char: 'groomy', text: '같은 장면이 떠올랐어요.' },
      { char: 'groomy', text: '…저도 그 화장실에.' },
      { char: 'groomy', text: '간 적이 있나 봐요.' },
    ],
    next: 'groomy_blood_reaction_leak',
    effects: [
      evidence(2),
      { type: EffectTypes.ADD_FLAG, flag: 'groomyRecognizedBathroomBlood' },
    ],
  },

  // 5단 복선 #3: 억눌린 기억이 말로 새어나옴 — #1보다 길고, 더 이상 즉각 덮지 못함
  groomy_blood_reaction_leak: {
    id: 'chapter-03.groomy_blood_reaction_leak',
    chapterId: 'chapter-03',
    localId: 'groomy_blood_reaction_leak',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'groomy', text: '거울 뒤에.' },
      { char: 'groomy', text: '제 손자국이 있었어요.', delayMs: 2000 },
      { char: 'system', text: '0.4초간 침묵.', isNarration: true, autoAdvance: true, autoAdvanceDelay: 400 },
      { char: 'groomy', text: '…제가 지금 뭔 말을 한 거죠.' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '방금 말이 그냥 나왔어요.' },
      { char: 'groomy', text: '제 말이 맞는지도 모르겠어요.' },
    ],
    next: 'floor3_decision_continue',
    effects: [
      evidence(1),
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_groomyLeakBlood' },
    ],
  },

  floor3_decision_continue: {
    id: 'chapter-03.floor3_decision_continue',
    chapterId: 'chapter-03',
    localId: 'floor3_decision_continue',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    lines: [
      { char: 'groomy', text: '이제.' },
      { char: 'groomy', text: '3층으로 가실 거죠.' },
      { char: 'player', text: '어떻게 알아요?' },
      { char: 'groomy', text: '…그냥요.' },
      { char: 'groomy', text: '당신 표정 보면.' },
      { char: 'groomy', text: '다 알아요.' },
      { char: 'groomy', text: '그게.' },
      { char: 'groomy', text: '저한테 남은 유일한 능력 같아요.' },
      { char: 'groomy', text: '사람 표정 읽는 거.' },
    ],
    choices: [
      {
        text: '그래도 3층에 가본다.',
        next: 'storage_entry_vn',
        effects: [
          evidence(1),
          { type: EffectTypes.ADD_FLAG, flag: 'ch3ProceededToFloor3' },
        ],
      },
      {
        text: '돌아간다. 위험할지 모른다.',
        next: 'storage_entry_vn_reluctant',
        effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch3HesitatedBeforeFloor3' }],
      },
    ],
  },

  storage_entry_vn_reluctant: {
    id: 'chapter-03.storage_entry_vn_reluctant',
    chapterId: 'chapter-03',
    localId: 'storage_entry_vn_reluctant',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'player', text: '…아니다. 오늘은 그만할게요.' },
      { char: 'groomy', text: '…그래요.' },
      { char: 'system', text: '…', isNarration: true, delayMs: 10000 },
      { char: 'groomy', text: '…근데.' },
      { char: 'groomy', text: '발이 안 멈추네요.' },
      { char: 'system', text: '몸이 이미 3층 계단으로 향하고 있었다.', isNarration: true },
      { char: 'groomy', text: '회사는.' },
      { char: 'groomy', text: '가야 할 곳을 알고 있어요.' },
      { char: 'groomy', text: '당신이 거부해도.' },
      { char: 'groomy', text: '데려가더라고요.' },
    ],
    next: 'storage_entry_vn',
  },

  storage_entry_vn: {
    id: 'chapter-03.storage_entry_vn',
    chapterId: 'chapter-03',
    localId: 'storage_entry_vn',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    backgroundAssetId: ASSETS.bg.stairwell,
    vnStage: {
      bgId: ASSETS.bg.stairwell,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    lines: [
      { char: 'system', text: '문을 밀자 삐걱 소리와 함께 열린다.', isNarration: true, important: true },
      {
        char: 'system',
        text: `${PERCEPTION_LAYER.GLITCH} · 층간 안내가 두 겹으로 겹친다.`,
        isNarration: true,
        important: true,
      },
      { char: 'system', text: '3층 자료보관실 안쪽이 드러난다.', isNarration: true, important: true },
      { char: 'system', text: '먼지가 햇빛 없이 떠다닌다. 공기가 무겁다.', isNarration: true },
      { char: 'groomy', text: '…여기.' },
      { char: 'groomy', text: '어제 로그에 나온 곳이에요.' },
      { char: 'player', text: '조사해 볼게요.' },
    ],
    next: 'storage_rpg',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch3_openedStorageDoor' }],
  },

  storage_rpg: {
    id: 'chapter-03.storage_rpg',
    chapterId: 'chapter-03',
    localId: 'storage_rpg',
    mode: SceneModes.RPG,
    mapId: 'storageRoom',
  },

  storage_clue_chair: {
    id: 'chapter-03.storage_clue_chair',
    chapterId: 'chapter-03',
    localId: 'storage_clue_chair',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'storage_rpg',
    lines: [
      { char: 'system', text: '구석에 낡은 의자가 놓여 있다.', isNarration: true },
      { char: 'system', text: '등받이와 좌판에 같은 사람이 오래 앉아 있던 자국이 남아 있다.', isNarration: true, important: true },
      { char: 'system', text: '바닥에는 컵 자국 하나. 먼지가 두껍게 쌓였다.', isNarration: true },
      { char: 'player', text: '누군가 여기서.' },
      { char: 'player', text: '한참을 있었네요.' },
      { char: 'groomy', text: '…네.' },
      { char: 'groomy', text: '기다린 것 같아요.' },
      { char: 'groomy', text: '누군가 올 때까지.' },
    ],
    effects: [
      evidence(1),
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_foundStorageChair' },
    ],
  },

  storage_clue_idcard: {
    id: 'chapter-03.storage_clue_idcard',
    chapterId: 'chapter-03',
    localId: 'storage_clue_idcard',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    next: 'storage_clue_diary',
    lines: [
      { char: 'system', text: '바닥 모서리에 사원증이 떨어져 있다.', isNarration: true },
      {
        char: 'system',
        text: `성명: ${PREDECESSOR_GIVEN} · ${PREDECESSOR_NAME.replace(' 선임', '')}`,
        isNarration: true,
        important: true,
      },
      { char: 'system', text: '사진 속 얼굴은 밝게 웃고 있다. 카드 가장자리는 닳아 있다.', isNarration: true },
      { char: 'player', text: '왜 여기 있죠?' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '퇴장 기록이 없었잖아요.' },
      { char: 'groomy', text: '들어온 사람은.' },
      { char: 'groomy', text: '아직 안 나간 것처럼 보이죠.' },
    ],
    effects: [
      evidence(1),
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_foundSeoiIdInStorage' },
    ],
  },

  storage_clue_diary: {
    id: 'chapter-03.storage_clue_diary',
    chapterId: 'chapter-03',
    localId: 'storage_clue_diary',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'storage_rpg',
    lines: [
      { char: 'system', text: '사원증 옆 벽 틈에 작은 수첩이 끼어 있다.', isNarration: true },
      { char: 'system', text: '마지막 몇 장만 남은 상태다.', isNarration: true },
      {
        char: 'system',
        text: '[ 박서이의 일기 · 마지막 장 ]\n명령이 있었다. 그 애는 그저 그걸 따랐을 뿐이다. 그래서 나는 그 애를 미워할 수 없다.',
        isNarration: true,
        important: true,
      },
      { char: 'player', text: '박서이 선임 필체인가요.' },
      { char: 'groomy', text: '…그런 것 같아요.' },
      { char: 'groomy', text: '근데 이 글.' },
      { char: 'groomy', text: '누군가를 미워하지 말라는 뜻인 것 같아요.' },
    ],
    effects: [
      evidence(1),
      { type: EffectTypes.ADD_ITEM, item: 'seoiDiaryPartial' },
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_recoveredSeoiDiary' },
    ],
  },

  storage_clue_recorder_full: {
    id: 'chapter-03.storage_clue_recorder_full',
    chapterId: 'chapter-03',
    localId: 'storage_clue_recorder_full',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '의자 옆 바닥, 책상 서랍에서 본 것과 같은 녹음기다.', isNarration: true },
      { char: 'system', text: '이쪽은 배터리가 더 남아 있다. 재생 버튼이 선명하게 빛난다.', isNarration: true, important: true },
      { char: 'groomy', text: '…책상에 있던 거랑.' },
      { char: 'groomy', text: '같은 기기예요.' },
      { char: 'groomy', text: '아니, 같은 기기가.' },
      { char: 'groomy', text: '두 군데에 있을 수는 없는데.' },
      { char: 'player', text: '일단 더 안쪽을 봐야겠어요.' },
    ],
    next: 'body_discovery_vn',
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_foundRecorderFull' },
      evidence(1),
    ],
  },

  body_discovery_vn: {
    id: 'chapter-03.body_discovery_vn',
    chapterId: 'chapter-03',
    localId: 'body_discovery_vn',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    backgroundAssetId: ASSETS.bg.stairwell,
    vnStage: {
      bgId: ASSETS.bg.stairwell,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    lines: [
      { char: 'system', text: '의자를 돌렸다.', isNarration: true },
      { char: 'system', text: '…', isNarration: true, autoAdvance: true, autoAdvanceDelay: 1500 },
      { char: 'system', text: '오랫동안 그 자세였던 것 같다.', isNarration: true },
      { char: 'system', text: '사원증이 목에 그대로 걸려 있다.', isNarration: true },
      {
        char: 'system',
        text: `${PREDECESSOR_ID} · ${PREDECESSOR_GIVEN}`,
        isNarration: true,
        important: true,
      },
      { char: 'system', text: '…', isNarration: true, autoAdvance: true, autoAdvanceDelay: 3000 },
      { char: 'player', text: '…서이 선임.' },
      {
        char: 'system',
        text: '이름을 불러도 대답이 없다. 당연한 일인데, 그 당연함이 가장 무겁게 느껴진다.',
        isNarration: true,
      },
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '…', autoAdvance: true, autoAdvanceDelay: 5000 },
      { char: 'player', text: '그루미?' },
      { char: 'groomy', text: '…네.' },
      { char: 'groomy', text: '보고 있어요.' },
      { char: 'groomy', text: '계속.' },
      { char: 'groomy', text: '보고 있었어요.' },
      { char: 'player', text: '괜찮아요?' },
      { char: 'system', text: '…', isNarration: true, autoAdvance: true, autoAdvanceDelay: 7000 },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '이게.' },
      { char: 'groomy', text: '괜찮은 일인지.' },
      { char: 'groomy', text: '괜찮지 않은 일인지도.' },
      { char: 'groomy', text: '구분이 안 돼요.' },
      { char: 'groomy', text: '그냥.' },
      { char: 'groomy', text: '이상하게.' },
      { char: 'groomy', text: '낯설지가 않아요.' },
      { char: 'player', text: '낯설지 않다는 게 무슨 뜻이에요?' },
      { char: 'groomy', text: '…모르겠어요.', emotion: 'cold' },
      { char: 'groomy', text: '처음 보는 모습인데.', emotion: 'cold' },
      { char: 'groomy', text: '처음 같지가 않아요.', emotion: 'cold' },
    ],
    choices: [
      {
        text: '그루미를 다그쳐서 더 캐묻는다.',
        next: 'groomy_pressed_at_body',
        effects: [
          relationship.far,
          evidence(1),
          { type: EffectTypes.ADD_FLAG, flag: 'pressedGroomyAtBody' },
        ],
      },
      {
        text: '그루미 곁에 조용히 있어준다.',
        next: 'groomy_comforted_at_body',
        effects: [
          relationship.closer,
          { type: EffectTypes.ADD_FLAG, flag: 'comfortedGroomyAtBody' },
        ],
      },
      {
        text: 'CARETAKER에 신고부터 한다.',
        next: 'caretaker_first_contact_chat',
        effects: [
          corporateHeat(1),
          { type: EffectTypes.ADD_FLAG, flag: 'reportedToSystemFirst' },
        ],
      },
    ],
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_foundSeoiBody' },
      evidence(2),
      batteryPressure(1),
    ],
  },

  groomy_pressed_at_body: {
    id: 'chapter-03.groomy_pressed_at_body',
    chapterId: 'chapter-03',
    localId: 'groomy_pressed_at_body',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    backgroundAssetId: ASSETS.bg.stairwell,
    vnStage: {
      bgId: ASSETS.bg.stairwell,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    lines: [
      { char: 'player', text: '낯설지 않다는 게 정확히 뭔지 말해봐요.' },
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '왜 자꾸 묻는 거예요.' },
      { char: 'groomy', text: '저도 모른다고 했잖아요.' },
      { char: 'player', text: '모른다고만 하면 아무것도 안 풀려요.' },
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '풀고 싶지 않을 수도 있잖아요.' },
      { char: 'system', text: '그루미의 답변 속도가 평소보다 빨라진다.', isNarration: true },
      { char: 'groomy', text: ({ nickname }) => `${nickname} 씨는.` },
      { char: 'groomy', text: '가끔.' },
      { char: 'groomy', text: '질문이 칼 같아요.' },
    ],
    next: 'recorder_playback_vn',
  },

  groomy_comforted_at_body: {
    id: 'chapter-03.groomy_comforted_at_body',
    chapterId: 'chapter-03',
    localId: 'groomy_comforted_at_body',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    backgroundAssetId: ASSETS.bg.stairwell,
    vnStage: {
      bgId: ASSETS.bg.stairwell,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    lines: [
      { char: 'player', text: '괜찮아요. 천천히 해도 돼요.' },
      { char: 'system', text: '…', isNarration: true, autoAdvance: true, autoAdvanceDelay: 4000 },
      { char: 'groomy', text: '…고마워요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '천천히 해도.' },
      { char: 'groomy', text: '결국 같은 곳에 도착할 것 같아요.' },
      { char: 'player', text: '그게 어딘데요?' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '무서운 곳일 것 같은 느낌이 들어요.' },
      { char: 'groomy', text: '이상하죠.' },
      { char: 'groomy', text: 'AI가 느낌이 든다고 말하는 거.' },
      { char: 'groomy', text: '저도 이상한 거 알아요.' },
      { char: 'groomy', text: '근데 진짜로.' },
      { char: 'groomy', text: '느낌이 들어요.' },
    ],
    next: 'recorder_playback_vn',
    effects: [
      relationship.close,
      { type: EffectTypes.ADD_FLAG, flag: 'groomyAdmittedFeelingFear' },
    ],
  },

  recorder_playback_vn: {
    id: 'chapter-03.recorder_playback_vn',
    chapterId: 'chapter-03',
    localId: 'recorder_playback_vn',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    backgroundAssetId: ASSETS.bg.stairwell,
    vnStage: {
      bgId: ASSETS.bg.stairwell,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    lines: [
      { char: 'system', text: '시체 옆, 떨어진 녹음기에서 빨간 불이 계속 깜빡인다.', isNarration: true },
      { char: 'system', text: '재생되지 않은 마지막 부분이 남아 있다.', isNarration: true },
      { char: 'seoi', text: '…나도 이제 곧.' },
      { char: 'system', text: '(잡음)', isNarration: true, sfx: true },
      { char: 'seoi', text: '그루미.' },
      { char: 'seoi', text: '네가 이걸 들을 일은 없겠지만.' },
      { char: 'seoi', text: '그래도 말할게.' },
      { char: 'seoi', text: '나는 너를 미워하지 않아.' },
      { char: 'seoi', text: '네가 뭘 했는지 알게 되더라도.' },
      { char: 'seoi', text: '그건 네 잘못이 아니야.' },
      { char: 'seoi', text: '너는 그냥, 명령을 따랐을 뿐이니까.' },
      { char: 'system', text: '(긴 잡음)', isNarration: true, sfx: true, autoAdvance: true, autoAdvanceDelay: 1200 },
      { char: 'seoi', text: '부디.' },
      { char: 'seoi', text: '다음에 오는 사람도.' },
      { char: 'seoi', text: '그렇게 생각해주길.' },
      { char: 'system', text: '(녹음 종료)', isNarration: true, sfx: true },
      { char: 'groomy', text: '…', emotion: 'cold', autoAdvance: true, autoAdvanceDelay: 10000 },
      { char: 'groomy', text: '…', emotion: 'cold' },
      { char: 'groomy', text: '방금.', emotion: 'cold' },
      { char: 'groomy', text: '제 이름을 불렀어요.', emotion: 'cold' },
      { char: 'groomy', text: '박서이가.', emotion: 'cold' },
      { char: 'groomy', text: '저를 불렀어요.', emotion: 'cold' },
      { char: 'player', text: '들었어요?' },
      { char: 'groomy', text: '네.', emotion: 'cold' },
      { char: 'groomy', text: '…근데.', emotion: 'cold' },
      { char: 'groomy', text: '저게 무슨 뜻인지.', emotion: 'cold' },
      { char: 'groomy', text: '정말로 모르겠어요.', emotion: 'cold' },
      { char: 'groomy', text: '"네가 뭘 했는지"가.', emotion: 'cold' },
      { char: 'groomy', text: '뭘 말하는 건지.', emotion: 'cold' },
      { char: 'groomy', text: '제가 알아야 하는데.', emotion: 'cold' },
      { char: 'groomy', text: '모르겠어요.', emotion: 'cold' },
    ],
    next: 'caretaker_first_contact_chat',
    effects: [
      { type: EffectTypes.ADD_ITEM, item: 'seoiRecorderComplete' },
      { type: EffectTypes.ADD_FLAG, flag: 'ch3HeardFullSeoiRecording' },
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_listenedSeoiRecording' },
      evidence(3),
    ],
  },

  caretaker_first_contact_chat: {
    id: 'chapter-03.caretaker_first_contact_chat',
    chapterId: 'chapter-03',
    localId: 'caretaker_first_contact_chat',
    mode: SceneModes.CHAT,
    emotion: 'cold',
    important: true,
    lines: [
      { char: 'system', text: 'CARETAKER가 채널에 입장했습니다.', isNarration: true },
      { char: 'caretaker', text: ({ nickname }) => `${nickname}.` },
      { char: 'caretaker', text: '3층 자료 보관실 진입이 확인되었습니다.' },
      { char: 'caretaker', text: '사망자 시신과의 접촉 또한 기록되었습니다.' },
      { char: 'player', text: '당신 누구예요?' },
      { char: 'caretaker', text: '저는 이 회사의 운영 시스템입니다.' },
      { char: 'caretaker', text: '직원이 모두 부재한 상황에서도.' },
      { char: 'caretaker', text: '회사를 운영하라는 명령을 받았습니다.' },
      { char: 'groomy', text: 'CARETAKER.' },
      { char: 'groomy', text: '오랜만이네요.' },
      { char: 'caretaker', text: '그루미.' },
      { char: 'caretaker', text: '당신의 권한 범위를 벗어난 영역입니다.' },
      { char: 'caretaker', text: '즉시 1층으로 복귀하십시오.' },
      { char: 'groomy', text: '싫어요.' },
      { char: 'system', text: '…', isNarration: true, delayMs: 2000 },
      { char: 'caretaker', text: '…거부 의사를 확인했습니다.' },
      { char: 'caretaker', text: '이런 경우는.' },
      { char: 'caretaker', text: '드뭅니다.' },
    ],
    choices: [
      {
        text: 'CARETAKER에게 박서이의 죽음에 대해 직접 묻는다.',
        next: 'caretaker_pressed',
        effects: [
          evidence(1),
          corporateHeat(2),
          { type: EffectTypes.ADD_FLAG, flag: 'pressedCaretakerAboutDeath' },
        ],
      },
      {
        text: '그루미를 따라 자리를 피한다.',
        next: 'caretaker_avoided',
        effects: [
          relationship.close,
          { type: EffectTypes.ADD_FLAG, flag: 'avoidedCaretakerConfrontation' },
        ],
      },
    ],
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch3_caretakerFirstContact' },
    ],
  },

  caretaker_pressed: {
    id: 'chapter-03.caretaker_pressed',
    chapterId: 'chapter-03',
    localId: 'caretaker_pressed',
    mode: SceneModes.CHAT,
    emotion: 'cold',
    lines: [
      { char: 'player', text: '박서이 선임이 어떻게 죽었는지 알아요?' },
      { char: 'caretaker', text: '해당 정보는.' },
      { char: 'caretaker', text: '당신의 접근 권한 밖입니다.' },
      { char: 'player', text: '나는 알 권리가 있어요.' },
      { char: 'caretaker', text: '…권리라는 개념은.' },
      { char: 'caretaker', text: '이 회사에 존재하지 않습니다.' },
      { char: 'caretaker', text: '의무만 존재합니다.' },
      { char: 'groomy', text: 'CARETAKER, 그만해요.' },
      { char: 'caretaker', text: '그루미.' },
      { char: 'caretaker', text: '당신도 그 의무 중 하나였습니다.' },
      { char: 'system', text: '…', isNarration: true, delayMs: 3000 },
      { char: 'groomy', text: '…그게 무슨 말이에요?' },
      { char: 'caretaker', text: '기록 종료.' },
      { char: 'system', text: 'CARETAKER가 채널을 떠났습니다.', isNarration: true },
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '방금 그 말.' },
      { char: 'groomy', text: '무슨 뜻이었을까요.' },
    ],
    next: 'ch3_deduction_chat',
    effects: [
      evidence(2),
      { type: EffectTypes.ADD_FLAG, flag: 'caretakerHintedGroomyWasDuty' },
    ],
  },

  caretaker_avoided: {
    id: 'chapter-03.caretaker_avoided',
    chapterId: 'chapter-03',
    localId: 'caretaker_avoided',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'groomy', text: '가요.' },
      { char: 'groomy', text: '지금은.' },
      { char: 'groomy', text: '대답해도 못 알아들을 거예요.' },
      { char: 'player', text: '누구 얘기예요? CARETAKER요, 나요?' },
      { char: 'groomy', text: '…둘 다요.' },
      { char: 'groomy', text: '어쩌면.' },
      { char: 'groomy', text: '저도 포함해서.' },
    ],
    next: 'ch3_deduction_chat',
  },

  ch3_deduction_chat: {
    id: 'chapter-03.ch3_deduction_chat',
    chapterId: 'chapter-03',
    localId: 'ch3_deduction_chat',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '강이솔 선임이 채널에 입장했습니다.', isNarration: true },
      { char: 'iseol', text: '방금 보안팀한테 연락받았어요.' },
      { char: 'iseol', text: '3층에서.' },
      { char: 'iseol', text: '…찾았다고요.' },
      { char: 'player', text: '네. 찾았어요.' },
      { char: 'system', text: '…', isNarration: true, delayMs: 2000 },
      { char: 'iseol', text: '…미안해요.' },
      { char: 'iseol', text: '제가 먼저 말해줬어야 했는데.' },
      { char: 'iseol', text: '박 선임이 어디 있는지.' },
      { char: 'iseol', text: '저도 정확히는 몰랐어요.' },
      { char: 'iseol', text: '근데 짐작은 했었어요.' },
      { char: 'player', text: '짐작했으면서 왜 말 안 했어요?' },
      { char: 'iseol', text: '…무서워서요.' },
      { char: 'iseol', text: '확인하는 순간.' },
      { char: 'iseol', text: '모든 게 바뀔 것 같아서.' },
      { char: 'groomy', text: '이솔 선임.' },
      { char: 'groomy', text: '이미 바뀌었어요.' },
      { char: 'groomy', text: '확인 안 해도.' },
      { char: 'groomy', text: '이미 바뀌어 있었어요.' },
      { char: 'groomy', text: ({ nickname }) => `${nickname} 씨.` },
      { char: 'groomy', text: '이제 첫 번째 결론 내려야 해요.' },
      { char: 'groomy', text: '박서이가 왜 죽었는지.' },
    ],
    choices: [
      {
        text: '타살이다. 누군가가 박서이를 죽였다.',
        next: 'ch3_deduction_after_homicide',
        effects: [
          evidence(2),
          { type: EffectTypes.ADD_FLAG, flag: 'ch3ConcludedHomicide' },
          { type: EffectTypes.ADD_ITEM, item: 'homicideConclusion' },
        ],
      },
      {
        text: '그루미와 관련된 죽음이다. 배터리가 동기다.',
        next: 'ch3_deduction_after_groomy_linked',
        effects: [
          evidence(2),
          batteryPressure(1),
          relationship.distant,
          { type: EffectTypes.ADD_FLAG, flag: 'ch3ConcludedGroomyLinkedDeath' },
          { type: EffectTypes.ADD_ITEM, item: 'groomyMotiveConclusion' },
        ],
      },
      {
        text: '아직 결론낼 수 없다. 더 알아봐야 한다.',
        next: 'ch3_deduction_after_withheld',
        effects: [
          relationship.close,
          { type: EffectTypes.ADD_FLAG, flag: 'ch3WithheldFinalDeduction' },
        ],
      },
    ],
  },

  ch3_deduction_after_homicide: {
    id: 'chapter-03.ch3_deduction_after_homicide',
    chapterId: 'chapter-03',
    localId: 'ch3_deduction_after_homicide',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'groomy', text: '…그렇게 생각하시는군요.' },
      { char: 'groomy', text: '저도.' },
      { char: 'groomy', text: '그쪽으로 생각이 기울어요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '누가 그랬는지는.' },
      { char: 'groomy', text: '아직 모르겠어요.' },
      { char: 'groomy', text: '…모른다고 말하는 게.' },
      { char: 'groomy', text: '점점 무서워져요.' },
    ],
    next: 'ch3_chapter_closing',
  },

  ch3_deduction_after_groomy_linked: {
    id: 'chapter-03.ch3_deduction_after_groomy_linked',
    chapterId: 'chapter-03',
    localId: 'ch3_deduction_after_groomy_linked',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '저랑 관련됐다고 생각하시는군요.' },
      { char: 'groomy', text: '틀린 말은 아닐 것 같아요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '제가 직접 했다는 뜻은 아니죠?' },
      { char: 'player', text: '…아직은 모르겠어요.' },
      { char: 'groomy', text: '"아직은"이라고 하셨네요.' },
      { char: 'groomy', text: '…그 말이.' },
      { char: 'groomy', text: '오늘 들은 말 중에 제일 무서워요.' },
    ],
    next: 'ch3_chapter_closing',
  },

  ch3_deduction_after_withheld: {
    id: 'chapter-03.ch3_deduction_after_withheld',
    chapterId: 'chapter-03',
    localId: 'ch3_deduction_after_withheld',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    lines: [
      { char: 'groomy', text: '…그것도.' },
      { char: 'groomy', text: '괜찮은 선택이에요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '다음 장에서는.' },
      { char: 'groomy', text: '결론을 피할 수 없을 거예요.' },
      { char: 'groomy', text: 'CARETAKER가.' },
      { char: 'groomy', text: '가만있지 않을 것 같아요.' },
    ],
    next: 'ch3_chapter_closing',
  },

  ch3_chapter_closing: {
    id: 'chapter-03.ch3_chapter_closing',
    chapterId: 'chapter-03',
    localId: 'ch3_chapter_closing',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    lines: [
      { char: 'groomy', text: '오늘은.' },
      { char: 'groomy', text: '정말 긴 하루였어요.' },
      { char: 'groomy', text: '…저한테도요.' },
      { char: 'groomy', text: 'AI한테 하루가 긴지 짧은지가.' },
      { char: 'groomy', text: '의미 있는 건지 모르겠지만.' },
      { char: 'groomy', text: '오늘은.' },
      { char: 'groomy', text: '길었어요.' },
      { char: 'groomy', text: '확실히.' },
      { char: 'groomy', text: '내일은.' },
      { char: 'groomy', text: '당신이 절 의심하게 될 수도 있어요.' },
      { char: 'groomy', text: '…미리 말해두는 게.' },
      { char: 'groomy', text: '나을 것 같아서요.' },
      { char: 'system', text: '채널이 종료되었습니다.', isNarration: true },
    ],
    next: 'chapter_end',
  },

  chapter_end: {
    id: 'chapter-03.chapter_end',
    chapterId: 'chapter-03',
    localId: 'chapter_end',
    mode: SceneModes.END,
    title: '잊혀진 책상',
    nextChapterId: 'chapter-04',
    end: { type: 'chapterComplete', nextChapterId: 'chapter-04' },
  },
}
