export const cueMap = {
  'nfc:scan': { id: 'nfc-scan', frequency: 720, durationMs: 40, gain: 0.03 },
  'typing:start': { id: 'typing-start', frequency: 460, durationMs: 20, gain: 0.02 },
  'typewriter:tick': { id: 'typewriter-tick', frequency: 410, durationMs: 14, gain: 0.015 },
  'choice:selected': { id: 'choice-selected', frequency: 280, durationMs: 70, gain: 0.03 },
  'screen:impact': { id: 'screen-impact', frequency: 120, durationMs: 210, gain: 0.05 },
  'rpg:step': { id: 'rpg-step', frequency: 150, durationMs: 22, gain: 0.02 },
  'rpg:bump': { id: 'rpg-bump', frequency: 90, durationMs: 85, gain: 0.03 },
  'rpg:interact': { id: 'rpg-interact', frequency: 240, durationMs: 60, gain: 0.03 },
  'ui:hover': { id: 'ui-hover', assetId: 'ui_hover', gain: 0.18 },
  'ui:click': { id: 'ui-click', assetId: 'ui_click', gain: 0.2 },
  'ui:confirm': { id: 'ui-confirm', assetId: 'ui_confirm', gain: 0.22 },
  'ui:cancel': { id: 'ui-cancel', assetId: 'ui_cancel', gain: 0.2 },
  'ui:open': { id: 'ui-open', assetId: 'ui_open', gain: 0.2 },
  'ui:close': { id: 'ui-close', assetId: 'ui_close', gain: 0.2 },
  'ui:save': { id: 'ui-save', assetId: 'ui_save', gain: 0.24 },
  'ui:load': { id: 'ui-load', assetId: 'ui_load', gain: 0.24 },
  'ui:toggle': { id: 'ui-toggle', assetId: 'ui_toggle', gain: 0.18 },
  'ui:transition': { id: 'ui-transition', assetId: 'ui_transition', gain: 0.2 },
  'ui:scroll': { id: 'ui-scroll', assetId: 'ui_scroll', gain: 0.1 },
  'ui:notification': { id: 'ui-notification', assetId: 'ui_notification', gain: 0.16 },
  'ui:glitch': { id: 'ui-glitch', assetId: 'ui_glitch', gain: 0.14 },
}
