import { EffectTypes, SceneModes } from '../../../engine/contracts.js'
import { PREDECESSOR_NAME, SESSION_EMP_ID } from '../../world/company.js'

export const prologueBootLines = [
  'NEXUS CORE · TalkLine v2.1',
  '[ OK ] Network UP · TLS 1.3',
  `[ WARN ] TEMP_CARD_BINDING · ${SESSION_EMP_ID}`,
  'Launching TalkLine INTERNAL...',
]

export const prologueScenes = {
  start: {
    id: 'prologue.start',
    chapterId: 'prologue',
    localId: 'start',
    mode: SceneModes.CHAT,
    emotion: 'friendly',
    lines: [
      { char: 'kim', text: `${PREDECESSOR_NAME}님이 맞으시죠?` },
      { char: 'kim', text: '방금 카드 접속 로그가 올라와서요.' },
      { char: 'kim', text: '오늘 첫 출근이시잖아요.' },
      { char: 'kim', text: 'TalkLine 먼저 확인 부탁드려요.' },
    ],
    choices: [
      { text: '네, 안녕하세요.', next: 'clarify_yes', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'acceptedMistakenIdentity' }] },
      { text: '저는 그분이 아닌데요.', next: 'clarify_no', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'deniedIdentity' }] },
      { text: '…혹시 카드 오류 아닌가요?', next: 'clarify_card', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'questionedCard' }] },
    ],
  },
  clarify_yes: {
    id: 'prologue.clarify_yes',
    chapterId: 'prologue',
    localId: 'clarify_yes',
    mode: SceneModes.CHAT,
    emotion: 'friendly',
    lines: [
      { char: 'kim', text: '어서오세요!' },
      { char: 'kim', text: '잘 부탁드립니다.' },
      { char: 'kim', text: '편하게 성함으로 불러 드려도 될까요?' },
    ],
    choices: [
      { text: '네, 편하게 불러 주세요.', next: 'ask_nickname', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'cooperativeIntro' }] },
      { text: '아, 잠깐요…', next: 'clarify_no', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'correctedLate' }] },
    ],
  },
  clarify_no: {
    id: 'prologue.clarify_no',
    chapterId: 'prologue',
    localId: 'clarify_no',
    mode: SceneModes.CHAT,
    emotion: 'nervous',
    lines: [
      { char: 'kim', text: '…아, 그런가요?' },
      { char: 'kim', text: '죄송해요, 제가 헷갈렸네요.' },
      { char: 'kim', text: '아직 귀하의 카드가 정식 발급 전이라서요.' },
      { char: 'kim', text: '전임자분 카드 라인을 임시로 매핑해 뒀거든요.' },
    ],
    choices: [
      { text: '그게 무슨 말인가요?', next: 'explain_binding', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'askedBinding' }] },
      { text: '이름이 어떻게 되시죠?', next: 'ask_nickname', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'movedToName' }] },
    ],
  },
  clarify_card: {
    id: 'prologue.clarify_card',
    chapterId: 'prologue',
    localId: 'clarify_card',
    mode: SceneModes.CHAT,
    emotion: 'nervous',
    lines: [
      { char: 'kim', text: '오류는 아니고요…' },
      { char: 'kim', text: 'TEMP_CARD_BINDING 상태예요.' },
      { char: 'kim', text: '정식 카드 발급 전까지' },
      { char: 'kim', text: '임시로 전임자 라인을 쓰는 거예요.' },
    ],
    choices: [
      { text: '그런 거군요.', next: 'ask_nickname', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'acceptedBinding' }] },
      { text: '좀 더 설명해 주세요.', next: 'explain_binding', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'pressedBinding' }] },
    ],
  },
  explain_binding: {
    id: 'prologue.explain_binding',
    chapterId: 'prologue',
    localId: 'explain_binding',
    mode: SceneModes.CHAT,
    emotion: 'nervous',
    lines: [
      { char: 'kim', text: '시스템 로그가 이름·사번 때문에' },
      { char: 'kim', text: '섞여 보일 수 있어요.' },
      { char: 'kim', text: '전임자 기록 접두어가 포함된 결과는' },
      { char: 'kim', text: '무시하시면 됩니다.' },
      { char: 'kim', text: '일단 업무 진행부터 부탁드릴게요.' },
    ],
    choices: [
      { text: '알겠습니다.', next: 'ask_nickname', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'heardBindingExplanation' }] },
    ],
  },
  ask_nickname: {
    id: 'prologue.ask_nickname',
    chapterId: 'prologue',
    localId: 'ask_nickname',
    mode: SceneModes.CHAT,
    emotion: 'friendly',
    lines: [{ char: 'kim', text: '어떻게 불러 드릴까요?' }],
    input: { type: 'nickname', next: 'after_nickname' },
  },
  after_nickname: {
    id: 'prologue.after_nickname',
    chapterId: 'prologue',
    localId: 'after_nickname',
    mode: SceneModes.CHAT,
    emotion: 'friendly',
    lines: [
      { char: 'kim', text: ({ nickname }) => `${nickname}님이라고 부를게요!` },
      { char: 'kim', text: '자리는 7층 창가쪽이에요.' },
      { char: 'kim', text: '실물 카드는 나중에 HR에서 교체해 줄 거예요.' },
    ],
    choices: [
      { text: '감사해요. 다른 안내사항 있나요?', next: 'schedule_info', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'askedForGuidance' }] },
      { text: '먼저 자리 찾아가 볼게요.', next: 'schedule_info', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'headedToDesk' }] },
    ],
  },
  schedule_info: {
    id: 'prologue.schedule_info',
    chapterId: 'prologue',
    localId: 'schedule_info',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    lines: [
      { char: 'kim', text: '오후 2시에 팀 미팅 있습니다.' },
      { char: 'kim', text: '회의실은 시스템 캘린더에 반영해 뒀어요.' },
    ],
    choices: [
      { text: '알겠습니다.', next: 'vn_warning_intro', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'acceptedSchedule' }] },
      { text: '캘린더 확인할게요.', next: 'vn_warning_intro', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'checkedCalendar' }] },
    ],
  },
  vn_warning_intro: {
    id: 'prologue.vn_warning_intro',
    chapterId: 'prologue',
    localId: 'vn_warning_intro',
    mode: SceneModes.VN,
    emotion: 'nervous',
    lines: [{ char: 'kim', text: '…잠깐, 한 가지만 더.' }],
    next: 'vn_warning_floor',
  },
  vn_warning_floor: {
    id: 'prologue.vn_warning_floor',
    chapterId: 'prologue',
    localId: 'vn_warning_floor',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [{ char: 'kim', text: '3층에는 절대 가지 마세요.' }],
    next: 'vn_warning_detail',
  },
  vn_warning_detail: {
    id: 'prologue.vn_warning_detail',
    chapterId: 'prologue',
    localId: 'vn_warning_detail',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [{ char: 'kim', text: '오늘 새벽, 그쪽에서 뭔가 있었어요.' }],
    next: 'vn_warning_reason',
  },
  vn_warning_reason: {
    id: 'prologue.vn_warning_reason',
    chapterId: 'prologue',
    localId: 'vn_warning_reason',
    mode: SceneModes.VN,
    emotion: 'warning',
    lines: [{ char: 'kim', text: '이유는 묻지 마세요.' }],
    next: 'vn_warning_silence',
  },
  vn_warning_silence: {
    id: 'prologue.vn_warning_silence',
    chapterId: 'prologue',
    localId: 'vn_warning_silence',
    mode: SceneModes.VN,
    emotion: 'warning',
    lines: [{ char: 'kim', text: '…제발요.' }],
    next: 'after_vn',
  },
  after_vn: {
    id: 'prologue.after_vn',
    chapterId: 'prologue',
    localId: 'after_vn',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    systemMessage: '메시지 1건이 내부 정책에 의해 숨김 처리되었습니다.',
    lines: [
      { char: 'kim', text: '아, 3층은 지금 보안 감사 중이라서요!' },
      { char: 'kim', text: '신경 쓰지 않으셔도 돼요. ^^' },
    ],
    choices: [
      { text: '…알겠어요.', next: 'final_approach', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'obeyedWarning' }] },
      { text: '보안 감사요? 평소에도 있나요?', next: 'floor3_push', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'pressedFloor3' }] },
    ],
  },
  floor3_push: {
    id: 'prologue.floor3_push',
    chapterId: 'prologue',
    localId: 'floor3_push',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'kim', text: '…그냥 오늘만요.' },
      { char: 'kim', text: '더 이상은 저도 말씀드리기 어렵네요.' },
    ],
    choices: [{ text: '…알겠습니다.', next: 'final_approach', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'backedOffFloor3' }] }],
  },
  final_approach: {
    id: 'prologue.final_approach',
    chapterId: 'prologue',
    localId: 'final_approach',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    lines: [
      { char: 'kim', text: '그럼 적응 잘 하세요.' },
      { char: 'kim', text: '모르는 거 있으면 언제든지 연락 주세요.' },
    ],
    choices: [{ text: '감사합니다.', next: 'final_question_lead', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'thankedKim' }] }],
  },
  final_question_lead: {
    id: 'prologue.final_question_lead',
    chapterId: 'prologue',
    localId: 'final_question_lead',
    mode: SceneModes.CHAT,
    emotion: 'nervous',
    lines: [
      { char: 'kim', text: '…아, 맞다.' },
      { char: 'kim', text: '한 가지만 더 여쭤봐도 될까요?' },
    ],
    next: 'final_question',
  },
  final_question: {
    id: 'prologue.final_question',
    chapterId: 'prologue',
    localId: 'final_question',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'kim', text: ({ nickname }) => `${nickname}님,` },
      { char: 'kim', text: '이 사번… 쓰시던 분 혹시 아세요?' },
      { char: 'kim', text: '박준혁 선임이요.' },
    ],
    choices: [
      { text: '모릅니다. 처음 듣는 이름이에요.', next: 'ending_deny', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'deniedJunhyeok' }] },
      { text: '…왜 그걸 물어보시죠?', next: 'ending_suspicious', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'questionedJunhyeok' }] },
      { text: '(침묵)', next: 'ending_silence', effects: [{ type: EffectTypes.ADD_FLAG, flag: 'silentAboutJunhyeok' }] },
    ],
  },
  ending_deny: {
    id: 'prologue.ending_deny',
    chapterId: 'prologue',
    localId: 'ending_deny',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    lines: [
      { char: 'kim', text: '그렇군요.' },
      { char: 'kim', text: '…그냥 궁금했어요.' },
      { char: 'kim', text: '잘 적응하세요.' },
    ],
    end: { type: 'chapterComplete', nextChapterId: 'chapter-01' },
  },
  ending_suspicious: {
    id: 'prologue.ending_suspicious',
    chapterId: 'prologue',
    localId: 'ending_suspicious',
    mode: SceneModes.CHAT,
    emotion: 'nervous',
    lines: [
      { char: 'kim', text: '아무것도 아니에요.' },
      { char: 'kim', text: '잊어버리세요.' },
      { char: 'kim', text: '…정말로요.' },
    ],
    end: { type: 'chapterComplete', nextChapterId: 'chapter-01' },
  },
  ending_silence: {
    id: 'prologue.ending_silence',
    chapterId: 'prologue',
    localId: 'ending_silence',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'kim', text: '……' },
      { char: 'kim', text: '나중에 다시 얘기해요.' },
      { char: 'kim', text: '꼭 다시 얘기해야 할 것 같아요.' },
    ],
    end: { type: 'chapterComplete', nextChapterId: 'chapter-01' },
  },
}
