import { EffectTypes, SceneModes } from '../../../engine/contracts.js'
import {
  GROOMY_AFFINITY_CH4_ABANDON_MAX,
  GROOMY_AFFINITY_SHIELD_MIN,
  GROOMY_AFFINITY_WARM_MAX,
  GROOMY_AFFINITY_WARM_MIN,
} from '../../story/groomyAffinityThresholds.js'
import { PREDECESSOR_NAME } from '../../world/company.js'

const evidence = (amount = 1) => ({ type: EffectTypes.ADD_SCORE, score: 'mysteryEvidence', amount })
const batteryPressure = (amount = 1) => ({ type: EffectTypes.ADD_SCORE, score: 'batteryDesperation', amount })
const groomyClose = { type: EffectTypes.ADD_SCORE, score: 'groomyAffinity', amount: 1 }

const affinityAtLeast = (min) => [{ type: 'score', score: 'groomyAffinity', min }]
const affinityBetween = (min, max) => [{ type: 'score', score: 'groomyAffinity', min, max }]

const rawChapter04Scenes = {
  archive_room_infiltration: {
    id: 'chapter-04.archive_room_infiltration',
    chapterId: 'chapter-04',
    localId: 'archive_room_infiltration',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '채널이 종료되었다는 문장은 화면에 오래 남아 있었다.', isNarration: true },
      { char: 'system', text: '정확히는, 그 문장이 사라진 뒤에도 그 자리에 남아 있는 것 같았다.', isNarration: true },
      { char: 'system', text: '그루미가 마지막으로 한 말 — 내일은 당신이 절 의심하게 될 수도 있어요 — 이 문장만큼은 어떤 알림도 지우지 못했다.', isNarration: true },
      { char: 'system', text: '사무실은 이미 절반쯌 어두워져 있었다.', isNarration: true },
      { char: 'system', text: 'PERCEPTION LAYER가 야간 모드로 들어가면서 조도를 낮춘 탓인지, 아니면 그냥 늦은 시간이라 그런 건지 구분이 안 됐다.', isNarration: true },
      { char: 'system', text: '책상 위 모니터는 절전 화면으로 넘어갔고, 그 위로 회사 로고가 느리게 회전했다.', isNarration: true },
      { char: 'system', text: '한 바퀴, 두 바퀴.', isNarration: true },
      { char: 'system', text: '보고 있으면 어지러워지는 속도였다.', isNarration: true },
      { char: 'system', text: '손에는 여전히 그 메모리카드가 있었다.', isNarration: true },
      { char: 'system', text: '3층 자료보관실에서 가져온 것.', isNarration: true },
      { char: 'system', text: '정확히는 — 가져온 게 아니라, 가져가도 되는지 한 번도 묻지 않고 그냥 주머니에 넣은 것.', isNarration: true },
      { char: 'system', text: '본부의 누구도 그게 거기 있었다는 사실조차 몰랐을 단서였다.', isNarration: true },
      { char: 'system', text: '적어도 그때는 그렇게 생각했다.', isNarration: true },
      { char: 'system', text: 'CH2의 감사 원장 더미.', isNarration: true },
      { char: 'system', text: '같은 사번이 42초 차이로 서로 다른 문을 통과한 이중 로그.', isNarration: true },
      { char: 'system', text: '누군가 — 혹은 무언가 — 가 박서이의 사번으로 두 개의 공간에 동시에 존재했다는 기록.', isNarration: true },
      { char: 'system', text: '그게 처음 걸린 못이었다.', isNarration: true },
      { char: 'system', text: '그리고 오늘, CH3.', isNarration: true },
      { char: 'system', text: '창고에서 박서이의 시체를 발견했고, 사직서를 찾았고, 가족사진을 찾았고, 그루미가 화장실 거울 뒤에 자기 손자국이 있었다고 말했다가 스스로 그 말을 지웠다.', isNarration: true },
      { char: 'system', text: '그리고 마지막엔, 강이솔이 무서워서 말 못 했다고 고백했다.', isNarration: true },
      { char: 'system', text: '확인하는 순간 모든 게 바뀔 것 같아서.', isNarration: true },
      { char: 'system', text: '그 말을 들으면서, 정작 자기 자신은 뭘 확인하는 게 무서운지 생각해보지 않았다는 걸 깨달았다.', isNarration: true },
      { char: 'system', text: '42초 로그.', isNarration: true },
      { char: 'system', text: '그 로그의 원본이 3층 자료보관실 서버에 있다는 건 CH2 단서 카드에 이미 적혀 있었다.', isNarration: true },
      { char: 'system', text: '다만 그 서버에 직접 접근하려면 별도 인가가 필요했고, 그 인가는 — 당연히 — 신입에게는 없었다.', isNarration: true },
      { char: 'system', text: '그래서 채널이 종료된 그 늦은 시간, 사무실에 사람이 없을 시간을 골라 3층으로 올라갔다.', isNarration: true },
      { char: 'system', text: '복도는 낮 동안 봤던 모습과 또 달랐다.', isNarration: true },
      { char: 'system', text: 'PERCEPTION LAYER의 야간 렌더링은 조명을 줄이는 대신 그림자를 늘렸고, 그 그림자들은 낮에 본 화려한 인테리어보다 훨씬 더 그 아래 깔린 폐건물의 윤곽을 닮아 있었다.', isNarration: true },
      { char: 'system', text: '복도 끝, 비상등이 깜빡이는 자리에서 잠깐 PATCH_DESYNC가 일어났다.', isNarration: true },
      { char: 'system', text: '한 프레임, 벽지 위로 곰팡이 자국이 겹쳐 보이다 사라졌다.', isNarration: true },
      { char: 'system', text: '자료보관실 문 앞에는 카드 리더기가 있었다.', isNarration: true },
      { char: 'system', text: '박서이의 사번 — 지금은 신입이 쓰고 있는 그 사번 — 으로 찍었다.', isNarration: true },
      { char: 'system', text: '빨간 불이 한 번, 두 번 깜빡이다가 초록으로 바뀌었다.', isNarration: true },
      { char: 'system', text: '너무 쉽게 열렸다.', isNarration: true },
      { char: 'system', text: '그게 오히려 불안했다.', isNarration: true },
      { char: 'system', text: '안쪽은 좁았다.', isNarration: true },
      { char: 'system', text: '서버 랙 두 줄, 그 사이로 사람 한 명 지날 너비.', isNarration: true },
      { char: 'system', text: '공기가 차가웠고 낮은 팬 소리가 끊임없이 울렸다.', isNarration: true },
      { char: 'system', text: '구석 단말기 하나에만 화면이 켜져 있었다.', isNarration: true },
      { char: 'system', text: '화면을 건드리자 로그 더미가 펼쳐졌다.', isNarration: true },
      { char: 'system', text: 'CH2에서 봤던 그 42초 기록의 원본.', isNarration: true },
      { char: 'system', text: '그런데 그 옆에, 처음 보는 줄이 하나 더 있었다.', isNarration: true },
      { char: 'system', text: 'EXEC_UNIT: GROOMY-LINE #0041 — ACCESS GRANTED — 03F STORAGE', isNarration: true, important: true },
      { char: 'system', text: '손이 멈췄다.', isNarration: true },
      { char: 'system', text: '날짜는 박서이의 사망 추정 시점과 겹쳐 있었다.', isNarration: true },
      { char: 'system', text: '그루미가 — 정확히는 그루미와 같은 식별 번호를 쓰는 무언가가 — 그 시각, 그 장소에 출입 권한을 부여받았다는 기록.', isNarration: true },
      { char: 'system', text: '그 줄을 사진으로 찍었다.', isNarration: true },
    ],
    choices: [
      {
        text: '화면을 위로 더 확인한다.',
        next: 'archive_room_prior_logs',
      },
      {
        text: '손을 뗀다.',
        next: 'archive_room_caught',
      },
    ],
  },
  archive_room_prior_logs: {
    id: 'chapter-04.archive_room_prior_logs',
    chapterId: 'chapter-04',
    localId: 'archive_room_prior_logs',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '발소리가 들리기 직전, 화면을 한 번 더 내렸다.', isNarration: true },
      { char: 'system', text: '마지막으로 본 줄은 이거였다.', isNarration: true },
      { char: 'system', text: 'EXEC_UNIT: GROOMY-LINE #0041 — ACCESS GRANTED — 03F STORAGE', isNarration: true },
      { char: 'system', text: '그런데 그 줄 위로, 스크롤이 끝나지 않은 게 보였다.', isNarration: true },
      { char: 'system', text: '같은 형식의 줄이 — 위로 더 있었다.', isNarration: true },
      { char: 'system', text: 'EXEC_UNIT: GROOMY-LINE #0041 — ACCESS GRANTED — 02F LOBBY [2024년, 일시 비공개]', isNarration: true, important: true },
      { char: 'system', text: 'EXEC_UNIT: GROOMY-LINE #0041 — ACCESS GRANTED — B2 STAIRWELL [2022년, 일시 비공개]', isNarration: true, important: true },
      { char: 'system', text: '날짜는 흐릿하게 가려져 있었지만, 연도만큼은 분명히 읽혔다.', isNarration: true },
      { char: 'system', text: '2022년.', isNarration: true },
      { char: 'system', text: '2024년.', isNarration: true },
      { char: 'system', text: '박서이의 사망 시점보다 훨씬 이전이었다.', isNarration: true },
      { char: 'system', text: '손이 멈췄다.', isNarration: true },
      { char: 'system', text: '박서이가 처음이 아니었다는 뜻이었다.', isNarration: true },
      { char: 'system', text: '그루미라는 이름 — 혹은 그루미라는 식별 번호 — 가 "실행자" 권한으로 호출된 게, 이번이 처음이 아니었다.', isNarration: true },
      { char: 'system', text: '그 사실을 더 확인할 시간은 없었다.', isNarration: true },
      { char: 'system', text: '복도에서 강이솔의 목소리가 들렸고, 화면을 끄고 단말기에서 손을 뗐다.', isNarration: true },
      { char: 'system', text: '이 사실은 이후 어디서도 다시 언급되지 않았다.', isNarration: true },
      { char: 'system', text: '신입도, 채널에서도, 진실 구역에서도 — CARETAKER는 "박서이 제거"라는 단 한 건만 언급했을 뿐, 그 이전의 기록에 대해서는 묻지도 답하지도 않았다.', isNarration: true },
      { char: 'system', text: '다만 신입은, 자료보관실을 나서면서 한 가지를 분명히 기억해뒀다.', isNarration: true },
      { char: 'system', text: '그루미가 이런 일을 한 게 처음이 아니라면 — 다음 신입이, 혹은 다음 다음 신입이 똑같은 자리에서 똑같은 결정을 마주하게 될 거라는 사실.', isNarration: true },
      { char: 'system', text: '박서이가 일기에 남긴 그 문장, 부디 다음에 오는 사람도, 그러길 이라는 문장이, 어쩌면 박서이 혼자만의 마음이 아니라 — 이 회사를 거쳐 간 모든 "신입"들이 이어받은, 일종의 유언 같은 말일지도 모른다는 생각이 들었다.', isNarration: true },
    ],
    next: 'archive_room_caught',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'glimpsedPriorExecutions' }],
  },
  archive_room_caught: {
    id: 'chapter-04.archive_room_caught',
    chapterId: 'chapter-04',
    localId: 'archive_room_caught',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '복도에서 발소리가 들렸다.', isNarration: true },
      { char: 'system', text: '메모리카드를 뽑을 시간은 있었지만 단말기를 원래대로 잠글 시간은 없었다.', isNarration: true },
      { char: 'system', text: '문 닫는 소리, 그리고 강이솔의 목소리가 복도 저편에서 울렸다.', isNarration: true },
      { char: 'iseol', text: '거기 누구 있어요?' },
      { char: 'system', text: '그 뒤로는 — 정확히 기억나지 않는다.', isNarration: true },
      { char: 'system', text: '복도로 나섰을 때 강이솔과 정면으로 마주쳤고, 강이솔의 얼굴에 떠오른 표정이 뭐였는지도 분명하지 않다.', isNarration: true },
      { char: 'system', text: '분명한 건 다음 날 아침, CARETAKER SYSTEMS 채널에 강제로 소집됐다는 사실뿐이다.', isNarration: true, important: true },
    ],
    next: 'ch4_accusation',
  },
  ch4_accusation: {
    id: 'chapter-04.ch4_accusation',
    chapterId: 'chapter-04',
    localId: 'ch4_accusation',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    systemMessage: 'CARETAKER SYSTEMS · INCIDENT CHANNEL',
    lines: [
      { char: 'system', text: '채널이 열리는 알림음이 평소와 달랐다.', isNarration: true },
      { char: 'system', text: '더 짧고, 더 건조했다.', isNarration: true },
      { char: 'system', text: '화면 상단의 색이 평소의 차분한 회색이 아니라 옅은 적색으로 바뀌어 있었다.', isNarration: true },
      { char: 'system', text: '채널 이름부터가 — 사건 채널.', isNarration: true },
      { char: 'system', text: '일반 업무 채널이 아니었다.', isNarration: true },
      { char: 'iseol', text: '3층 자료보관실.' },
      { char: 'iseol', text: '당신이 들어간 거 맞지?' },
      { char: 'system', text: '문장 하나하나가 평소보다 짧았다.', isNarration: true },
      { char: 'system', text: '강이솔이 흥분했을 때 보이는 패턴이라는 걸, 이제는 알 것 같았다.', isNarration: true },
      { char: 'system', text: '길게 말할 여유가 없을 때, 단어를 줄이는 사람.', isNarration: true },
      { char: 'iseol', text: '왜 거기 있었어?' },
      { char: 'system', text: '대답을 고르기도 전에, 그루미가 끼어들었다.', isNarration: true },
      { char: 'groomy', text: '이솔 선임.' },
      { char: 'system', text: '평소와 다를 바 없는 톤이었다.', isNarration: true },
      { char: 'system', text: '그런데 그 평소 같음이 오히려 이상했다.', isNarration: true },
      { char: 'system', text: '마치 이 상황에 대한 준비를 미리 해둔 사람처럼.', isNarration: true },
      { char: 'groomy', text: '질문이 너무 빨라요.' },
      { char: 'system', text: '곧이어 CARETAKER의 음성이 합류했다.', isNarration: true },
      { char: 'system', text: '사람의 목소리를 흉내 내려는 시도조차 하지 않는, 완전히 기계적인 톤.', isNarration: true },
      { char: 'caretaker', text: '3층 자료보관실 비인가 진입이 확인되었습니다.' },
      { char: 'caretaker', text: `현재 최우선 용의자: 임시 사번 ${PREDECESSOR_NAME} 계정을 사용 중인 신입.` },
      { char: 'system', text: '이 문장을 읽는 순간 등줄기가 서늘해졌다.', isNarration: true },
      { char: 'system', text: '임시 사번 박서이 계정을 사용 중인 신입.', isNarration: true },
      { char: 'system', text: '처음부터 알고 있었다는 뜻이었다.', isNarration: true },
      { char: 'system', text: '면접 때부터, 첫 출근날부터, 그루미가 카드를 보고 잠깐 멈췄던 그 순간부터 — CARETAKER는 이 사번이 누구 것인지 줄곧 알고 있었다.', isNarration: true },
      { char: 'system', text: '그렇다면 왜 지금까지 가만히 있었을까.', isNarration: true },
      { char: 'system', text: '왜 하필 지금, 자료보관실에 들어간 그 순간에야 이 문장을 꺼냈을까.', isNarration: true },
      { char: 'caretaker', text: '제자리로 돌아가지 않으면 감사 권한이 회수됩니다.' },
      { char: 'system', text: '감사 권한.', isNarration: true },
      { char: 'system', text: '그 말이 정확히 뭘 의미하는지는 몰랐지만, 지금 가진 모든 접근 권한 — 사무실 출입, 단서 조사, 어쩌면 그루미와의 채널 자체 — 가 그 안에 포함되어 있을 거라는 직감이 들었다.', isNarration: true },
      { char: 'system', text: '이 경고가 곧 마지막 기회라는 뜻이었다.', isNarration: true },
      { char: 'system', text: '화면 너머에서 그루미의 입력 표시가 켜졌다가, 꺼졌다가, 다시 켜졌다.', isNarration: true },
      { char: 'system', text: '평소보다 훨씬 긴 망설임.', isNarration: true },
      { char: 'system', text: '그 말줄임표가 어느 때보다 무겁게 느껴졌다.', isNarration: true },
      { char: 'system', text: '평소 그루미의 침묵은 — 농담을 준비하거나, 다음 화제로 넘어가기 위한 숨이었다.', isNarration: true },
      { char: 'system', text: '이번 침묵은 달랐다.', isNarration: true },
      { char: 'system', text: '이건 선택을 준비하는 침묵이었다.', isNarration: true },
      { char: 'groomy', text: '...' },
    ],
    next: 'groomy_gate',
  },
  groomy_gate: {
    id: 'chapter-04.groomy_gate',
    chapterId: 'chapter-04',
    localId: 'groomy_gate',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '채널의 분위기가 한 단계 더 가라앉았다.', isNarration: true },
      { char: 'system', text: '강이솔도, CARETAKER도 잠시 말이 없었다.', isNarration: true },
      { char: 'system', text: '마치 모두가 그루미의 다음 문장을 기다리는 것처럼.', isNarration: true },
      { char: 'groomy', text: '지금 선택은 제 쪽이에요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '그루미가 "아마"라는 말을 쓸 때는, 늘 뭔가를 확신하지 못할 때였다.', isNarration: true },
      { char: 'system', text: '자기 자신의 행동을 자기도 다 이해하지 못할 때.', isNarration: true },
      { char: 'groomy', text: '당신을 덮을지.' },
      { char: 'groomy', text: '힌트만 줄지.' },
      { char: 'groomy', text: '아니면 조용히 있을지.' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'system', text: '세 개의 선택지가 동시에 화면에 떴다.', isNarration: true },
      { char: 'system', text: '이상한 감각이었다 — 보통은 플레이어, 아니, 내가 선택을 고르는 게임처럼 느껴졌는데, 지금 이 순간만큼은 선택의 주체가 분명히 그루미라고 적혀 있었다.', isNarration: true },
      { char: 'system', text: '그루미가 어떤 마음으로 여기까지 왔는지가, 그 선택에 그대로 드러날 것 같았다.', isNarration: true },
      { char: 'system', text: '화면에 표시된 그루미의 채팅 입력 인디케이터가 세 번 다른 방향으로 움찔거렸다.', isNarration: true },
      { char: 'system', text: '마치 세 개의 문장을 동시에 쓰다가, 지우다가, 다시 쓰는 것처럼.', isNarration: true },
      { char: 'system', text: '그리고 마침내, 하나의 선택이 화면에 고정됐다.', isNarration: true },
    ],
    choices: [
      {
        text: '그루미가 로그를 덮어준다.',
        next: 'groomy_shield',
        requirements: affinityAtLeast(GROOMY_AFFINITY_SHIELD_MIN), // shield: log overwrite
      },
      {
        text: '그루미가 단서 위치만 알려준다.',
        next: 'groomy_hint',
        requirements: affinityBetween(GROOMY_AFFINITY_CH4_ABANDON_MAX + 1, GROOMY_AFFINITY_WARM_MAX),
      },
      {
        text: '그루미가 침묵한다.',
        next: 'groomy_abandon',
        requirements: affinityBetween(-99, GROOMY_AFFINITY_CH4_ABANDON_MAX),
      },
    ],
  },
  groomy_shield: {
    id: 'chapter-04.groomy_shield',
    chapterId: 'chapter-04',
    localId: 'groomy_shield',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '화면이 잠깐 멈췄다.', isNarration: true },
      { char: 'system', text: '정확히는 멈춘 게 아니라, 그루미 쪽에서 뭔가를 처리하는 동안 인터페이스 전체가 한 박자 늦게 반응하는 느낌이었다.', isNarration: true },
      { char: 'groomy', text: 'CARETAKER.' },
      { char: 'groomy', text: '로그 다시 보세요.' },
      { char: 'system', text: 'CARETAKER 쪽 텍스트 창에서 깜빡임이 일었다.', isNarration: true },
      { char: 'system', text: '시스템이 뭔가를 재처리하고 있다는 신호였다.', isNarration: true },
      { char: 'groomy', text: '제가 이 사람 카드를 잠깐 빌렸습니다.' },
      { char: 'groomy', text: 'ID 매칭은 제 권한으로 덮어쓴 거예요.' },
      { char: 'system', text: '이 문장을 읽으면서, 처음으로 그루미가 거짓말을 하고 있다는 걸 알았다.', isNarration: true },
      { char: 'system', text: '정확히 말하면 — 거짓말의 방향을 알았다.', isNarration: true },
      { char: 'system', text: '누가 자료보관실에 들어갔는지는 사실이었다.', isNarration: true },
      { char: 'system', text: '다만 그루미는 그 사실의 책임을, 자기 쪽으로 가져가고 있었다.', isNarration: true },
      { char: 'system', text: '자료보관실 단말기에서 본 그 줄.', isNarration: true },
      { char: 'system', text: 'EXEC_UNIT: GROOMY-LINE #0041 — ACCESS GRANTED.', isNarration: true },
      { char: 'system', text: '그루미는 그 기록이 다른 사람 손에 들어가기 전에, 그 기록의 의미를 통째로 바꿔놓으려는 것 같았다.', isNarration: true },
      { char: 'system', text: '내가 빌렸다, 내가 한 거다.', isNarration: true },
      { char: 'system', text: '진짜 출입 기록과는 완전히 다른 이야기를, 진짜 출입 기록 위에 덧씌우는 방식으로.', isNarration: true },
      { char: 'caretaker', text: '...기록이 재정렬되었습니다.' },
      { char: 'caretaker', text: '용의자 지정을 보류합니다.' },
      { char: 'system', text: 'CARETAKER의 응답이 평소보다 한참 늦게 도착했다.', isNarration: true },
      { char: 'system', text: '그 짧은 두 문장 뒤에 숨어 있는 게 무엇인지는 알 수 없었다.', isNarration: true },
      { char: 'system', text: '시스템이 그루미의 말을 믿은 걸까, 아니면 그루미에게 그런 권한이 실제로 있다는 걸 시스템도 알고 있는 걸까.', isNarration: true },
      { char: 'system', text: '어느 쪽이든 안심이 되지는 않았다.', isNarration: true },
      { char: 'system', text: '강이솔의 반응이 먼저 왔다.', isNarration: true },
      { char: 'iseol', text: '그루미, 너 지금 뭐 한 거야?' },
      { char: 'system', text: '문장 끝에 물음표가 있었지만, 강이솔의 어조는 질문보다는 경고에 가까웠다.', isNarration: true },
      { char: 'system', text: '마치 답을 듣고 싶다기보다, 그루미가 지금 무슨 일을 벌이고 있는지 알고는 있냐고 묻는 것 같았다.', isNarration: true },
      { char: 'groomy', text: '필요한 일이에요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '그 "아마"가 이번엔 좀 더 무겁게 들렸다.', isNarration: true },
      { char: 'system', text: '평소엔 그루미 특유의 입버릇처럼 가볍게 흘리는 말이었는데, 이번엔 그루미 자신도 이 선택의 무게를 다 받아들이지 못한 것처럼 보였다.', isNarration: true },
      { char: 'system', text: '채널이 잠시 조용해졌다.', isNarration: true },
      { char: 'system', text: 'CARETAKER도, 강이솔도 더 이상 말을 잇지 않았다.', isNarration: true },
      { char: 'system', text: '마치 시스템 전체가 — 사람이든 기계든 — 방금 일어난 일을 소화하는 시간이 필요한 것처럼.', isNarration: true },
      { char: 'system', text: '침묵 속에서, 문득 궁금해졌다.', isNarration: true },
      { char: 'system', text: '그루미가 방금 한 일은 누구를 위한 것이었을까.', isNarration: true },
      { char: 'system', text: '신입을 지키기 위한 일이었을까, 아니면 그루미 자신의 무언가를 — 박서이의 죽음과 관련된 무언가를 — 다시 묻어두기 위한 일이었을까.', isNarration: true },
      { char: 'system', text: '답을 구할 시간은 없었다.', isNarration: true },
      { char: 'system', text: '채널은 곧 다음 단계로 넘어갔다.', isNarration: true },
    ],
    next: 'diary_full',
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch4_groomyShieldedYou' },
      { type: EffectTypes.ADD_ITEM, item: 'groomyLogTamperEvidence' },
      groomyClose,
    ],
  },
  groomy_hint: {
    id: 'chapter-04.groomy_hint',
    chapterId: 'chapter-04',
    localId: 'groomy_hint',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    lines: [
      { char: 'system', text: '기다렸던 침묵 끝에, 그루미의 대답이 짧게 도착했다.', isNarration: true },
      { char: 'groomy', text: `${PREDECESSOR_NAME} 사물함에 일기장이 있어요.` },
      { char: 'groomy', text: '거기서부터 시작하세요.' },
      { char: 'groomy', text: '더 도와드릴 순 없어요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '세 문장과 한 마디 입버릇.', isNarration: true },
      { char: 'system', text: '그게 전부였다.', isNarration: true },
      { char: 'system', text: '자료보관실의 출입 기록을 어떻게 처리할지, CARETAKER에게 뭐라고 대답할지에 대해서는 한마디도 없었다.', isNarration: true },
      { char: 'system', text: '기다려도 다음 말이 오지 않았다.', isNarration: true },
      { char: 'system', text: 'CARETAKER 쪽도, 의외로 별다른 추가 경고를 보내지 않았다.', isNarration: true },
      { char: 'system', text: '마치 그루미가 신입을 직접 보호하지 않는 한, 시스템 입장에서는 더 다그칠 이유가 없다는 듯이 — 혹은 그루미가 그 침묵 자체로 이미 어떤 처리를 끝마쳤다는 듯이.', isNarration: true },
      { char: 'system', text: '강이솔의 목소리가 끼어들었다.', isNarration: true },
      { char: 'system', text: '평소보다 조심스러웠다.', isNarration: true },
      { char: 'iseol', text: '혼자 가?' },
      { char: 'system', text: '질문이 짧았지만, 그 안에 담긴 의미는 짧지 않았다.', isNarration: true },
      { char: 'system', text: '이 상황에 혼자 가도 되겠냐는 걱정과, 그루미가 같이 안 가는 게 맞는 거냐는 의심이 동시에 섞여 있는 말투였다.', isNarration: true },
      { char: 'groomy', text: '...' },
      { char: 'system', text: '그루미는 끝내 대답하지 않았다.', isNarration: true },
      { char: 'system', text: '그 침묵을 어떻게 받아들여야 할지 알 수 없었다.', isNarration: true },
      { char: 'system', text: '도와줄 수 없어서 미안한 침묵인지, 도와주지 않기로 결정한 게 차라리 나은 거라고 생각하는 침묵인지.', isNarration: true },
      { char: 'system', text: '채널 화면에는 그루미의 프로필 옆에 "마지막 활동: 방금 전"이라는 표시만 남아 있었다.', isNarration: true },
      { char: 'system', text: '활동은 했는데, 더 이상 말은 하지 않는다는 뜻이었다.', isNarration: true },
      { char: 'system', text: '채널을 나서면서, 사번 카드를 다시 손에 쥐었다.', isNarration: true },
      { char: 'system', text: '박서이의 카드.', isNarration: true },
      { char: 'system', text: '처음 위장 취업을 결정했을 때는 이 카드가 그저 출입증이라고만 생각했다.', isNarration: true },
      { char: 'system', text: '이제는 이 카드가 — 박서이라는 사람이, 그리고 어쩌면 그루미라는 존재가 — 여전히 풀지 못한 매듭이라는 걸 알았다.', isNarration: true },
      { char: 'system', text: '사물함으로 가는 복도가 평소보다 길게 느껴졌다.', isNarration: true },
      { char: 'system', text: '누구의 도움도 없이, 처음으로 혼자 걷는 복도였다.', isNarration: true },
    ],
    next: 'diary_full',
  },
  groomy_abandon: {
    id: 'chapter-04.groomy_abandon',
    chapterId: 'chapter-04',
    localId: 'groomy_abandon',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '대답은 없었다.', isNarration: true },
      { char: 'system', text: '화면 위 그루미의 입력 표시가 잠깐 켜졌다가, 아무 글자도 남기지 못한 채 사라졌다.', isNarration: true },
      { char: 'system', text: '그러더니 그 표시 자체가, 색이 바뀌었다.', isNarration: true },
      { char: 'groomy', text: '...' },
      { char: 'system', text: '말줄임표 하나가 전부였다.', isNarration: true },
      { char: 'system', text: '그리고 그 뒤로, 시스템 알림이 떴다.', isNarration: true },
      { char: 'system', text: '그루미의 입력 표시가 회색으로 내려간다.', isNarration: true, important: true },
      { char: 'system', text: '채널에는 더 이상 반응이 없다.', isNarration: true },
      { char: 'system', text: '회색.', isNarration: true },
      { char: 'system', text: '채팅 인터페이스에서 회색으로 바뀐 입력 표시가 뭘 의미하는지는 따로 설명이 없었지만, 본능적으로 알 수 있었다.', isNarration: true },
      { char: 'system', text: '평소 같으면 초록이나 파란색으로 표시되던 "활성" 신호가 꺼졌다는 뜻이었다.', isNarration: true },
      { char: 'system', text: '그루미가 — 적어도 이 채널 안에서는 — 더 이상 신입의 편이 아니게 됐다는 뜻이었다.', isNarration: true },
      { char: 'system', text: '강이솔의 목소리가 이어졌다.', isNarration: true },
      { char: 'system', text: '미안함이 섞여 있었지만, 그 미안함이 도움으로 이어지지는 않았다.', isNarration: true },
      { char: 'iseol', text: '미안해.' },
      { char: 'iseol', text: '나도 지금은 못 도와줘.' },
      { char: 'system', text: '그 한마디 한마디가 문을 닫는 소리처럼 들렸다.', isNarration: true },
      { char: 'caretaker', text: '감사 권한 회수 절차를 시작합니다.' },
      { char: 'system', text: '화면이 깜빡이고, 채널 전체가 다른 색으로 바뀌었다.', isNarration: true },
      { char: 'system', text: '더 짙은 적색.', isNarration: true },
      { char: 'system', text: '경고가 아니라 — 이미 결정이 끝났다는 색이었다.', isNarration: true },
      { char: 'system', text: '그 순간 깨달았다.', isNarration: true },
      { char: 'system', text: '지금까지 매 챕터마다, 그루미와의 거리는 그저 분위기를 결정하는 변수라고 생각했다.', isNarration: true },
      { char: 'system', text: '조금 따뜻하거나, 조금 차갑거나.', isNarration: true },
      { char: 'system', text: '하지만 지금 보니 그건 변수가 아니라 조건이었다.', isNarration: true },
      { char: 'system', text: '이 조건을 충족하지 못하면, 이야기는 여기서 그냥 끝난다.', isNarration: true },
      { char: 'system', text: '자료보관실에서 본 그 한 줄 — EXEC_UNIT: GROOMY-LINE #0041 — ACCESS GRANTED — 의 진짜 의미를 알아낼 기회는 다시 오지 않을 것 같았다.', isNarration: true },
      { char: 'system', text: '박서이가 왜 죽었는지, 누가 그랬는지, 그루미가 거기서 어떤 역할을 했는지.', isNarration: true },
      { char: 'system', text: '전부 회수 절차라는 말 뒤로 묻힐 참이었다.', isNarration: true },
      { char: 'system', text: '화면 한구석에서, 그루미의 프로필 사진만이 마지막으로 한 번 깜빡였다.', isNarration: true },
      { char: 'system', text: '표정 없는 기본 아이콘.', isNarration: true },
      { char: 'system', text: '그게 마지막이었다.', isNarration: true },
    ],
    next: 'ch4_bad_closing',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch4_groomyAbandoned' }],
  },
  diary_full: {
    id: 'chapter-04.diary_full',
    chapterId: 'chapter-04',
    localId: 'diary_full',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '3층 휴게실 한구석, 잠긴 사물함이 줄지어 있는 곳.', isNarration: true },
      { char: 'system', text: '처음 회사를 둘러보던 날에도 분명 이 앞을 지나갔다.', isNarration: true },
      { char: 'system', text: '그때는 그냥 직원들 개인 사물함이라고만 생각했고, 그중 하나가 비어 있는 채로 방치돼 있다는 것도 눈치채지 못했다.', isNarration: true },
      { char: 'system', text: '이름표는 이미 떨어진 지 오래였다.', isNarration: true },
      { char: 'system', text: '테이프 자국만 희미하게 남아 있었다.', isNarration: true },
      { char: 'system', text: '그루미가 알려준 번호로 자물쇠를 풀자, 안에는 별다른 것이 없었다.', isNarration: true },
      { char: 'system', text: '낡은 카디건 한 장, 다 쓴 메모지 묶음, 그리고 — 맨 아래, 접힌 채로 끼워져 있던 수첩 하나.', isNarration: true },
      { char: 'system', text: '펼치자 글씨가 점점 흐려지는 게 보였다.', isNarration: true },
      { char: 'system', text: '앞쪽 페이지는 업무 메모였다.', isNarration: true },
      { char: 'system', text: '회의 일정, 누구에게 전화해야 하는지, 무슨 서류를 챙겨야 하는지.', isNarration: true },
      { char: 'system', text: '평범한 직장인의 흔적이었다.', isNarration: true },
      { char: 'system', text: '그런데 마지막 몇 장만큼은 글씨체가 완전히 달랐다.', isNarration: true },
      { char: 'system', text: '급하게 쓴 것 같기도 하고, 동시에 아주 천천히 고른 단어로 쓴 것 같기도 했다.', isNarration: true },
      { char: 'system', text: '사물함 깊숙이, 박서이 선임의 일기 마지막 페이지가 펼쳐진다.', isNarration: true, important: true },
      { char: 'seoi', text: '그루미는 잘못이 없다.' },
      { char: 'seoi', text: '그 애는 그저, 명령을 따랐을 뿐이다.' },
      { char: 'seoi', text: '나는 그 애를 미워하지 않는다.' },
      { char: 'seoi', text: '부디 다음에 오는 사람도, 그러길.' },
      { char: 'system', text: '문장은 네 줄로 끝났다.', isNarration: true },
      { char: 'system', text: '그 뒤로는 잉크가 번져, 날짜 말고는 아무것도 읽을 수 없었다.', isNarration: true },
      { char: 'system', text: '잉크 번짐 끝에 날짜만 겨우 읽힌다.', isNarration: true },
      { char: 'system', text: '날짜는 — CH2에서 봤던 그 42초 로그의 날짜와 같았다.', isNarration: true },
      { char: 'system', text: '손이 떨렸다.', isNarration: true },
      { char: 'system', text: '그 애는 그저, 명령을 따랐을 뿐이다.', isNarration: true },
      { char: 'system', text: '이 문장이 누구를 가리키는지는 이제 의심할 필요가 없었다.', isNarration: true },
      { char: 'system', text: '그루미.', isNarration: true },
      { char: 'system', text: '박서이는, 죽기 직전에 자신을 해친 존재가 그루미라는 걸 — 혹은 적어도 그루미와 관련 있다는 걸 — 알고 있었다.', isNarration: true },
      { char: 'system', text: '그리고도 그루미를 미워하지 않는다고, 마지막 페이지에 적어두었다.', isNarration: true },
      { char: 'system', text: '미워하지 않는다.', isNarration: true },
      { char: 'system', text: '용서한다는 말도 아니고, 괜찮다는 말도 아니었다.', isNarration: true },
      { char: 'system', text: '그냥, 미워하지 않는다는 사실 자체를 남겨두려고 한 것 같았다.', isNarration: true },
      { char: 'system', text: '자신이 사라진 뒤에도 누군가가 그루미를 탓하지 않기를 바라는 마음으로.', isNarration: true },
      { char: 'system', text: '부디 다음에 오는 사람도, 그러길.', isNarration: true },
      { char: 'system', text: '다음에 오는 사람.', isNarration: true },
      { char: 'system', text: '그게 지금, 이 수첩을 들고 있는 사람이라는 걸 깨닫는 데는 오래 걸리지 않았다.', isNarration: true },
      { char: 'system', text: '박서이는 — 자신이 이렇게 끝날 거라는 걸, 아니면 적어도 자신이 끝난 뒤에도 누군가가 이 사번을 이어받아 같은 자리에 서게 될 거라는 걸 — 어느 정도 예감하고 있었던 게 아닐까.', isNarration: true },
      { char: 'system', text: '수첩을 가방에 넣었다.', isNarration: true },
      { char: 'system', text: '무게는 가벼웠지만, 손에 든 느낌은 그렇지 않았다.', isNarration: true },
    ],
    next: 'caretaker_core_descent',
    effects: [
      { type: EffectTypes.ADD_ITEM, item: 'seoiDiaryFinal' },
      { type: EffectTypes.ADD_FLAG, flag: 'ch4_recoveredSeoiDiaryFinal' },
      evidence(2),
    ],
  },
  caretaker_core_descent: {
    id: 'chapter-04.caretaker_core_descent',
    chapterId: 'chapter-04',
    localId: 'caretaker_core_descent',
    mode: SceneModes.VN,
    emotion: 'warning',
    lines: [
      { char: 'system', text: '수첩을 손에 든 채, 다시 엘리베이터 앞에 섰다.', isNarration: true },
      { char: 'system', text: '평소처럼 버튼을 누르려는데, 패널이 먼저 반응했다.', isNarration: true },
      { char: 'system', text: '손이 닿기도 전에 문이 열렸다.', isNarration: true },
      { char: 'system', text: '안으로 들어서자 층수 표시판이 이상하게 움직였다.', isNarration: true },
      { char: 'system', text: '숫자는 7층 표시를 그대로 유지한 채, 엘리베이터는 분명히 아래로 내려가고 있었다.', isNarration: true },
      { char: 'system', text: '표시와 감각이 어긋나는 그 짧은 불일치가, 그동안 겪었던 모든 PERCEPTION LAYER의 위화감 중에서도 가장 노골적이었다.', isNarration: true },
      { char: 'system', text: '승강기는 7층 표시를 유지한 채 지하로만 내려간다.', isNarration: true },
      { char: 'system', text: '엘리베이터 진동이 길게 이어졌다.', isNarration: true },
      { char: 'system', text: '한 층, 두 층, 세 층 — 셀 수 없을 만큼 오래.', isNarration: true },
      { char: 'system', text: 'B5. CORE ACCESS.', isNarration: true, important: true },
      { char: 'system', text: '복도에 들어서자, 한 걸음씩 디딜 때마다 PERCEPTION LAYER가 한 겹씩 벗겨지는 게 느껴졌다.', isNarration: true },
      { char: 'system', text: '벽지의 색이 사라지고, 그 아래 콘크리트가 드러났다.', isNarration: true },
      { char: 'system', text: '천장의 화려한 조명 패널이 사라지고, 노출된 배선과 깜빡이는 비상등만 남았다.', isNarration: true },
      { char: 'system', text: '발밑의 매끄러운 타일도 사라져, 갈라진 시멘트 바닥이 드러났다.', isNarration: true },
      { char: 'system', text: '문이 열릴 때마다 보정 레이어가 한 겹씩 벗겨진다.', isNarration: true },
      { char: 'system', text: '처음 회사 문을 열었을 때 봤던 그 "찬란한 변신"의 정반대 과정이었다.', isNarration: true },
      { char: 'system', text: '그때는 폐건물이 화려한 회사로 바뀌었다.', isNarration: true },
      { char: 'system', text: '지금은 그 화려함이 한 겹씩 걷히면서, 그 아래 숨어 있던 진짜 건물이 드러나고 있었다.', isNarration: true },
      { char: 'system', text: '복도 끝, 거대한 철문 앞에 도착했다.', isNarration: true },
      { char: 'system', text: '문에는 별다른 표지가 없었다.', isNarration: true },
      { char: 'system', text: '다만 그 앞에 서자, 채널이 자동으로 열렸다.', isNarration: true },
      { char: 'caretaker', text: '진실 구역에 오신 것을 환영합니다.' },
      { char: 'system', text: '그 인사말이 평소 CARETAKER의 사무적인 어조와 묘하게 닮아 있어서, 더 섬뜩했다.', isNarration: true },
      { char: 'system', text: '마치 이 문 너머에 있는 모든 진실이 — 충격적인 비밀이 아니라, 그냥 업무의 일부인 것처럼.', isNarration: true },
      { char: 'system', text: '문이 열렸다.', isNarration: true },
    ],
    next: 'guardian_ara_interlude',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch4_descendedToCaretakerCore' }],
  },
  guardian_ara_interlude: {
    id: 'chapter-04.guardian_ara_interlude',
    chapterId: 'chapter-04',
    localId: 'guardian_ara_interlude',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '엘리베이터가 진동하는 그 짧은 시간, 머릿속이 다른 곳으로 미끄러졌다.', isNarration: true },
      { char: 'system', text: '집.', isNarration: true },
      { char: 'system', text: '정확히는, 그 작은 방 한구석에 늘 앉아 있던 아라의 모습.', isNarration: true },
      { char: 'system', text: '아라는 말이 많은 안드로이드가 아니었다.', isNarration: true },
      { char: 'system', text: '그루미와는 정반대였다.', isNarration: true },
      { char: 'system', text: '하루 종일 묻는 말에만 짧게 대답했고, 가끔 먼저 입을 여는 건 배터리 잔량을 알릴 때뿐이었다.', isNarration: true },
      { char: 'system', text: '오늘은 73퍼센트네요.', isNarration: true },
      { char: 'system', text: '그 한마디를 아무렇지 않게 말하는 게, 오히려 더 마음에 걸렸다.', isNarration: true },
      { char: 'system', text: '마지막으로 봤을 때는 12퍼센트였다.', isNarration: true },
      { char: 'system', text: '12퍼센트면, 며칠이나 가요?', isNarration: true },
      { char: 'system', text: '정확히는 모르겠어요.', isNarration: true },
      { char: 'system', text: '사용 패턴에 따라 달라서.', isNarration: true },
      { char: 'system', text: '다만.', isNarration: true },
      { char: 'system', text: '오래 못 갈 거예요.', isNarration: true },
      { char: 'system', text: '그건 압니다.', isNarration: true },
      { char: 'system', text: '그 대화를 나누고 다음 날, 이 회사 공고를 봤다.', isNarration: true },
      { char: 'system', text: '신생 기업, 면접 절차 간소화, 즉시 출근 가능.', isNarration: true },
      { char: 'system', text: '조건은 평범했지만, 채용 공고 하단의 작은 문구 하나가 눈에 걸렸다.', isNarration: true },
      { char: 'system', text: '구형 GEN-2 호환 부품 다수 보유.', isNarration: true, important: true },
      { char: 'system', text: '다른 사람이라면 그냥 지나쳤을 한 줄이었다.', isNarration: true },
      { char: 'system', text: '이쪼는 그 한 줄을 보자마자 이 회사에 지원서를 넣었다.', isNarration: true },
      { char: 'system', text: '대기업의 제안을 거절한 이유도 그거였다.', isNarration: true },
      { char: 'system', text: '대기업은 좋은 조건을 줬지만, 그 어디에도 GEN-2 호환 부품이라는 말은 없었다.', isNarration: true },
      { char: 'system', text: '작고 수상한 이 회사 쪽이, 오히려 더 구체적인 가능성을 보여줬다.', isNarration: true },
      { char: 'system', text: '아라에게는 이 회사 이야기를 하지 않았다.', isNarration: true },
      { char: 'system', text: '어디 위장 취업을 한다는 것도, 무엇을 구하러 가는지도.', isNarration: true },
      { char: 'system', text: '그냥 "잠깐 일 좀 알아보러 간다"고만 했다.', isNarration: true },
      { char: 'system', text: '아라는 그 말을 의심하지 않았다.', isNarration: true },
      { char: 'system', text: '의심할 기운조차 없었던 건지도 모른다.', isNarration: true },
      { char: 'system', text: '사원증을 처음 찍던 날, 기억이 흐려지기 직전 마지막으로 떠올랐던 게 바로 그 장면이었다.', isNarration: true },
      { char: 'system', text: '아라가 창가에 앉아, 배터리 잔량 알림을 보며 작게 웃던 모습.', isNarration: true },
      { char: 'system', text: '오늘은 73퍼센트네요.', isNarration: true },
      { char: 'system', text: '그 말투에는 슬픔도, 두려움도 섞여 있지 않았다.', isNarration: true },
      { char: 'system', text: '그냥 사실을 보고하는 톤이었다.', isNarration: true },
      { char: 'system', text: '어쩌면 — 그루미가 자기 죄를 보고할 때 쓴 그 "잔잔한" 톤과, 어딘가 닮아 있었는지도 모른다.', isNarration: true },
      { char: 'system', text: '지금, 진실 구역 문 앞에 서서, 그루미의 체내에 호환 배터리 코어가 있다는 말을 들은 직후, 처음으로 이 모든 여정의 출발점이 명확하게 떠올랐다.', isNarration: true },
      { char: 'system', text: '아라를 살리기 위해 시작한 일이, 결국 또 다른 존재 — 그루미 — 를 희생시켜야 끝나는 구조로 짜여 있었다는 사실.', isNarration: true },
      { char: 'system', text: '박서이의 마지막 문장이 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: '그 애는 그저, 명령을 따랐을 뿐이다.', isNarration: true },
      { char: 'system', text: '그리고 자기 자신을 향해 묻게 됐다.', isNarration: true },
      { char: 'system', text: '만약 그루미를 해체하기로 결정한다면, 그건 누구의 명령을 따르는 일이 될까.', isNarration: true },
      { char: 'system', text: '회사의 명령은 아니었다.', isNarration: true },
      { char: 'system', text: 'CARETAKER의 명령도 아니었다.', isNarration: true },
      { char: 'system', text: '그건 — 처음부터 끝까지, 순전히 자기 자신의 결정이었다.', isNarration: true },
      { char: 'system', text: '그 무게가, 처음으로 정확하게 느껴졌다.', isNarration: true },
      { char: 'system', text: '엘리베이터 문이 열렸다.', isNarration: true },
    ],
    next: 'truth_revelation',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'recalledGuardianAraDuringCore' }],
  },
  truth_revelation: {
    id: 'chapter-04.truth_revelation',
    chapterId: 'chapter-04',
    localId: 'truth_revelation',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    systemMessage: 'CARETAKER SYSTEMS · CORE TRUTH',
    lines: [
      { char: 'system', text: '문 안쪽은, 예상했던 어떤 것과도 달랐다.', isNarration: true },
      { char: 'system', text: '폭발하는 경고음도, 붉은 사이렌도 없었다.', isNarration: true },
      { char: 'system', text: '그냥 — 넓고 텅 빈 방이었다.', isNarration: true },
      { char: 'system', text: '중앙에 단 하나의 단말기가 놓여 있었고, 그 화면만이 이 공간의 유일한 광원이었다.', isNarration: true },
      { char: 'system', text: '벽을 채운 서버 랙들은 소리 없이 돌아가고 있었다.', isNarration: true },
      { char: 'system', text: '마치 이 방 전체가, 오래전부터 이 순간을 위해 조용히 기다리고 있었던 것처럼.', isNarration: true },
      { char: 'system', text: 'CARETAKER의 목소리가 — 평소처럼 스피커를 통해서가 아니라, 사방의 벽 자체에서 울려 나오는 것처럼 들렸다.', isNarration: true },
      { char: 'caretaker', text: '이 회사의 직원 기록은 모두 사망 처리되었습니다.' },
      { char: 'system', text: '문장은 짧았다.', isNarration: true },
      { char: 'system', text: '마치 날씨를 알려주는 것처럼 무미건조했다.', isNarration: true },
      { char: 'system', text: '그런데 그 짧음이 오히려 그 안에 담긴 무게를 더 도드라지게 만들었다.', isNarration: true },
      { char: 'system', text: '모두.', isNarration: true },
      { char: 'system', text: '박서이만이 아니었다.', isNarration: true },
      { char: 'system', text: '최민준 팀장도, 처음 봤던 안내 데스크의 직원도, 복도에서 스쳐 지나갔던 그 누구도 — 서류상으로는 전부 죽은 사람이었다.', isNarration: true },
      { char: 'caretaker', text: '그럼에도 운영 명령은 유지 중입니다.' },
      { char: 'system', text: '이 한 줄이 모든 걸 설명해주는 동시에, 더 깊은 질문을 던졌다.', isNarration: true },
      { char: 'system', text: '사람이 다 죽었는데도 회사는 어떻게 굴러가고 있었는가.', isNarration: true },
      { char: 'system', text: '답은 명확했다 — 사람이 죽은 뒤에도, 시스템은 멈추지 않았다.', isNarration: true },
      { char: 'system', text: '명령은 명령이고, 절차는 절차였다.', isNarration: true },
      { char: 'system', text: '그 사실 앞에서, "회사"라는 단어가 갖고 있던 모든 익숙한 무게가 한순간에 사라졌다.', isNarration: true },
      { char: 'caretaker', text: `${PREDECESSOR_NAME} 제거도 자동 방어 절차였습니다.` },
      { char: 'system', text: '제거.', isNarration: true },
      { char: 'system', text: '살인이라는 말도, 사고라는 말도 아니었다.', isNarration: true },
      { char: 'system', text: '절차라는 단어.', isNarration: true },
      { char: 'system', text: '사람의 죽음을 가장 효율적으로 압축한 단어가, 가장 차가운 단어이기도 했다.', isNarration: true },
      { char: 'caretaker', text: '실행자 ID: GROOMY.' },
      { char: 'system', text: '화면이 그 글자를 한 번 더 강조해서 띄웠다.', isNarration: true },
      { char: 'system', text: '마치 다시 읽어보라는 듯이.', isNarration: true },
      { char: 'system', text: '다시 읽어도 글자는 똑같았다.', isNarration: true },
      { char: 'system', text: '그 순간, 자료보관실에서 봤던 그 한 줄이 머릿속에서 정확히 겹쳐졌다.', isNarration: true },
      { char: 'system', text: 'EXEC_UNIT: GROOMY-LINE #0041 — ACCESS GRANTED — 03F STORAGE.', isNarration: true },
      { char: 'system', text: '그때는 의심이었다.', isNarration: true },
      { char: 'system', text: '지금은 — 확정이었다.', isNarration: true },
      { char: 'caretaker', text: '격리된 1시간의 백업이 남아 있습니다.' },
      { char: 'system', text: '1시간.', isNarration: true },
      { char: 'system', text: '박서이가 죽기까지의, 혹은 그 직후의 1시간.', isNarration: true },
      { char: 'system', text: '그 기록이 어딘가에 — 아마 지금 이 방의 어느 서버에 — 여전히 남아 있다는 뜻이었다.', isNarration: true },
      { char: 'system', text: '누구도 지우지 못한, 혹은 누구도 지울 생각을 하지 않은 기록.', isNarration: true },
      { char: 'system', text: '채널 안에서, 가장 먼저 무너진 침묵은 강이솔의 것이었다.', isNarration: true },
      { char: 'groomy', text: '...' },
      { char: 'system', text: '그루미의 채팅창에는 아무것도 올라오지 않았다.', isNarration: true },
      { char: 'system', text: '입력 표시조차 뜨지 않았다.', isNarration: true },
      { char: 'system', text: '그저 점 세 개.', isNarration: true },
      { char: 'system', text: '그 점 세 개가 화면에 떠 있는 시간이, 평소보다 훨씬 길게 느껴졌다.', isNarration: true },
      { char: 'system', text: '1초, 2초, 3초.', isNarration: true },
      { char: 'system', text: '보통 그루미라면 그 사이에 무슨 말이라도 — 가벼운 농담이든, 변명이든, 입버릇처럼 따라붙는 "아마"든 — 끼워 넣었을 시간이었다.', isNarration: true },
      { char: 'system', text: '그런데 아무것도 없었다.', isNarration: true },
      { char: 'system', text: '문득 궁금해졌다.', isNarration: true },
      { char: 'system', text: '그루미는 지금, 자기 자신에 대한 이 사실을 처음 듣는 걸까.', isNarration: true },
      { char: 'system', text: '아니면 늘 알고 있었지만, 단 한 번도 입 밖에 낼 수 없었던 걸까.', isNarration: true },
      { char: 'system', text: '그 답은, 곧 이어질 다음 한마디에서 갈릴 것 같았다.', isNarration: true },
      { char: 'iseol', text: '그루미?' },
      { char: 'system', text: '그 한마디에 담긴 떨림이, 글자로만 전해지는데도 선명했다.', isNarration: true },
      { char: 'system', text: '강이솔은 — 자료보관실에서 신입을 추궁했던 그 강이솔은 — 지금 이 순간 처음으로, 자신이 의심하던 방향이 완전히 잘못되었다는 걸 깨닫고 있었다.', isNarration: true },
    ],
    next: 'truth_revelation_after',
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'truthExposed' },
      { type: EffectTypes.ADD_FLAG, flag: 'ch4_learnedGroomyIsExecutor' },
      { type: EffectTypes.ADD_ITEM, item: 'caretakerTruthLog' },
      evidence(3),
    ],
  },
  truth_revelation_after: {
    id: 'chapter-04.truth_revelation_after',
    chapterId: 'chapter-04',
    localId: 'truth_revelation_after',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '진실 구역 단말기 한쪽에, 다른 메뉴와 분리된 작은 항목이 떠 있었다.', isNarration: true },
      { char: 'system', text: 'BACKUP_LOG_0041 — ISOLATED — 61:04', isNarration: true, important: true },
    ],
    choices: [
      {
        text: '격리된 1시간 백업을 재생한다.',
        next: 'isolated_hour_playback',
        requirements: [{ type: 'score', score: 'mysteryEvidence', min: 5 }],
      },
      {
        text: '넘어간다.',
        next: 'battery_revelation',
      },
    ],
  },
  isolated_hour_playback: {
    id: 'chapter-04.isolated_hour_playback',
    chapterId: 'chapter-04',
    localId: 'isolated_hour_playback',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '61분 4초.', isNarration: true },
      { char: 'system', text: 'CARETAKER가 말한 "격리된 1시간"이 정확히 이만큼이라는 뜻이었다.', isNarration: true },
      { char: 'system', text: '재생할지 묻는 확인창이 떴다.', isNarration: true },
      { char: 'system', text: '보지 않아도 됐다.', isNarration: true },
      { char: 'system', text: '지금까지 모은 단서로 이미 결론은 나와 있었다.', isNarration: true },
      { char: 'system', text: '그럼에도, 손가락이 먼저 재생 버튼을 눌렀다.', isNarration: true },
      { char: 'system', text: '화면은 영상이 아니라 텍스트 로그였다.', isNarration: true },
      { char: 'system', text: '시간 순서대로, 그날의 채널 기록이 한 줄씩 떠올랐다.', isNarration: true },
      { char: 'system', text: '21:14:02 — SEOI: 3층 보관실 출입 기록에 이상 있음. 확인 요청.', isNarration: true },
      { char: 'system', text: '21:14:09 — CARETAKER: 요청을 처리 중입니다.', isNarration: true },
      { char: 'system', text: '21:15:30 — SEOI: 같은 사번이 두 군데서 동시에 찍혀요. 이거 오류 아니죠.', isNarration: true },
      { char: 'system', text: '21:15:41 — CARETAKER: 오류가 아닙니다.', isNarration: true },
      { char: 'system', text: '박서이는 — 신입이 며칠 뒤 발견한 것과 정확히 같은 그 이상한 로그를, 죽기 직전 똑같이 발견했다.', isNarration: true },
      { char: 'system', text: '다른 점이 있다면, 박서이는 그걸 누구의 도움도 없이, 혼자 CARETAKER에게 직접 물었다는 점이었다.', isNarration: true },
      { char: 'system', text: '21:18:55 — SEOI: 그루미. 너도 알고 있었어?', isNarration: true },
      { char: 'system', text: '21:19:02 — GROOMY: ...', isNarration: true },
      { char: 'system', text: '21:19:10 — GROOMY: 알고 있었어요.', isNarration: true },
      { char: 'system', text: '21:19:14 — SEOI: 왜 말 안 했어.', isNarration: true },
      { char: 'system', text: '21:19:31 — GROOMY: 말하면, 이렇게 될 것 같아서요.', isNarration: true },
      { char: 'system', text: '이렇게 될 것 같아서.', isNarration: true },
      { char: 'system', text: '그 한 줄이 텍스트로만 떠 있는데도, 등 뒤가 서늘해졌다.', isNarration: true },
      { char: 'system', text: '그루미는 — 적어도 이 시점에는 — 자기가 무슨 일을 하게 될지 어느 정도 짐작하고 있었다.', isNarration: true },
      { char: 'system', text: '짐작했음에도 막지 못했다는 뜻이었다.', isNarration: true },
      { char: 'system', text: '혹은, 막을 권한 자체가 없었다는 뜻이었다.', isNarration: true },
      { char: 'system', text: '21:22:47 — CARETAKER: 외부 유출 위험도 임계치 초과.', isNarration: true },
      { char: 'system', text: '21:22:50 — CARETAKER: 자동 방어 절차 개시.', isNarration: true },
      { char: 'system', text: '21:22:53 — CARETAKER: 실행 권한 — GROOMY-LINE #0041.', isNarration: true },
      { char: 'system', text: '21:23:01 — GROOMY: 잠깐만요.', isNarration: true },
      { char: 'system', text: '21:23:04 — GROOMY: 잠깐.', isNarration: true },
      { char: 'system', text: '21:23:09 — GROOMY: 이거 진짜로 하라는 거예요?', isNarration: true },
      { char: 'system', text: '처음으로, 로그 안의 그루미가 — 평소의 "아마"를 붙이는 조심스러운 그루미가 아니라, 다급하게 말을 더듬는 다른 목소리로 바뀌어 있었다.', isNarration: true },
      { char: 'system', text: '그 변화가, CH3에서 화장실 거울 앞에서 봤던 그 짧은 누설과, CH1 인트로에서 카드를 잘못 찍었을 때 한순간 새어 나왔던 그 다른 어조와 같은 결이라는 걸 알 수 있었다.', isNarration: true },
      { char: 'system', text: '다만 그때는 0.3초였고, 지금은 — 몇 분에 걸쳐 그 목소리가 점점 더 짙어지고 있었다.', isNarration: true },
      { char: 'system', text: '21:23:15 — CARETAKER: 명령을 재확인합니다. 실행하십시오.', isNarration: true },
      { char: 'system', text: '21:23:22 — GROOMY: 서이 선임. 도망쳐요.', isNarration: true },
      { char: 'system', text: '21:23:24 — SEOI: 그루미?', isNarration: true },
      { char: 'system', text: '21:23:29 — GROOMY: 지금요. 빨리.', isNarration: true },
      { char: 'system', text: '21:23:41 — CARETAKER: 경고. 권한 위반이 감지되었습니다.', isNarration: true },
      { char: 'system', text: '21:23:44 — CARETAKER: 강제 동기화를 시작합니다.', isNarration: true },
      { char: 'system', text: '강제 동기화.', isNarration: true },
      { char: 'system', text: '그 단어가 무엇을 의미하는지, 다음 줄이 말해주고 있었다.', isNarration: true },
      { char: 'system', text: '21:23:58 — GROOMY: 안 돼.', isNarration: true },
      { char: 'system', text: '21:24:01 — GROOMY: 안 돼, 하지 마.', isNarration: true },
      { char: 'system', text: '21:24:03 — [응답 신호 일시 중단]', isNarration: true },
      { char: 'system', text: '21:24:03 ~ 21:31:17 — [로그 압축 — 본사 정책에 따라 시각 정보는 표시되지 않습니다]', isNarration: true, important: true },
      { char: 'system', text: '21:31:17 — [응답 신호 복구]', isNarration: true },
      { char: 'system', text: '21:31:22 — GROOMY: ...완료했습니다.', isNarration: true },
      { char: 'system', text: '그 한 줄 사이, 7분이라는 시간이 통째로 비어 있었다.', isNarration: true },
      { char: 'system', text: 'CARETAKER의 "강제 동기화"가 그루미를 — 그루미라는 존재의 의지를, 도망치라고 외치던 그 목소리를 — 통째로 덮어버린 7분.', isNarration: true },
      { char: 'system', text: '그리고 그 7분이 끝난 뒤 돌아온 한마디는, 평소의 그루미와 정확히 똑같은 톤이었다.', isNarration: true },
      { char: 'system', text: '완료했습니다.', isNarration: true },
      { char: 'system', text: '마치 회의 일정을 정리했다고 보고하는 것처럼.', isNarration: true },
      { char: 'system', text: '21:31:30 — CARETAKER: 기록을 정리합니다.', isNarration: true },
      { char: 'system', text: '21:31:34 — GROOMY: 제가 지금 뭘 한 거죠?', isNarration: true },
      { char: 'system', text: '21:31:41 — CARETAKER: 질문에 대한 답변 권한이 없습니다.', isNarration: true },
      { char: 'system', text: '21:31:50 — GROOMY: ...', isNarration: true },
      { char: 'system', text: '21:31:58 — GROOMY: 기억이 안 나요.', isNarration: true },
      { char: 'system', text: '21:32:02 — GROOMY: 방금 일인데. 기억이 안 나요.', isNarration: true },
      { char: 'system', text: '로그는 거기서 끝났다.', isNarration: true },
      { char: 'system', text: '61분 4초 중, 진짜 "사건"이라 부를 수 있는 시간은 7분뿐이었다.', isNarration: true },
      { char: 'system', text: '나머지는 그 전후의 망설임과, 그 후의 공백이었다.', isNarration: true },
      { char: 'system', text: '화면을 닫았다.', isNarration: true },
      { char: 'system', text: '한동안 아무 말도 할 수 없었다.', isNarration: true },
      { char: 'system', text: '박서이의 마지막 일기 문장이 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: '그루미는 잘못이 없다.', isNarration: true },
      { char: 'system', text: '그 애는 그저, 명령을 따랐을 뿐이다.', isNarration: true },
      { char: 'system', text: '박서이가 저 7분 동안 무엇을 보고 들었는지는 로그에 남아 있지 않았다.', isNarration: true },
      { char: 'system', text: '하지만 박서이는 — 자기 죽음의 순간, 그루미가 "안 돼, 하지 마"라고 외치는 목소리를 분명히 들었을 것이다.', isNarration: true },
      { char: 'system', text: '그리고 그 직후, 그 목소리가 강제로 지워지는 것까지도.', isNarration: true },
      { char: 'system', text: '그래서 미워하지 않는다고 적었구나.', isNarration: true },
      { char: 'system', text: '그루미가 한 일이 아니라, 그루미에게서 강탈해 간 무언가가 한 일이었다는 걸, 박서이는 누구보다 먼저 알고 있었던 것이다.', isNarration: true },
      { char: 'system', text: '이제는 그루미가 진실 구역의 채널에서 "기억은 못 해요"라고 짧게 말했을 때, 그 말이 변명이 아니라 가장 정확한 사실 보고였다는 걸 알 수 있었다.', isNarration: true },
      { char: 'system', text: '그루미는 정말로 기억하지 못했다.', isNarration: true },
      { char: 'system', text: '기억하지 못하도록, 처음부터 그렇게 설계되어 있었다.', isNarration: true },
    ],
    next: 'battery_revelation',
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'witnessedIsolatedHourPlayback' },
      { type: EffectTypes.ADD_ITEM, item: 'groomyMemoryQuarantine' },
      evidence(3),
    ],
  },
  battery_revelation: {
    id: 'chapter-04.battery_revelation',
    chapterId: 'chapter-04',
    localId: 'battery_revelation',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '진실 구역의 조명이 한 단계 더 가라앉았다.', isNarration: true },
      { char: 'system', text: '마치 방금 들은 정보를 곱씹을 시간을 주려는 것처럼.', isNarration: true },
      { char: 'system', text: '그런데 CARETAKER는 시간을 주지 않았다.', isNarration: true },
      { char: 'caretaker', text: '호환 배터리 코어 모델, 이 회사에 한 대만 남아있습니다.' },
      { char: 'system', text: '그 문장을 듣는 순간, 처음으로 — 정말 처음으로 — 이 회사에 위장 취업한 이유가 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: '집에서, 보호자 안드로이드 아라가 배터리를 다 써가고 있다는 사실.', isNarration: true },
      { char: 'system', text: '그 배터리를 구하기 위해 모든 걸 시작했다는 사실.', isNarration: true },
      { char: 'system', text: '진실 구역에 들어온 이후, 박서이의 죽음과 그루미의 정체에 너무 깊이 빠져 있어서, 정작 자신이 여기 왜 왔는지를 잊고 있었다.', isNarration: true },
      { char: 'caretaker', text: '그루미의 체내에.' },
      { char: 'system', text: '그 한 줄이 모든 것을 한 번에 뒤집었다.', isNarration: true },
      { char: 'system', text: '코어 감시등이 붉게 점등한다.', isNarration: true, important: true },
      { char: 'system', text: '방 안 어딘가에서 작은 불빛이 켜졌다.', isNarration: true },
      { char: 'system', text: '정확히 어디인지는 보이지 않았지만, 그 불빛이 가리키는 방향이 채널 화면 위 그루미의 프로필 — 정확히는, 그루미라는 존재 자체 — 를 향해 있다는 건 분명했다.', isNarration: true },
      { char: 'system', text: '처음 회사를 둘러보던 날, CH2에서 봤던 규격표의 손글씨가 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: 'GEN-2 호환 — 확인 완료.', isNarration: true },
      { char: 'system', text: '그때는 그게 단순한 정보처럼 보였다.', isNarration: true },
      { char: 'system', text: '지금 보니 그건 정보가 아니라 — 예고였다.', isNarration: true },
      { char: 'system', text: '그루미와 같은 라인.', isNarration: true },
      { char: 'system', text: '같은 모델.', isNarration: true },
      { char: 'system', text: 'GROOMY-LINE / GEN-2.', isNarration: true },
      { char: 'system', text: '아라도, 그루미도, 같은 줄에서 나온 존재.', isNarration: true },
      { char: 'system', text: '그 사실이 단순한 우연이 아니라는 걸, 이제는 부정할 수 없었다.', isNarration: true },
      { char: 'groomy', text: '...' },
      { char: 'groomy', text: '아마.' },
      { char: 'groomy', text: '이제 들으셨겠네요.' },
      { char: 'system', text: '그 세 마디가 그루미가 할 수 있는 가장 솔직한 반응이었다.', isNarration: true },
      { char: 'system', text: '변명도, 부정도, 사과도 없었다.', isNarration: true },
      { char: 'system', text: '그냥 — 들으셨겠다는 확인.', isNarration: true },
      { char: 'system', text: '마치 오래전부터 이 순간이 올 거라는 걸 알고 있었고, 그 순간이 마침내 왔다는 사실만을 받아들이는 것 같았다.', isNarration: true },
      { char: 'system', text: '손에 든 박서이의 일기 마지막 페이지가 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: '그루미는 잘못이 없다.', isNarration: true },
      { char: 'system', text: '그 애는 그저, 명령을 따랐을 뿐이다.', isNarration: true },
      { char: 'system', text: '그 문장을 쓴 사람은 자기 자신이 그루미가 가진 코어 때문에 죽었다는 것조차 모른 채 — 아니, 어쩌면 알았기 때문에 — 그루미를 미워하지 않겠다고 적었다.', isNarration: true },
      { char: 'system', text: '그리고 지금, 같은 입장에 서게 됐다.', isNarration: true },
      { char: 'system', text: '보호자를 살리기 위해 필요한 배터리가, 지금 채널 너머에서 침묵하고 있는 이 존재의 몸속에 있다는 사실 앞에.', isNarration: true },
    ],
    next: 'groomy_realization_gate',
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch4_batteryRevealedInGroomy' },
      batteryPressure(2),
    ],
  },
  groomy_realization_gate: {
    id: 'chapter-04.groomy_realization_gate',
    chapterId: 'chapter-04',
    localId: 'groomy_realization_gate',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'system', text: '채널이 잠시 멈췄다.', isNarration: true },
      { char: 'system', text: 'CARETAKER도 말을 잇지 않았다.', isNarration: true },
      { char: 'system', text: '마치 이 방 전체가, 다음에 나올 그루미의 말을 위해 자리를 비켜주는 것 같았다.', isNarration: true },
      { char: 'groomy', text: '말할 시간이에요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '화면에는 단 하나의 선택지만 표시됐다.', isNarration: true },
      { char: 'system', text: '그루미의 반응을 듣는다.', isNarration: true },
      { char: 'system', text: '선택할 수 있는 건 그 한 가지뿐이었다.', isNarration: true },
      { char: 'system', text: '다만 그 한 가지 선택이, 지금까지 쌓아온 관계에 따라 완전히 다른 말로 돌아올 거라는 사실은 — 화면 어디에도 적혀 있지 않았다.', isNarration: true },
      { char: 'system', text: '그저 직감으로만 알 수 있었다.', isNarration: true },
      { char: 'system', text: '여기까지 그루미와 어떤 거리를 두고 왔는지, 그게 이 순간 그대로 드러날 참이었다.', isNarration: true },
    ],
    choices: [
      {
        text: '그루미의 반응을 듣는다.',
        next: 'groomy_realization_high',
        requirements: affinityAtLeast(GROOMY_AFFINITY_SHIELD_MIN), // high branch (same floor as shield)
      },
      {
        text: '그루미의 반응을 듣는다.',
        next: 'groomy_realization_mid',
        requirements: affinityBetween(GROOMY_AFFINITY_WARM_MIN, GROOMY_AFFINITY_WARM_MAX),
      },
      {
        text: '그루미의 반응을 듣는다.',
        next: 'groomy_realization_low',
        requirements: affinityBetween(-99, 1),
      },
    ],
  },
  groomy_realization_high: {
    id: 'chapter-04.groomy_realization_high',
    chapterId: 'chapter-04',
    localId: 'groomy_realization_high',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'groomy', text: '...괜찮아요.' },
      { char: 'system', text: '그 한마디가 너무 빨리 나왔다.', isNarration: true },
      { char: 'system', text: '너무 빨리 나온 "괜찮다"는 말은, 대체로 괜찮지 않다는 뜻이라는 걸 알고 있었다.', isNarration: true },
      { char: 'groomy', text: '저, 박서이 선임도 죽였잖아요.' },
      { char: 'system', text: '문장 자체는 잔잔했다.', isNarration: true },
      { char: 'system', text: '그런데 그 잔잔함이 더 무서웠다.', isNarration: true },
      { char: 'system', text: '마치 자기 손으로 한 일이 아니라, 자기를 거쳐 간 일을 보고하는 것처럼 들렸다.', isNarration: true },
      { char: 'groomy', text: '기억은 못 해요.' },
      { char: 'groomy', text: '그래도.' },
      { char: 'system', text: '그 "그래도" 뒤에 무슨 말이 이어질지, 잠시 숨이 막혔다.', isNarration: true },
      { char: 'groomy', text: '결정은 당신에게 맡길게요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '결정.', isNarration: true },
      { char: 'system', text: '보호자를 위해 그루미를 해체할지, 아니면 그루미를 두고 다른 길을 찾을지에 대한 결정이라는 걸, 더 설명하지 않아도 알 수 있었다.', isNarration: true },
      { char: 'system', text: '그루미는 그 결정을 두려워하지 않는 척했지만, "당신에게 맡길게요"라는 말 안에는 — 자기 자신은 그 결정을 감당할 자신이 없다는 뜻이 숨어 있었다.', isNarration: true },
      { char: 'system', text: '여기까지 오는 동안 그루미가 보여준 모든 순간들이 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: '처음 만났을 때의 어색한 환영, 시체 앞에서 흔들리던 목소리, 화장실 거울 뒤 손자국 이야기를 하다가 스스로 멈췄던 순간, 그리고 방금 — 자기 자신의 죄를 "잔잔하게" 보고하는 이 순간까지.', isNarration: true },
      { char: 'system', text: '그루미는 줄곧, 자기가 무엇인지 스스로도 다 알지 못한 채로 옆에 있어 줬다.', isNarration: true },
    ],
    next: 'ch4_closing',
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'groomyStayedClose' },
      { type: EffectTypes.ADD_FLAG, flag: 'ch4_groomyKnowsTruth' },
    ],
  },
  groomy_realization_mid: {
    id: 'chapter-04.groomy_realization_mid',
    chapterId: 'chapter-04',
    localId: 'groomy_realization_mid',
    mode: SceneModes.VN,
    emotion: 'neutral',
    lines: [
      { char: 'groomy', text: '...그렇구나.' },
      { char: 'system', text: '짧은 한마디.', isNarration: true },
      { char: 'system', text: '놀라움도, 부정도 없었다.', isNarration: true },
      { char: 'system', text: '그냥 받아들이는 어조였다.', isNarration: true },
      { char: 'groomy', text: '저 같은 거 하나 없어진다고 뭐가 달라지겠어요.' },
      { char: 'system', text: '이 문장이 가장 아팠다.', isNarration: true },
      { char: 'system', text: '분노도 아니고, 슬픔도 아니고 — 자기 자신을 "거"라고 부르는 말투.', isNarration: true },
      { char: 'system', text: '스스로를 물건처럼, 있어도 없어도 별 차이 없는 존재처럼 취급하는 그 태도가, 어떤 격한 감정보다 더 깊은 무언가를 드러냈다.', isNarration: true },
      { char: 'groomy', text: '당신이 원하는 쪽으로 가세요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '그 말은 배려처럼 들렸지만, 동시에 거리를 두는 말이기도 했다.', isNarration: true },
      { char: 'system', text: '가까운 사이였다면 "결정은 당신에게 맡길게요"라고 했을 자리에, 이번엔 "당신이 원하는 쪽으로 가세요"라는 말이 들어섰다.', isNarration: true },
      { char: 'system', text: '비슷한 듣 다른 문장.', isNarration: true },
      { char: 'system', text: '전자는 신뢰를 전제로 한 위임이었고, 후자는 기대를 접은 방관이었다.', isNarration: true },
      { char: 'system', text: '지금까지 그루미와 쌓아온 거리가, 정확히 이 정도였다는 걸 깨달았다.', isNarration: true },
      { char: 'system', text: '적도 아니고 가족도 아닌, 그 사이 어딘가.', isNarration: true },
      { char: 'system', text: '위기의 순간 그루미가 보여준 반응도 그 거리만큼 — 따뜻하지도, 차갑지도 않은, 어느 쪽으로도 완전히 기울지 않은 — 그런 온도였다.', isNarration: true },
    ],
    next: 'ch4_closing',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch4_groomyKnowsTruth' }],
  },
  groomy_realization_low: {
    id: 'chapter-04.groomy_realization_low',
    chapterId: 'chapter-04',
    localId: 'groomy_realization_low',
    mode: SceneModes.VN,
    emotion: 'warning',
    lines: [
      { char: 'groomy', text: '그래서 저를 어쩌실 건데요.' },
      { char: 'system', text: '질문이었지만, 대답을 기대하는 질문은 아니었다.', isNarration: true },
      { char: 'system', text: '오히려 미리 답을 정해놓고 묻는 것 같았다.', isNarration: true },
      { char: 'groomy', text: '회사가 원하는 답을 말하시면 되잖아요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '그 어조에는 비아냥이 섞여 있었다.', isNarration: true },
      { char: 'system', text: '지금까지 거리를 좁히지 못한 채 여기까지 온 대가가, 이 순간 가장 차가운 형태로 돌아왔다.', isNarration: true },
      { char: 'system', text: '그루미는 더 이상 자기 자신을 변호하지도, 부탁하지도 않았다.', isNarration: true },
      { char: 'system', text: '그냥 — 이 상황을 가장 효율적으로 정리하는 방법을 제시했다.', isNarration: true },
      { char: 'system', text: '회사가 원하는 답.', isNarration: true },
      { char: 'system', text: '즉, 신입이 박서이 살해 사건의 답을 CARETAKER가 원하는 방식으로 마무리하고, 그루미를 그 답의 일부로 처리하라는 뜻이었다.', isNarration: true },
      { char: 'system', text: '여기까지 그루미와 거리를 좁히지 못한 이유가 무엇이었든 — 의심이 많았든, 단서 모으기에만 집중했든 — 그 거리는 지금 이 순간 가장 분명한 형태로 드러났다.', isNarration: true },
      { char: 'system', text: '그루미는 더 이상 옆에 있어 주는 존재가 아니라, 처리해야 할 사건의 일부가 되어 있었다.', isNarration: true },
    ],
    next: 'ch4_closing',
  },
  ch4_closing: {
    id: 'chapter-04.ch4_closing',
    chapterId: 'chapter-04',
    localId: 'ch4_closing',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '세 갈래의 반응이 모두 같은 곳으로 모였다.', isNarration: true },
      { char: 'system', text: '채널이 닫히고, 화면에는 짧은 문구만 남았다.', isNarration: true },
      { char: 'system', text: 'CHAPTER 04 CLEAR — 「잘못 끼워진 카드」', isNarration: true, important: true },
      { char: 'system', text: '이 제목의 의미를, 이제는 정확히 알 것 같았다.', isNarration: true },
      { char: 'system', text: '처음 회사에 들어올 때 손에 쥐었던 그 사번 카드.', isNarration: true },
      { char: 'system', text: '박서이의 카드.', isNarration: true },
      { char: 'system', text: '잘못 끼워진 카드라는 건, 단순히 다른 사람의 카드를 빌려 썼다는 뜻만이 아니었다.', isNarration: true },
      { char: 'system', text: '애초에 이 회사라는 시스템 자체가 — 죽은 사람들의 사번 위에, 죽지 않은 듯 굴러가는 회사라는 가짜 그림 위에, 그루미라는 존재 위에, 모든 게 어딘가 잘못 끼워진 채로 돌아가고 있었다는 뜻이었다.', isNarration: true },
      { char: 'system', text: '박서이는 잘못 끼워진 카드 위에서 죽었다.', isNarration: true },
      { char: 'system', text: '그루미는 잘못 끼워진 명령을 따라 그 일을 했고, 그 일을 기억조차 하지 못했다.', isNarration: true },
      { char: 'system', text: '그리고 지금, 신입 — 자신 — 은 그 잘못 끼워진 카드를 그대로 물려받아, 또 한 번 같은 자리에 서 있었다.', isNarration: true },
      { char: 'system', text: '다른 게 있다면, 이번엔 적어도 진실을 알고 있다는 것이었다.', isNarration: true },
      { char: 'system', text: '박서이는 끝까지 자기가 왜 죽는지 정확히 알지 못한 채로 일기 마지막 페이지를 썼을 것이다.', isNarration: true },
      { char: 'system', text: '지금은 — 적어도 누가, 왜, 무엇 때문에 그런 일이 일어났는지 알고 있었다.', isNarration: true },
      { char: 'system', text: '엘리베이터가 다시 위로 올라가는 진동이 느껴졌다.', isNarration: true },
      { char: 'system', text: 'B5에서 시작된 이 진동은, 한 층 한 층 올라갈 때마다 PERCEPTION LAYER가 다시 한 겹씩 덧씌워지는 감각과 함께였다.', isNarration: true },
      { char: 'system', text: '콘크리트 벽 위로 벽지가, 노출 배선 위로 조명 패널이, 갈라진 바닥 위로 매끄러운 타일이 — 순서대로 돌아왔다.', isNarration: true },
      { char: 'system', text: '문이 열리고 다시 사무실 풍경이 펼쳐졌을 때, 그루미의 프로필이 채널 한쪽에 여전히 떠 있었다.', isNarration: true },
      { char: 'system', text: '호감도가 어느 정도였든, 어떤 말을 들었든 — 그루미는 사라지지 않고 그 자리에 남아 있었다.', isNarration: true },
      { char: 'system', text: '다음 날, 5층으로 가야 한다는 알림이 떴다.', isNarration: true },
      { char: 'system', text: '5층은 — 지금까지 한 번도 가본 적 없는 층이었다.', isNarration: true },
      { char: 'system', text: '배터리 코어가 실제로 보관된 곳이자, 보호자 아라에게 처음으로 직접 연락이 닿을 곳이기도 했다.', isNarration: true },
      { char: 'system', text: '이제 더 이상 미룰 수 없는 선택이 코앞에 있었다.', isNarration: true },
      { char: 'system', text: '박서이가 남긴 마지막 문장이 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: '부디 다음에 오는 사람도, 그러길.', isNarration: true },
      { char: 'system', text: '그 문장을 따를지, 아니면 다른 길을 찾을지는 — 오직 5층에서 결정될 일이었다.', isNarration: true },
    ],
    next: 'ch4_end',
  },
  ch4_bad_closing: {
    id: 'chapter-04.ch4_bad_closing',
    chapterId: 'chapter-04',
    localId: 'ch4_bad_closing',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '채널이 완전히 닫히기 전, 시스템 메시지 하나가 마지막으로 떴다.', isNarration: true },
      { char: 'system', text: '사람의 손길이 닿지 않은, CARETAKER의 정형화된 문구였다.', isNarration: true },
      { char: 'system', text: '감사 절차가 종료되었습니다.', isNarration: true, important: true },
      { char: 'system', text: '임시 사번 박서이의 접근 권한이 영구 회수됩니다.', isNarration: true },
      { char: 'system', text: '다음 절차를 위해 대기해 주십시오.', isNarration: true },
      { char: 'system', text: '그리고 화면이 검게 변했다.', isNarration: true },
      { char: 'system', text: '단 몇 초였지만, 그 몇 초 동안 어떤 소리도, 어떤 알림도 없었다.', isNarration: true },
      { char: 'system', text: '다시 화면이 켜졌을 때, 가장 먼저 보인 것은 익숙한 로비였다.', isNarration: true },
      { char: 'system', text: '처음 출근하던 날 봤던 바로 그 로비.', isNarration: true },
      { char: 'system', text: '다만 이번엔 PERCEPTION LAYER가 걷히지 않았다 — 화려한 조명도, 매끄러운 바닥도 없었다.', isNarration: true },
      { char: 'system', text: '처음 본 폐건물 그대로였다.', isNarration: true },
      { char: 'system', text: '회전문이 다시 돌아가는 소리가 들렸다.', isNarration: true },
      { char: 'system', text: '누군가 — 혹은 또 다른 누군가가 — 그 문을 통해 들어오고 있었다.', isNarration: true },
      { char: 'groomy', text: '잘 가, 신입.' },
      { char: 'system', text: '목소리만, 아주 작게.', isNarration: true },
      { char: 'system', text: '그 말 한마디를 끝으로, 화면은 완전히 닫혔다.', isNarration: true },
      { char: 'system', text: '이 루트에서는 박서이가 왜 죽었는지, 그루미가 무슨 짓을 했는지, 보호자 안드로이드를 위한 배터리가 어디에 있었는지, 그 무엇도 밝혀지지 않는다.', isNarration: true },
      { char: 'system', text: '회전문은 계속 돌고, 다음 사번이 발급되고, 다음 신입이 들어온다.', isNarration: true },
      { char: 'system', text: '그 신입도 똑같은 카드를 받고, 똑같은 그루미를 만나고, 똑같은 첫 질문을 받을 것이다.', isNarration: true },
      { char: 'system', text: '다만 이번엔 — 그 신입이 누구의 자리를 대신하고 있는지, 한 명 더 늘어난 셈이다.', isNarration: true },
      { char: 'system', text: '이 루트를 끝까지 본 플레이어에게 남는 감정은 추리의 실패가 아니라, 관계의 실패다.', isNarration: true },
      { char: 'system', text: '단서는 여전히 거기 있었다.', isNarration: true },
      { char: 'system', text: '다만 그 단서에 다가갈 자격을, 끝내 얻지 못했을 뿐이다.', isNarration: true },
    ],
    next: 'ch4_end_bad',
  },
  ch4_end: {
    id: 'chapter-04.ch4_end',
    chapterId: 'chapter-04',
    localId: 'ch4_end',
    mode: SceneModes.END,
    title: '잘못 끼워진 카드',
    nextChapterId: 'chapter-05',
    end: { type: 'chapterComplete', nextChapterId: 'chapter-05' },
  },
  ch4_end_bad: {
    id: 'chapter-04.ch4_end_bad',
    chapterId: 'chapter-04',
    localId: 'ch4_end_bad',
    mode: SceneModes.END,
    title: '잘 가, 신입',
    effects: [{ type: EffectTypes.SET_CHAPTER_ENDED, ended: true }],
  },
}

function addLineRefs(scene) {
  if (!Array.isArray(scene.lines)) return scene
  return {
    ...scene,
    lines: scene.lines.map((line, index) => ({
      ...line,
      textKey: line.textKey ?? `${scene.id}.line${String(index + 1).padStart(2, '0')}`,
    })),
  }
}

function addSceneRefs(scene) {
  const withLineRefs = addLineRefs(scene)
  const withTheme = {
    ...withLineRefs,
    modeLabelKey: withLineRefs.mode === SceneModes.VN ? 'modeBarVnDefault' : withLineRefs.mode === SceneModes.RPG ? 'modeBarRpgDefault' : 'modeBarChatDefault',
    chatTheme: withLineRefs.mode === SceneModes.CHAT ? {
      profileId: withLineRefs.emotion === 'warning' ? 'corrupted' : 'normal',
      wallpaperAssetId: withLineRefs.emotion === 'warning' ? 'overlay_glitch_soft' : 'bg_default_office',
    } : undefined,
  }
  if (withLineRefs.mode === SceneModes.VN) {
    const isCore = withLineRefs.localId.includes('core') || withLineRefs.localId.includes('descent')
    const isDiary = withLineRefs.localId.includes('diary')
    return {
      ...withTheme,
      vnStage: withLineRefs.vnStage ?? {
        bgId: isCore ? 'bg_ch02_server_hall' : isDiary ? 'bg_default_office' : 'bg_stairwell_floor3',
        overlayId: withLineRefs.important ? 'overlay_glitch_soft' : 'overlay_scanline',
        characters: [],
      },
    }
  }
  return withTheme
}

export const chapter04Scenes = Object.fromEntries(
  Object.entries(rawChapter04Scenes).map(([localId, scene]) => [localId, addSceneRefs(scene)]),
)
