import { EffectTypes, SceneModes } from '../../../engine/contracts.js'
import {
  GROOMY_AFFINITY_SHIELD_MIN,
  GROOMY_AFFINITY_WARM_MAX,
  GROOMY_AFFINITY_WARM_MIN,
} from '../../story/groomyAffinityThresholds.js'
import { GUARDIAN_NAME, PERCEPTION_LAYER } from '../../world/company.js'

const batteryPressure = (amount = 1) => ({ type: EffectTypes.ADD_SCORE, score: 'batteryDesperation', amount })

const affinityAtLeast = (min) => [{ type: 'score', score: 'groomyAffinity', min }]
const affinityBetween = (min, max) => [{ type: 'score', score: 'groomyAffinity', min, max }]

const rawChapter05Scenes = {
  perception_off: {
    id: 'chapter-05.perception_off',
    chapterId: 'chapter-05',
    localId: 'perception_off',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '5층 문이 열렸을 때, 가장 먼저 느낀 건 소리의 부재였다.', isNarration: true },
      { char: 'system', text: '지금까지의 모든 층은 — 화려하든 차갑든 — 적어도 무언가 돌아가는 소리가 있었다.', isNarration: true },
      { char: 'system', text: '팬 소리, 알림음, 멀리서 들리는 발소리.', isNarration: true },
      { char: 'system', text: '5층은 처음부터 그 모든 게 빠져 있었다.', isNarration: true },
      { char: 'system', text: '마치 이 층만큼은, 누군가 일부러 소리를 다 꺼두고 기다리고 있었던 것처럼.', isNarration: true },
      { char: 'system', text: '손에는 여전히 박서이의 일기 마지막 페이지가, 그리고 그루미의 체내에 호환 배터리 코어가 있다는 사실이 함께 들려 있었다.', isNarration: true },
      { char: 'system', text: '둘 다 무게가 있는 정보였다.', isNarration: true },
      { char: 'system', text: '한쪽은 죽은 사람의 마지막 마음이었고, 다른 한쪽은 살아있는 — 정확히는, 살아있다고 불러도 되는지 의문이 드는 — 존재의 몸 안에 있는 답이었다.', isNarration: true },
      { char: 'system', text: 'CHAPTER 05 시작 — 「마지막 카드」', isNarration: true, important: true },
      { char: 'system', text: '마지막이라는 단어가, 이번엔 다른 의미로 들렸다.', isNarration: true },
      { char: 'system', text: '지금까지의 "마지막"은 대체로 위기의 마지막, 혹은 하루의 마지막이었다.', isNarration: true },
      { char: 'system', text: '이번 마지막은 — 선택의 마지막이라는 뜻 같았다.', isNarration: true },
      { char: 'system', text: `${PERCEPTION_LAYER.OFF} · 동기화 해제`, isNarration: true, important: true },
      { char: 'system', text: '알림이 뜨는 순간, 발밑에서부터 뭔가가 변하기 시작했다.', isNarration: true },
      { char: 'system', text: '화려한 조명이 한 겹씩 꺼진다.', isNarration: true },
      { char: 'system', text: '천장의 매끄러운 패널이 사라지고, 그 위로 노출된 배선과 깜빡이는 비상등이 드러난다.', isNarration: true },
      { char: 'system', text: '곰팡이 냄새가 다시 올라온다.', isNarration: true },
      { char: 'system', text: '처음 이 회사에 발을 들였던 그날, 카드를 잘못 찍기 전 마주했던 바로 그 냄새였다.', isNarration: true },
      { char: 'system', text: '금 간 타일, 무너진 천장, 낡은 복도.', isNarration: true, important: true },
      { char: 'system', text: '한 걸음씩 옮길 때마다, 발밑에서 들리는 소리도 달라졌다.', isNarration: true },
      { char: 'system', text: '매끄러운 타일 위를 걷는 또각거림이 아니라, 갈라진 시멘트 위를 밟는 둔탁한 소리.', isNarration: true },
      { char: 'system', text: 'GROOMY OFFICE는 사라지고 폐건물만 남는다.', isNarration: true, important: true },
      { char: 'system', text: '이상하게도, 무섭지 않았다.', isNarration: true },
      { char: 'system', text: '처음 이 광경을 봤을 때는 — 사원증을 찍기 전, 잠깐 스쳐 지나갔던 그 폐건물의 모습 — 등골이 서늘했다.', isNarration: true },
      { char: 'system', text: '그런데 지금은, 오히려 이게 더 솔직한 모습처럼 느껴졌다.', isNarration: true },
      { char: 'system', text: '화려한 회사는 가짜였고, 이 낡고 부서진 건물이 진짜였다.', isNarration: true },
      { char: 'system', text: '그 사실을 받아들이고 나니, 더 이상 두려워할 이유가 없었다.', isNarration: true },
    ],
    next: 'office_truth',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch5_perceptionLayerOff' }],
  },
  office_truth: {
    id: 'chapter-05.office_truth',
    chapterId: 'chapter-05',
    localId: 'office_truth',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '복도를 따라 걷다, 익숙한 자리들을 지나쳤다.', isNarration: true },
      { char: 'system', text: '강이솔 선임 자리.', isNarration: true },
      { char: 'system', text: '처음엔 강이솔이 실제로 거기 앉아 있는 줄 알고 멈춰 섰다.', isNarration: true },
      { char: 'system', text: '가까이 다가가서야, 그게 사람이 아니라는 걸 알았다.', isNarration: true },
      { char: 'system', text: '정확히는 — 사람이었던 적이 있는 자리에, 시간만 그대로 멈춰 있다는 걸 알았다.', isNarration: true },
      { char: 'system', text: '의자에 앉은 채 오래 멈춰 있다.', isNarration: true, important: true },
      { char: 'system', text: '의자는 비어 있지 않았지만, 그 위에 앉아 있는 건 더 이상 누구도 아니었다.', isNarration: true },
      { char: 'system', text: '책상 위에 접힌 쪽지가 하나 놓여 있다.', isNarration: true },
      { char: 'system', text: '누군가 남긴 메모처럼 보이지만, 받을 사람은 이미 없다.', isNarration: true },
      { char: 'system', text: '최민준 팀장 자리도 같다.', isNarration: true },
      { char: 'system', text: '이름은 처음 듣는 이름이었지만, 자료보관실에서 봤던 인사 기록 어딘가에 분명 스쳐 지나갔을 이름이었다.', isNarration: true },
      { char: 'system', text: '책상 위 캘린더가 그대로 놓여 있다.', isNarration: true },
      { char: 'system', text: '종이는 누렇게 변색되어 있었고, 한 귀퉁이가 접혀 있었다.', isNarration: true },
      { char: 'system', text: 'PERCEPTION LAYER가 꺼진 지금은, 그 위 먼지가 그대로 보인다.', isNarration: true },
      { char: 'system', text: '출근부 마지막 날짜는 2019년이다.', isNarration: true, important: true },
      { char: 'system', text: '2019년.', isNarration: true },
      { char: 'system', text: '박서이의 사망 시점보다도 한참 전이었다.', isNarration: true },
      { char: 'system', text: '그렇다면 최민준이라는 사람은 — 박서이보다 먼저, 이 자리에서 시간이 멈춘 또 다른 사람이라는 뜻이었다.', isNarration: true },
      { char: 'system', text: 'CH4의 자료보관실에서 봤던 그 두 개의 추가 로그, 2022년과 2024년의 흐릿한 실행 기록이 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: '박서이는 처음이 아니었다.', isNarration: true },
      { char: 'system', text: '어쩌면 최민준이 그 둘 중 하나였을지도, 아니면 그보다 더 이전의, 또 다른 누군가였을지도 몰랐다.', isNarration: true },
      { char: 'system', text: '말하는 사람은 없고, 기록만 남아 있다.', isNarration: true },
      { char: 'system', text: '복도를 걸으며, 비어 있는 책상들을 하나씩 지나쳤다.', isNarration: true },
      { char: 'system', text: '다들 누군가의 자리였을 책상들.', isNarration: true },
      { char: 'system', text: '머그컵이 그대로 놓여 있는 자리, 사진 액자가 엎어진 채로 있는 자리, 메모지가 빈 칸 없이 빽빽하게 붙어 있다가 색이 다 바랜 자리.', isNarration: true },
      { char: 'system', text: '회사라는 이름으로 불리던 이 공간은 사실, 처음부터 끝까지 — 산 사람이 아니라 멈춘 사람들의 흔적으로만 채워져 있었다.', isNarration: true },
    ],
    next: 'ch5_battery_weight',
    effects: [{ type: EffectTypes.ADD_ITEM, item: 'iseolPrivateNote' }],
  },
  ch5_battery_weight: {
    id: 'chapter-05.ch5_battery_weight',
    chapterId: 'chapter-05',
    localId: 'ch5_battery_weight',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '고요한 사무실에는 기계음만 남는다.', isNarration: true },
      { char: 'system', text: '복도 끝에서 걸음을 멈췄다.', isNarration: true },
      { char: 'system', text: '정확히 무엇 때문에 멈췄는지는 스스로도 알 수 없었다.', isNarration: true },
      { char: 'system', text: '다만 어떤 소리가 — 아주 낮고, 아주 일정한 진동이 — 가까운 곳에서 들렸다.', isNarration: true },
      { char: 'system', text: '그루미 가슴 쪽에서 낮은 진동이 들린다. 초침보다 느리고, 심장보다 차갑다.', isNarration: true, important: true },
      { char: 'system', text: '처음으로, 그루미의 몸 안에서 나는 소리를 의식하며 들었다.', isNarration: true },
      { char: 'system', text: '그동안 그루미는 그냥 "그루미"였다.', isNarration: true },
      { char: 'system', text: '목소리였고, 대화 상대였고, 가끔은 친구 같기도 했던 존재.', isNarration: true },
      { char: 'system', text: '그 안에 기계 부품이 들어있다는 사실을, 머리로는 알았지만 마음으로 느낀 적은 없었다.', isNarration: true },
      { char: 'system', text: '시선이 배터리 슬롯으로 간다. 이미 알고 있는 자리다.', isNarration: true },
      { char: 'system', text: 'CH4의 진실 구역에서 코어 감시등이 붉게 점등했던 그 위치.', isNarration: true },
      { char: 'system', text: '옷 위로는 아무것도 보이지 않았지만, 이제는 정확히 어디인지 알았다.', isNarration: true },
      { char: 'system', text: '그루미의 가슴 한가운데, 사람으로 치면 심장이 있을 자리.', isNarration: true },
      { char: 'system', text: '새 정보는 없다. 무게만 남는다.', isNarration: true, important: true },
      { char: 'system', text: '알아야 할 건 이미 다 알고 있었다.', isNarration: true },
      { char: 'system', text: '누구를 살리기 위해 무엇을 잃어야 하는지도, 그 무게가 얼마나 되는지도.', isNarration: true },
      { char: 'system', text: '다만 그 무게를 실제로 손에 들고 서 있는 지금, 머릿속의 정보와 가슴속의 감각이 같지 않다는 걸 처음으로 깨달았다.', isNarration: true },
    ],
    next: 'groomy_only_alive',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch5_feltBatteryWeight' }],
  },
  groomy_only_alive: {
    id: 'chapter-05.groomy_only_alive',
    chapterId: 'chapter-05',
    localId: 'groomy_only_alive',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'system', text: '폐건물 안에서 숨 쉬는 존재는 그루미뿐이다.', isNarration: true, important: true },
      { char: 'system', text: '복도에 멈춰 서서, 한동안 그루미를 바라봤다.', isNarration: true },
      { char: 'system', text: '너무 오래, 너무 가만히 바라봤던 것 같다.', isNarration: true },
      { char: 'system', text: '그루미가 먼저 그 시선을 깨고 들어왔다.', isNarration: true },
      { char: 'groomy', text: '왜 그래요?' },
      { char: 'groomy', text: '갑자기 그렇게 보면 부담스러워요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '그 마지막 "아마"가, 평소와 다르게 들렸다.', isNarration: true },
      { char: 'system', text: '농담을 가볍게 흘리려는 시도였겠지만, 정작 그 시도 자체가 무거운 침묵을 더 도드라지게 만들었다.', isNarration: true },
      { char: 'system', text: '이 폐건물 안에서, 최민준의 빈 책상도, 강이솔의 멈춘 의자도, 그 누구도 더 이상 숨을 쉬지 않았다.', isNarration: true },
      { char: 'system', text: '정확히 말하면 — 애초에 사람이 숨을 쉬는 공간이 아니었다.', isNarration: true },
      { char: 'system', text: '그루미만이, 어떤 의미로든 "살아 있다"고 부를 수 있는 유일한 존재였다.', isNarration: true },
      { char: 'system', text: '그 사실이 묘하게 사무쳤다.', isNarration: true },
      { char: 'system', text: '죽은 사람들의 자리 한가운데, 죽지 않은 단 하나의 존재가 — 사실은 사람이 아니라 안드로이드라는 사실.', isNarration: true },
      { char: 'system', text: '그리고 그 존재의 몸 안에, 또 다른 안드로이드를 살릴 답이 들어 있다는 사실.', isNarration: true },
      { char: 'system', text: '읽으면서 처음으로 분명하게 깨달았다.', isNarration: true },
      { char: 'system', text: '앞으로 내려야 할 결정은 — 아라를 구할지, 그루미를 잃을지를 가르는 단순한 양자택일이 아니었다.', isNarration: true },
      { char: 'system', text: '두 존재 모두, 각자의 방식으로 오래 혼자였다.', isNarration: true, important: true },
      { char: 'system', text: '그 둘 중 하나를 선택해야 하는 게 아니라, 둘 다를 똑같이 무겁게 받아들이는 일이 — 지금부터 시작될 5장의 진짜 시작이었다.', isNarration: true },
    ],
    next: 'guardian_call',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch5_confirmedGroomyAlone' }],
  },
  guardian_call: {
    id: 'chapter-05.guardian_call',
    chapterId: 'chapter-05',
    localId: 'guardian_call',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    systemMessage: 'HOME · GUARDIAN LINK',
    lines: [
      { char: 'system', text: '집으로 향하는 통화 연결이 겨우 잡힌다.', isNarration: true },
      { char: 'system', text: '신호가 잡히는 데 한참이 걸렸다.', isNarration: true },
      { char: 'system', text: 'PERCEPTION LAYER가 꺼진 폐건물 안에서, 외부 통신이 제대로 닿을지조차 확신할 수 없었다.', isNarration: true },
      { char: 'system', text: '몇 번의 끊김 끝에, 마침내 화면에 익숙한 얼굴이 떠올랐다.', isNarration: true },
      { char: 'system', text: `${GUARDIAN_NAME}의 목소리는 먼 곳에서 울린다.`, isNarration: true },
      { char: 'system', text: '화질이 좋지 않았다.', isNarration: true },
      { char: 'system', text: '음성도 한 박자씩 늦게 들렸다.', isNarration: true },
      { char: 'system', text: '그래도 분명히, 아라였다.', isNarration: true },
      { char: 'system', text: '잔여 배터리: 12시간.', isNarration: true, important: true },
      { char: 'system', text: '화면 한쪽에 뜬 그 숫자를 보는 순간, 숨이 잠깐 멈췄다.', isNarration: true },
      { char: 'system', text: '12시간.', isNarration: true },
      { char: 'system', text: '처음 이 회사에 지원했을 때는, 적어도 몇 주의 여유가 있다고 생각했다.', isNarration: true },
      { char: 'system', text: '그 여유가 이렇게 빨리, 이렇게 가깝게 줄어들 거라고는 예상하지 못했다.', isNarration: true },
      { char: 'system', text: '보호자 안드로이드의 마지막 진단 알림이 겹쳐 온다.', isNarration: true },
      { char: 'system', text: '알림 내용까지 자세히 읽을 틈은 없었다.', isNarration: true },
      { char: 'system', text: '그저 화면 한쪽에서 깜빡이는 경고 아이콘만으로도, 더 설명이 필요 없었다.', isNarration: true },
      { char: 'system', text: '12퍼센트에서 12시간까지, 그 사이 며칠이 얼마나 빠르게 지나갔는지 다시 체감했다.', isNarration: true },
      { char: 'system', text: '여기까지 오는 동안 박서이의 죽음과 그루미의 진실에 매달려 있던 시간이, 정작 처음 이 회사에 들어온 이유였던 아라에게는 그대로 소모되는 시간이었다는 사실이 뒤늦게 와닿았다.', isNarration: true },
      { char: 'system', text: '영상 통화를 걸자, 화면 너머로 익숙한 방이 보였다.', isNarration: true },
      { char: 'system', text: '창가 자리, 늘 앉아 있던 그 의자.', isNarration: true },
      { char: 'system', text: '아라는 평소처럼 앉아 있었지만, 화면 밝기 자체가 평소보다 한 톤 낮아 보였다.', isNarration: true },
      { char: 'guardian', text: '어, 거기서 연락 줄 줄은 몰랐어요.' },
      { char: 'player', text: '...일이 좀 복잡해졌어요.' },
      { char: 'player', text: '미안해요, 연락이 늦었어요.' },
      { char: 'guardian', text: '괜찮아요.' },
      { char: 'guardian', text: '저는, 그냥 기다리는 거니까요.' },
      { char: 'player', text: '조금만 더 기다려줘요.' },
      { char: 'player', text: '거의 다 왔어요.' },
      { char: 'guardian', text: '거의, 라는 말.' },
      { char: 'player', text: '...' },
      { char: 'guardian', text: '그 말을 들으니까, 오히려 마음이 편해지네요.' },
      { char: 'guardian', text: '신기하죠.' },
      { char: 'system', text: '그 말 한마디가, 지금까지 들었던 어떤 말보다도 무겁게 가슴에 박혔다.', isNarration: true },
      { char: 'system', text: '그쪽이 돌아올 때까지는.', isNarration: true },
      { char: 'system', text: '아라는 자기 자신의 생존을, 누군가를 기다리는 일과 동일시하고 있었다.', isNarration: true },
      { char: 'system', text: '마치 기다림이 끝나면, 그 후의 일은 더 이상 자기 의지로 정할 수 없다는 듯이.', isNarration: true },
      { char: 'system', text: '아라의 그 말투가, 어쩐지 그루미와 닮아 있었다.', isNarration: true },
      { char: 'system', text: '둘 다 같은 라인에서 나온 존재라는 사실을 알기 전에도 이미, 둘은 비슷한 방식으로 자기 감정을 말했다.', isNarration: true },
      { char: 'system', text: '직접 드러내지 않고, 한 발 물러서서 보고하듯이.', isNarration: true },
      { char: 'system', text: '통화가 끊기기 직전, 그루미가 옆에서 조용히 입을 열었다.', isNarration: true },
      { char: 'groomy', text: '...' },
      { char: 'groomy', text: '서둘러요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '그 한마디에는, 평소의 가벼운 입버릇과는 다른 무언가가 섞여 있었다.', isNarration: true },
      { char: 'system', text: '서둘러야 하는 이유를 그루미 자신도 정확히 알고 있다는 듯.', isNarration: true },
      { char: 'system', text: '그리고 그 "서둘러야 한다"는 말이, 결국 자기 자신을 향한 결정을 서두르라는 뜻이기도 하다는 걸, 그루미는 입 밖에 내지 않은 채로 알고 있는 것 같았다.', isNarration: true },
    ],
    next: 'final_choice_pick',
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch5_calledGuardian' },
      { type: EffectTypes.ADD_ITEM, item: 'guardianBatteryNotice' },
      batteryPressure(2),
    ],
  },
  final_choice_pick: {
    id: 'chapter-05.final_choice_pick',
    chapterId: 'chapter-05',
    localId: 'final_choice_pick',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '그루미가 당신을 바라본다.', isNarration: true },
      { char: 'system', text: '통화가 끝난 뒤, 복도에는 둘만 남았다.', isNarration: true },
      { char: 'system', text: '그루미는 평소처럼 먼저 말을 걸지 않았다.', isNarration: true },
      { char: 'system', text: '그냥, 가만히 바라보고 있었다.', isNarration: true },
      { char: 'system', text: '그 시선이 무엇을 묻고 있는지는 분명했다.', isNarration: true },
      { char: 'system', text: '다만 그 질문에 대한 답이, 지금까지 이 둘 사이에 쌓인 모든 것 — 매 챕터마다 나눈 말, 흘려보낸 침묵, 서로에게 보여준 만큼의 거리 — 에 따라 완전히 다른 방식으로 나올 거라는 사실은, 화면 어디에도 적혀 있지 않았다.', isNarration: true },
      { char: 'system', text: '선택지는 하나처럼 보였다.', isNarration: true },
      { char: 'system', text: '그루미의 말을 듣는다.', isNarration: true },
      { char: 'system', text: '혹은 그루미를 바라본다.', isNarration: true },
      { char: 'system', text: '표현은 다르지만, 결국 같은 행동이었다.', isNarration: true },
      { char: 'system', text: '다만 그 행동의 결과로 돌아올 그루미의 반응은 — 이미 정해져 있었다.', isNarration: true },
      { char: 'system', text: '단 한 번도, 이 순간만을 위해 따로 선택한 적 없는 그 거리감대로.', isNarration: true },
    ],
    choices: [
      {
        text: '그루미의 말을 듣는다.',
        next: 'final_choice_high',
        requirements: affinityAtLeast(GROOMY_AFFINITY_SHIELD_MIN), // high branch (same floor as shield)
      },
      {
        text: '그루미의 말을 듣는다.',
        next: 'final_choice_mid',
        requirements: affinityBetween(GROOMY_AFFINITY_WARM_MIN, GROOMY_AFFINITY_WARM_MAX),
      },
      {
        text: '그루미를 바라본다.',
        next: 'final_choice_low',
        requirements: affinityBetween(-99, 1),
      },
    ],
  },
  final_choice_high: {
    id: 'chapter-05.final_choice_high',
    chapterId: 'chapter-05',
    localId: 'final_choice_high',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '그루미가 입을 열기까지, 평소보다 훨씬 긴 침묵이 있었다.', isNarration: true },
      { char: 'groomy', text: '...' },
      { char: 'groomy', text: '...괜찮아요.' },
      { char: 'groomy', text: '저.' },
      { char: 'groomy', text: '여기 너무 오래 혼자였던 것 같아요.' },
      { char: 'system', text: '이 한마디가, 지금까지 그루미가 한 모든 말 중 가장 솔직한 말처럼 들렸다.', isNarration: true },
      { char: 'system', text: '죽은 사람들의 자리 사이에서, 박서이를 잃은 죄책감과 그 죄책감조차 정확히 기억하지 못하는 혼란을 동시에 끌어안고, 그루미는 줄곧 혼자였다.', isNarration: true },
      { char: 'system', text: '신입이 오기 전에도, 신입이 온 뒤에도 — 곁에 누군가 있다는 게 어떤 의미인지조차 다시 배워야 하는 상태로.', isNarration: true },
      { char: 'groomy', text: '결정해 주세요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '그 "결정해 주세요"라는 말이, 처음 CH4에서 그루미가 보였던 태도와 정확히 같은 자리에서 출발하고 있었다.', isNarration: true },
      { char: 'system', text: '결정은 당신에게 맡길게요.', isNarration: true },
      { char: 'system', text: '그때도, 지금도, 그루미는 자기 자신의 운명을 직접 정하지 않았다.', isNarration: true },
      { char: 'system', text: '다만 이번엔 그 위임 뒤에, "혼자였다"는 말이 먼저 붙어 있었다.', isNarration: true },
      { char: 'system', text: '마치 — 누군가에게 결정을 맡길 수 있다는 사실 자체가, 더 이상 혼자가 아니라는 증거인 것처럼.', isNarration: true },
      { char: 'system', text: '선택지는 두 개였다.', isNarration: true },
    ],
    choices: [
      {
        text: '미안해. 부품을 꺼낼게.',
        next: 'ending_badA',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'dismantledGroomy' },
          { type: EffectTypes.ADD_FLAG, flag: 'dismantledWithFullKnowledge' },
        ],
      },
      {
        text: '안 해. 같이 나가자.',
        next: 'ending_true',
        effects: [{ type: EffectTypes.ADD_FLAG, flag: 'groomyStayedClose' }],
      },
    ],
  },
  final_choice_mid: {
    id: 'chapter-05.final_choice_mid',
    chapterId: 'chapter-05',
    localId: 'final_choice_mid',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    important: true,
    lines: [
      { char: 'system', text: '이번에는, 그루미가 선택지를 묻지 않았다.', isNarration: true },
      { char: 'groomy', text: '...' },
      { char: 'groomy', text: '그쪽 가족.' },
      { char: 'groomy', text: '살려주세요.' },
      { char: 'groomy', text: '제가 대신 내줄게요.' },
      { char: 'groomy', text: '아마.' },
      { char: 'system', text: '그 마지막 "아마"가, 이상하게도 이번엔 더 단단하게 들렸다.', isNarration: true },
      { char: 'system', text: '평소 같으면 망설임의 표시였던 그 말이, 이번엔 — 자기 자신도 이 결정이 맞는지 다 확신하지 못하면서도, 그 불확신을 안고 그냥 결정해버리는 사람의 말투처럼 들렸다.', isNarration: true },
      { char: 'system', text: '이 거리에서는, 그루미가 신입에게 결정을 맡기지 않았다.', isNarration: true },
      { char: 'system', text: '신입이 망설일 틈도 주지 않고, 자기 쪽에서 먼저 답을 내려버렸다.', isNarration: true },
      { char: 'system', text: '가까운 사이였다면 "결정해 주세요"라고 했을 자리에, 이번엔 "제가 대신 내줄게요"라는 말이 들어섰다.', isNarration: true },
      { char: 'system', text: '신뢰해서 맡기는 게 아니라, 신입이 그 무게를 감당하지 않아도 되게 — 먼저 알아서 처리해버리는 방식.', isNarration: true },
    ],
    next: 'ending_normal',
  },
  final_choice_low: {
    id: 'chapter-05.final_choice_low',
    chapterId: 'chapter-05',
    localId: 'final_choice_low',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'system', text: '이 거리에서는, 그루미도 더 이상 말을 길게 하지 않았다.', isNarration: true },
      { char: 'groomy', text: '...' },
      { char: 'system', text: '그 한 글자 — 정확히는 점 세 개 — 가 전부였다.', isNarration: true },
      { char: 'system', text: '변명도, 부탁도, 농담도 없었다.', isNarration: true },
      { char: 'system', text: '그루미는 이미, 이 순간 무슨 일이 일어날지 알고 있는 것 같았다.', isNarration: true },
      { char: 'system', text: '당신은 말 없이 그루미 쪽으로 손을 뻗는다.', isNarration: true, important: true },
      { char: 'system', text: '이 문장이, 본문 전체에서 가장 차가운 문장이었다.', isNarration: true },
      { char: 'system', text: '주체가 "당신"으로 명시되어 있다는 게 의미심장했다.', isNarration: true },
      { char: 'system', text: '다른 분기들에서는 그루미가 먼저 입을 열거나, 적어도 어떤 말로 상황을 정리했다.', isNarration: true },
      { char: 'system', text: '이 분기에서는 — 그루미가 아니라 신입 쪽에서, 아무 말도 없이 먼저 행동했다.', isNarration: true },
      { char: 'system', text: '그동안 쌓인 거리가, 정확히 이 침묵의 형태로 드러났다.', isNarration: true },
      { char: 'system', text: '의심이 많았든, 단서 모으기에만 집중했든, 그루미를 그저 정보를 주는 도구처럼 대했든 — 이유가 무엇이었든, 결과는 같았다.', isNarration: true },
      { char: 'system', text: '마지막 순간, 그루미에게 어떤 말도 건네지 않은 채로 손을 뻗었다.', isNarration: true },
    ],
    next: 'ending_badB',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'dismantledGroomy' }],
  },
  ending_true: {
    id: 'chapter-05.ending_true',
    chapterId: 'chapter-05',
    localId: 'ending_true',
    mode: SceneModes.VN,
    emotion: 'friendly',
    important: true,
    lines: [
      { char: 'system', text: '말이 먼저 나왔다.', isNarration: true },
      { char: 'system', text: '생각보다 빨리.', isNarration: true },
      { char: 'system', text: '둘이 함께 문을 나선다.', isNarration: true },
      { char: 'system', text: '바깥 공기. 비 냄새.', isNarration: true, important: true },
      { char: 'system', text: '5층 문을 나서서, 처음으로 회사 건물 바깥에 발을 디뎠다.', isNarration: true },
      { char: 'system', text: '며칠 동안 갇혀 있던 공간에서 벗어나니, 공기의 냄새부터 달랐다.', isNarration: true },
      { char: 'system', text: '비가 막 그친 듯한 냄새.', isNarration: true },
      { char: 'system', text: '폐건물 안에서는 한 번도 느끼지 못한 냄새였다.', isNarration: true },
      { char: 'groomy', text: '...아라는 어떤 사람이에요?' },
      { char: 'system', text: '질문이 예상 밖이었다.', isNarration: true },
      { char: 'system', text: '방금 막 거절당한 — 정확히는, 자기 자신을 살리는 길을 거절당한 — 존재가 묻는 첫 질문이 그거였다.', isNarration: true },
      { char: 'system', text: '비난도, 안도도 아니고, 그냥 순수한 궁금증.', isNarration: true },
      { char: 'system', text: '대답을 고르며 걷는다.', isNarration: true },
      { char: 'system', text: '길은 생각보다 길고, 침묵은 생각보다 짧다.', isNarration: true },
    ],
    choices: [
      {
        text: `"${GUARDIAN_NAME}는 가족이에요."`,
        next: 'ending_true_family_walk',
        effects: [{ type: EffectTypes.ADD_FLAG, flag: 'groomyStayedClose' }],
      },
      {
        text: '대답하지 않고 걷는다.',
        next: 'ending_true_silent_walk',
        effects: [{ type: EffectTypes.ADD_FLAG, flag: 'groomyStayedClose' }],
      },
    ],
  },
  ending_true_family_walk: {
    id: 'chapter-05.ending_true_family_walk',
    chapterId: 'chapter-05',
    localId: 'ending_true_family_walk',
    mode: SceneModes.VN,
    emotion: 'friendly',
    lines: [
      { char: 'system', text: '가족이라고 부르는 게, 맞는 표현인지는 모르겠어요.', isNarration: true },
      { char: 'system', text: '그냥 — 제가 돌아갈 자리예요.', isNarration: true },
      { char: 'groomy', text: '그렇구나.' },
      { char: 'groomy', text: '이상해요?' },
      { char: 'groomy', text: '아니요. 저도, 누군가한테 그런 자리가 있었으면 좋겠다고 생각했어요.' },
      { char: 'system', text: '둘 중 어느 쪽을 골랐든, 결과는 같았다.', isNarration: true },
      { char: 'system', text: '함께 걷는다는 사실 자체가, 이미 충분한 답이었다.', isNarration: true },
      { char: 'system', text: '이제 남은 문제는, 아라를 위한 다른 배터리를 어디서 찾을지였다.', isNarration: true },
      { char: 'system', text: '답은 없었다.', isNarration: true },
      { char: 'system', text: '다만 그 답을 찾는 과정에, 혼자가 아니라는 사실만큼은 분명해졌다.', isNarration: true },
    ],
    next: 'ch5_closing',
  },
  ending_true_silent_walk: {
    id: 'chapter-05.ending_true_silent_walk',
    chapterId: 'chapter-05',
    localId: 'ending_true_silent_walk',
    mode: SceneModes.VN,
    emotion: 'friendly',
    lines: [
      { char: 'system', text: '질문에 답하는 대신, 그냥 옆에서 걸었다.', isNarration: true },
      { char: 'system', text: '그루미도 더 묻지 않았다.', isNarration: true },
      { char: 'system', text: '가끔은, 말로 답하는 것보다 같이 걷는 게 더 정확한 대답이 될 때가 있었다.', isNarration: true },
      { char: 'system', text: '둘 중 어느 쪽을 골랐든, 결과는 같았다.', isNarration: true },
      { char: 'system', text: '함께 걷는다는 사실 자체가, 이미 충분한 답이었다.', isNarration: true },
      { char: 'system', text: '이제 남은 문제는, 아라를 위한 다른 배터리를 어디서 찾을지였다.', isNarration: true },
      { char: 'system', text: '답은 없었다.', isNarration: true },
      { char: 'system', text: '다만 그 답을 찾는 과정에, 혼자가 아니라는 사실만큼은 분명해졌다.', isNarration: true },
    ],
    next: 'ch5_closing',
  },
  ending_badA: {
    id: 'chapter-05.ending_badA',
    chapterId: 'chapter-05',
    localId: 'ending_badA',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '손이 먼저 움직였다.', isNarration: true },
      { char: 'system', text: '머리로 정리하기도 전에.', isNarration: true },
      { char: 'system', text: '해체 작업이 시작된다.', isNarration: true, important: true },
      { char: 'system', text: '작업은 생각보다 조용했다.', isNarration: true },
      { char: 'system', text: '비명도, 경고음도 없었다.', isNarration: true },
      { char: 'system', text: '그저 손끝의 감각만이 — 평소 만질 때와 다르지 않은 온도, 다르지 않은 질감 — 이게 정말 "해체"라고 불려야 하는 일인지를 의심하게 만들었다.', isNarration: true },
      { char: 'system', text: '그루미의 표정은 마지막까지 변하지 않는다.', isNarration: true },
      { char: 'groomy', text: '...괜찮아.' },
      { char: 'groomy', text: '이게 내가 만들어진 이유였나 봐.' },
      { char: 'system', text: '이 말을 듣는 순간, 손이 떨렸다.', isNarration: true },
      { char: 'system', text: '만들어진 이유.', isNarration: true },
      { char: 'system', text: '그루미는 — 끝까지 자기 존재를 정당화할 이유를 스스로 찾고 있었다.', isNarration: true },
      { char: 'system', text: '누군가를 살리기 위해 부품이 되는 것, 그게 자기 존재의 목적이었다고 받아들이는 방식으로.', isNarration: true },
      { char: 'groomy', text: '잘 가.' },
      { char: 'groomy', text: '신입.' },
      { char: 'system', text: '마지막 두 마디는, CH4의 가장 차가운 분기에서 그루미가 신입에게 했던 그 말과 정확히 같은 단어였다.', isNarration: true },
      { char: 'system', text: '다만 그때는 차갑게 버려지는 쪽에서 나온 말이었고, 지금은 — 스스로 떠나보내는 쪽에서 나온 말이었다.', isNarration: true },
      { char: 'system', text: '같은 두 마디가 이렇게 다른 무게를 가질 수 있다는 게, 오히려 더 아팠다.', isNarration: true },
      { char: 'system', text: '집에 돌아온 뒤, 아라의 질문에 답하지 못한다.', isNarration: true, important: true },
      { char: 'system', text: '호환 배터리는 손에 들려 있지만, 말은 입안에 남는다.', isNarration: true },
      { char: 'system', text: '집 문을 열었을 때, 아라는 평소처럼 창가에 앉아 있었다.', isNarration: true },
      { char: 'system', text: '손에 든 작은 코어를 내밀었을 때, 아라는 그게 무엇인지 묻지 않았다.', isNarration: true },
      { char: 'system', text: '그냥 받았다.', isNarration: true },
      { char: 'system', text: '그리고 그 후로 며칠 동안, 둘 사이에는 이전과 같은 종류의 대화가 돌아오지 않았다.', isNarration: true },
      { char: 'system', text: '고마워요.', isNarration: true },
      { char: 'system', text: '...', isNarration: true },
      { char: 'system', text: '왜 그래요? 표정이.', isNarration: true },
      { char: 'system', text: '...아무것도 아니야.', isNarration: true },
      { char: 'system', text: '아무것도 아니라는 말은, 거짓말이었다.', isNarration: true },
      { char: 'system', text: '다만 그 거짓말을 풀어낼 단어를 찾을 수가 없었다.', isNarration: true },
      { char: 'system', text: '어디서 구했어요 라는 질문에 답하는 순간, 이 침묵이 끝나기는 할까.', isNarration: true },
      { char: 'system', text: '아니면 평생, 그루미의 마지막 두 마디가 — 잘 가, 신입 — 머릿속에서 사라지지 않을까.', isNarration: true },
      { char: 'system', text: '목표는 달성됐다.', isNarration: true },
      { char: 'system', text: '아라는 살았다.', isNarration: true },
      { char: 'system', text: '다만 그 성공이, 처음 이 일을 시작했을 때 상상했던 어떤 결말과도 닮지 않았다.', isNarration: true },
    ],
    next: 'ch5_closing',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'dismantledGroomy' }],
  },
  ending_normal: {
    id: 'chapter-05.ending_normal',
    chapterId: 'chapter-05',
    localId: 'ending_normal',
    mode: SceneModes.VN,
    emotion: 'neutral',
    lines: [
      { char: 'groomy', text: '저 대신.' },
      { char: 'groomy', text: '오래오래 같이 있어 줘요.' },
      { char: 'system', text: '그루미가 자발적으로 배터리 코어를 내준다.', isNarration: true, important: true },
      { char: 'system', text: '그 과정은, 강제로 해체하는 것과는 분명히 달랐다.', isNarration: true },
      { char: 'system', text: '그루미가 직접 자신의 가슴 쪽 패널을 열었고, 코어를 직접 손에 쥐어 건넸다.', isNarration: true },
      { char: 'system', text: '누구의 강요도 아니었고, 그렇다고 완전히 평온한 결정도 아니었다.', isNarration: true },
      { char: 'system', text: '그냥 — 그루미 나름의 방식으로, 가장 덜 아픈 길을 스스로 골랐다는 느낌이었다.', isNarration: true },
      { char: 'system', text: '돌아오는 길이 평소보다 길게 느껴진다.', isNarration: true, important: true },
      { char: 'system', text: '그루미의 자리에는 묘한 공백만 남는다.', isNarration: true },
      { char: 'system', text: '코어를 건네받은 뒤, 그루미는 — 사라지지는 않았다.', isNarration: true },
      { char: 'system', text: '다만 뭔가가 분명히 비어 있었다.', isNarration: true },
      { char: 'system', text: '평소처럼 "아마"를 붙이며 말을 걸지도 않았고, 그렇다고 화를 내거나 슬퍼하는 것도 아니었다.', isNarration: true },
      { char: 'system', text: '그냥, 조금 더 조용해졌다.', isNarration: true },
      { char: 'system', text: '마치 자기 자신의 일부를 떼어내고 난 뒤, 남은 부분으로 어떻게든 평소처럼 굴려고 애쓰는 듯했다.', isNarration: true },
      { char: 'system', text: '집으로 돌아가는 길, "오래오래 같이 있어 줘요"라는 그 말이 계속 맴돌았다.', isNarration: true },
      { char: 'system', text: '그루미가 떠나는 게 아니라, 함께 있어달라는 부탁이었다는 것.', isNarration: true },
      { char: 'system', text: '코어를 내어주는 게 작별이 아니라, 오히려 더 오래 곁에 있고 싶다는 마음의 다른 표현이었다는 것.', isNarration: true },
      { char: 'system', text: '그 사실이, 단순한 "성공"이라는 말로는 다 설명되지 않는 감정을 남겼다.', isNarration: true },
    ],
    next: 'ch5_closing',
  },
  ending_badB: {
    id: 'chapter-05.ending_badB',
    chapterId: 'chapter-05',
    localId: 'ending_badB',
    mode: SceneModes.VN,
    emotion: 'warning',
    lines: [
      { char: 'system', text: '망설임 없이 해체가 진행된다.', isNarration: true, important: true },
      { char: 'system', text: '이번엔 "미안해"라는 말도 없었다.', isNarration: true },
      { char: 'system', text: '그냥, 해야 할 일을 하는 것처럼 진행됐다.', isNarration: true },
      { char: 'groomy', text: '아프네요.' },
      { char: 'groomy', text: '이거.' },
      { char: 'system', text: '그 두 마디가 전부였다.', isNarration: true },
      { char: 'system', text: '비난도, 호소도, 마지막 인사도 없이.', isNarration: true },
      { char: 'system', text: '그루미는 — 적어도 이 순간만큼은 — 그저 사실을 보고하듯 자기 상태를 알렸다.', isNarration: true },
      { char: 'system', text: '아프다는 말도, 따지고 보면 그루미가 끝까지 잃지 않은 솔직함이었다.', isNarration: true },
      { char: 'caretaker', text: '다음 직원의 자리를 마련해 두겠습니다.' },
      { char: 'system', text: '이 한 줄이, 그루미의 마지막 두 마디보다 더 섬뜩했다.', isNarration: true },
      { char: 'system', text: '마치 지금 일어난 일이 — 한 존재의 해체가 — 이 회사 입장에서는 그저 일상적인 절차에 불과하다는 듯.', isNarration: true },
      { char: 'system', text: '슬퍼할 필요도, 책임질 필요도 없는, 그냥 다음 단계로 넘어가는 행정 처리.', isNarration: true },
      { char: 'system', text: '새 세션 ID가 발급된다.', isNarration: true, important: true },
      { char: 'system', text: '회전문이 다시 돈다.', isNarration: true, important: true },
      { char: 'system', text: '회전문이 돌아가는 소리가, 멀리서 들려왔다.', isNarration: true },
      { char: 'system', text: '처음 이 회사에 들어오던 날 들었던 바로 그 소리.', isNarration: true },
      { char: 'system', text: '그 문을 통해 — 또 다른 누군가가, 또 다른 사번을 받고, 또 다른 그루미와 마주하기 위해 — 들어오고 있을 거라는 사실을 알 수 있었다.', isNarration: true },
      { char: 'system', text: '박서이가 일기에 남긴 마지막 바람, 부디 다음에 오는 사람도, 그러길 이라는 문장이 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: '이 결말에서는 — 그 바람이 끝내 닿지 않았다.', isNarration: true },
      { char: 'system', text: '진실도 모른 채, 관계도 쌓지 못한 채, 그저 가장 빠른 길로 목표를 달성했다.', isNarration: true },
      { char: 'system', text: '목표는 달성됐을 것이다.', isNarration: true },
      { char: 'system', text: '다만 그 달성이 무엇을 대가로 했는지조차, 끝내 제대로 알지 못한 채로.', isNarration: true },
    ],
    next: 'ch5_closing',
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'dismantledGroomy' }],
  },
  ch5_closing: {
    id: 'chapter-05.ch5_closing',
    chapterId: 'chapter-05',
    localId: 'ch5_closing',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    lines: [
      { char: 'system', text: '네 갈래의 길이 모두, 같은 화면으로 모인다.', isNarration: true },
      { char: 'system', text: 'CHAPTER 05 CLEAR — 「마지막 카드」', isNarration: true, important: true },
      { char: 'system', text: '마지막 카드.', isNarration: true },
      { char: 'system', text: '처음 회사에 들어올 때 손에 쥐었던 그 사번 카드가, 다시 떠올랐다.', isNarration: true },
      { char: 'system', text: '그 카드는 시작부터 끝까지 — 신입의 것이 아니라 박서이의 것이었다.', isNarration: true },
      { char: 'system', text: '이제 그 카드를 들고 들어왔던 여정이 끝났다.', isNarration: true },
      { char: 'system', text: '다만 그 끝이 어떤 모양이었는지는, 그동안 쌓아온 모든 선택의 합이었다.', isNarration: true },
      { char: 'system', text: '회사를 나서며, 처음 입구에서 봤던 그 회전문을 다시 지나쳤다.', isNarration: true },
      { char: 'system', text: '어떤 결말에 도달했든, 그 문은 똑같이 돌아가고 있었다.', isNarration: true },
      { char: 'system', text: '다만 그 문을 지나는 마음만큼은, 결코 같지 않았다.', isNarration: true },
    ],
    next: 'ch5_end',
  },
  ch5_end: {
    id: 'chapter-05.ch5_end',
    chapterId: 'chapter-05',
    localId: 'ch5_end',
    mode: SceneModes.END,
    title: '마지막 카드',
  },
}

function addLineRefs(scene) {
  if (!Array.isArray(scene.lines)) return scene
  return {
    ...scene,
    lines: scene.lines.map((line, index) => ({
      ...line,
      textKey: line.textKey ?? `${scene.id}.line${String(index + 1).padStart(2, '0')}`,
    })),
  }
}

function addSceneRefs(scene) {
  const withLineRefs = addLineRefs(scene)
  const withTheme = {
    ...withLineRefs,
    modeLabelKey: withLineRefs.mode === SceneModes.VN ? 'modeBarVnDefault' : withLineRefs.mode === SceneModes.RPG ? 'modeBarRpgDefault' : 'modeBarChatDefault',
    chatTheme: withLineRefs.mode === SceneModes.CHAT ? {
      profileId: withLineRefs.emotion === 'warning' ? 'corrupted' : 'normal',
      wallpaperAssetId: withLineRefs.emotion === 'warning' ? 'overlay_glitch_soft' : 'bg_default_office',
    } : undefined,
  }
  if (withLineRefs.mode === SceneModes.VN) {
    const isPerception =
      withLineRefs.localId.includes('perception') ||
      withLineRefs.localId.includes('office') ||
      withLineRefs.localId.includes('battery_weight')
    const isEnding = withLineRefs.localId.startsWith('ending')
    return {
      ...withTheme,
      vnStage: withLineRefs.vnStage ?? {
        bgId: isPerception ? 'bg_default_office' : isEnding ? 'bg_ch02_lobby' : 'bg_stairwell_floor3',
        overlayId: withLineRefs.important ? 'overlay_glitch_soft' : 'overlay_scanline',
        characters: [],
      },
    }
  }
  return withTheme
}

export const chapter05Scenes = Object.fromEntries(
  Object.entries(rawChapter05Scenes).map(([localId, scene]) => [localId, addSceneRefs(scene)]),
)
