/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/polyhaven/metal_office_desk/metal_office_desk_1k.gltf -o src/components/models/MetalOfficeDesk.jsx --transform=false --root public
*/

import { useGLTF } from '@react-three/drei'
import HeroProp from '../../systems/HeroProp.jsx'

export function MetalOfficeDesk(props) {
  const { nodes, materials } = useGLTF('/models/polyhaven/metal_office_desk/metal_office_desk_1k.gltf')
  return (
    <HeroProp contactScale={3.4} {...props}>
      <mesh geometry={nodes.metal_office_desk_drawer_06.geometry} material={materials.metal_office_desk} />
      <mesh geometry={nodes.metal_office_desk_tray_01.geometry} material={materials.metal_office_desk} />
      <mesh geometry={nodes.metal_office_desk.geometry} material={materials.metal_office_desk} />
      <mesh geometry={nodes.metal_office_desk_drawer_04.geometry} material={materials.metal_office_desk} />
      <mesh geometry={nodes.metal_office_desk_drawer_03.geometry} material={materials.metal_office_desk} />
      <mesh geometry={nodes.metal_office_desk_drawer_05.geometry} material={materials.metal_office_desk} />
      <mesh geometry={nodes.metal_office_desk_drawer_02.geometry} material={materials.metal_office_desk} />
      <mesh geometry={nodes.metal_office_desk_drawer_01.geometry} material={materials.metal_office_desk} />
      <mesh geometry={nodes.metal_office_desk_tray_02.geometry} material={materials.metal_office_desk} />
    </HeroProp>
  )
}

useGLTF.preload('/models/polyhaven/metal_office_desk/metal_office_desk_1k.gltf')
