/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/polyhaven/office_notepads/office_notepads_1k.gltf -o src/components/models/OfficeNotepads.jsx --transform=false 
*/

import { useGLTF } from '@react-three/drei'
import HeroProp from '../../systems/HeroProp.jsx'

export function OfficeNotepads(props) {
  const { nodes, materials } = useGLTF('/models/polyhaven/office_notepads/office_notepads_1k.gltf')
  return (
    <HeroProp contactScale={1.6} {...props}>
      <mesh geometry={nodes.office_notepads_yellow_sheet.geometry} material={materials.office_notepads} position={[0.15, 0, 0.175]} />
      <mesh geometry={nodes.office_notepads_yellow_pad.geometry} material={materials.office_notepads} position={[0.15, 0, -0.175]} />
      <mesh geometry={nodes.office_notepads_note_stack.geometry} material={materials.office_notepads} position={[0.45, 0, -0.275]} />
      <mesh geometry={nodes.office_notepads_sticky_stack.geometry} material={materials.office_notepads} position={[0.45, 0, 0.085]} />
      <mesh geometry={nodes.office_notepads_sticky_sheet.geometry} material={materials.office_notepads} position={[0.45, 0, 0.255]} />
      <mesh geometry={nodes.office_notepads_note_sheet.geometry} material={materials.office_notepads} position={[0.45, 0, -0.075]} />
      <mesh geometry={nodes.office_notepads_a4_stack.geometry} material={materials.office_notepads} position={[-0.45, 0, -0.175]} />
      <mesh geometry={nodes.office_notepads_a4_a.geometry} material={materials.office_notepads} position={[-0.45, 0, 0.175]} />
      <mesh geometry={nodes.office_notepads_a4_b.geometry} material={materials.office_notepads} position={[-0.15, 0, -0.17]} />
      <mesh geometry={nodes.office_notepads_a4_c.geometry} material={materials.office_notepads} position={[-0.15, 0, 0.18]} />
    </HeroProp>
  )
}

useGLTF.preload('/models/polyhaven/office_notepads/office_notepads_1k.gltf')
