/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/polyhaven/potted_plant_04/potted_plant_04_1k.gltf -o src/components/models/PottedPlant04.jsx --transform=false --root public
*/

import { useGLTF } from '@react-three/drei'
import HeroProp from '../../systems/HeroProp.jsx'

export function PottedPlant04(props) {
  const { nodes, materials } = useGLTF('/models/polyhaven/potted_plant_04/potted_plant_04_1k.gltf')
  return (
    <HeroProp contactScale={1.4} {...props}>
      <mesh geometry={nodes.potted_plant_04_ground.geometry} material={materials.potted_plant_04} />
      <mesh geometry={nodes.potted_plant_04_dirt.geometry} material={materials.potted_plant_04} />
      <mesh geometry={nodes.potted_plant_04_plant.geometry} material={materials.potted_plant_04} />
      <mesh geometry={nodes.potted_plant_04_pot.geometry} material={materials.potted_plant_04} />
    </HeroProp>
  )
}

useGLTF.preload('/models/polyhaven/potted_plant_04/potted_plant_04_1k.gltf')
