/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/polyhaven/SchoolChair_01/SchoolChair_01_1k.gltf -o src/components/models/SchoolChair.jsx --transform=false 
*/

import { useGLTF } from '@react-three/drei'
import HeroProp from '../../systems/HeroProp.jsx'
import { assetUrl } from '../../runtime/assetUrl.js'

const SRC = assetUrl('/models/polyhaven/SchoolChair_01/SchoolChair_01_1k.gltf')

export function SchoolChair(props) {
  const { nodes, materials } = useGLTF(SRC)
  return (
    <HeroProp {...props}>
      <mesh geometry={nodes.SchoolChair_01.geometry} material={materials.SchoolChair_01} />
    </HeroProp>
  )
}

useGLTF.preload(SRC)
