/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/polyhaven/wall_clock/wall_clock_1k.gltf -o src/components/models/WallClock.jsx --transform=false 
*/

import { useGLTF } from '@react-three/drei'
import HeroProp from '../../systems/HeroProp.jsx'

export function WallClock(props) {
  const { nodes, materials } = useGLTF('/models/polyhaven/wall_clock/wall_clock_1k.gltf')
  return (
    <HeroProp contact={false} {...props}>
      <mesh geometry={nodes.wall_clock_minute_hand.geometry} material={materials.wall_clock} />
      <mesh geometry={nodes.wall_clock_second_hand.geometry} material={materials.wall_clock} />
      <mesh geometry={nodes.wall_clock_hours_hand.geometry} material={materials.wall_clock} />
      <mesh geometry={nodes.frame001.geometry} material={materials.wall_clock} />
      <mesh geometry={nodes.frame001_1.geometry} material={materials.wall_clock_glass} />
    </HeroProp>
  )
}

useGLTF.preload('/models/polyhaven/wall_clock/wall_clock_1k.gltf')
