import { CH02_ASSETS as ASSETS } from './assets.js'

export const rawChapter02Maps = {
  floor5: {
    id: 'floor5',
    label: '5F 보안감사 구역',
    floorId: '5F',
    ambient: '밝은 사무실 조명 아래에서 서버 팬 소리만 낮게 돈다.',
    hint: '전임자 로그와 3층 출입 기록의 연결점을 찾으세요. 서버 패널·기록실·분석가(개인 충전 로그)를 조사하세요.',
    cols: 12,
    rows: 8,
    tileSize: 40,
    spriteFrame: { width: 32, height: 32 },
    backgroundAssetId: ASSETS.bg.floor5,
    tilesetAssetId: ASSETS.tileset.floor5,
    playerSpriteAssetId: ASSETS.sprite.player,
    tilesetMap: { 0: [0, 0], 1: [1, 0], 2: [2, 0], 3: [0, 1], 4: [1, 1] },
    playerStart: { row: 6, col: 1, facing: { dr: 0, dc: 1 } },
    grid: [
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1],
      [1, 0, 0, 3, 0, 0, 0, 0, 4, 0, 0, 1],
      [1, 0, 0, 0, 0, 3, 0, 0, 4, 0, 0, 1],
      [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
      [1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 1],
      [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    ],
    labels: {
      '3-3': '서버 패널',
      '3-5': '기록실 입구',
      '4-5': '거울 파편',
      '4-8': '잠긴 보관함',
      '5-5': '감사 경보',
      '6-2': '보안요원',
      '6-10': '데이터 분석가',
    },
    triggers: {
      '3-3': 'server_panel_chat',
      '3-5': 'vault_terminal_chat',
      '4-5': 'mirror_clue_vn',
      '4-8': 'locker_chat',
      '5-5': 'escalation_vn',
      '6-2': 'guard_chat',
      '6-10': 'analyst_chat',
    },
    eventTiles: [
      { id: 'floor5.server', key: '3-3', trigger: 'server_panel_chat' },
      { id: 'floor5.records', key: '3-5', trigger: 'vault_terminal_chat' },
      { id: 'floor5.mirror', key: '4-5', trigger: 'mirror_clue_vn' },
      { id: 'floor5.locker', key: '4-8', trigger: 'locker_chat' },
      { id: 'floor5.escalation', key: '5-5', trigger: 'escalation_vn' },
    ],
    npcs: [
      {
        id: 'npc_guard',
        name: '보안요원 서준',
        label: '보안요원 서준',
        position: { row: 6, col: 2 },
        spriteAssetId: ASSETS.sprite.guard,
        trigger: 'guard_chat',
      },
      {
        id: 'npc_analyst',
        name: '분석가 리아',
        label: '분석가 리아',
        position: { row: 6, col: 10 },
        spriteAssetId: ASSETS.sprite.analyst,
        trigger: 'analyst_chat',
      },
    ],
    ambientFlags: [
      { id: 'floor5.flicker', enabled: true, intensity: 0.7, overlayAssetId: ASSETS.overlay.scanline },
    ],
    investigation: {
      progressLabel: '5F 감사 구역 조사',
      exitScene: 'mirror_clue_vn',
      exitRequirements: [
        { type: 'flag', flag: 'foundBatteryCompatCheckLog' },
        { type: 'flag', flag: 'foundDuplicateAccessRecord' },
        { type: 'flag', flag: 'ch2_guardInterviewed' },
        { type: 'flag', flag: 'learnedGroomySeenInTwoPlaces' },
        { type: 'flag', flag: 'foundBatterySpecWithGroomyNote' },
      ],
      spots: [
        { flag: 'foundBatteryCompatCheckLog', label: '서버 패널', tileKey: '3-3', trigger: 'server_panel_chat' },
        { flag: 'foundDuplicateAccessRecord', label: '기록실 입구', tileKey: '3-5', trigger: 'vault_terminal_chat' },
        { flag: 'foundBatterySpecWithGroomyNote', label: '잠긴 보관함', tileKey: '4-8', trigger: 'locker_chat' },
        { flag: 'ch2_triggeredAuditAlarm', label: '감사 경보', tileKey: '5-5', trigger: 'escalation_vn' },
        { flag: 'ch2_guardInterviewed', label: '보안요원', tileKey: '6-2', trigger: 'guard_chat' },
        { flag: 'learnedGroomySeenInTwoPlaces', label: '데이터 분석가', tileKey: '6-10', trigger: 'analyst_chat' },
      ],
    },
  },
}
