import { EffectTypes, SceneModes } from '../../../engine/contracts.js'
import {
  PERCEPTION_LAYER,
  PREDECESSOR_GIVEN,
  PREDECESSOR_ID,
  SESSION_EMP_ID,
} from '../../world/company.js'
import { CH02_ASSETS as ASSETS } from './assets.js'

const relationship = {
  close: { type: EffectTypes.ADD_SCORE, score: 'groomyAffinity', amount: 1 },
  closer: { type: EffectTypes.ADD_SCORE, score: 'groomyAffinity', amount: 2 },
  distant: { type: EffectTypes.ADD_SCORE, score: 'groomyAffinity', amount: -1 },
}

const evidence = (amount = 1) => ({ type: EffectTypes.ADD_SCORE, score: 'mysteryEvidence', amount })
const batteryPressure = (amount = 1) => ({ type: EffectTypes.ADD_SCORE, score: 'batteryDesperation', amount })

const mirrorInvestigationComplete = [
  { type: 'flag', flag: 'foundBatteryCompatCheckLog' },
  { type: 'flag', flag: 'foundDuplicateAccessRecord' },
  { type: 'flag', flag: 'ch2_guardInterviewed' },
  { type: 'flag', flag: 'learnedGroomySeenInTwoPlaces' },
  { type: 'flag', flag: 'foundBatterySpecWithGroomyNote' },
]

export const rawChapter02Scenes = {
  arrival_vn: {
    id: 'chapter-02.arrival_vn',
    chapterId: 'chapter-02',
    localId: 'arrival_vn',
    mode: SceneModes.VN,
    emotion: 'neutral',
    backgroundAssetId: ASSETS.bg.lobby,
    vnStage: {
      bgId: ASSETS.bg.lobby,
      overlayId: ASSETS.overlay.scanline,
      characters: [],
    },
    lines: [
      { char: 'system', text: '엘리베이터 문이 열린다.', isNarration: true },
      { char: 'system', text: '5층. 보안 감사 구역.', isNarration: true },
      { char: 'system', text: '복도 조명이 다른 층보다 한 톤 차갑다.', isNarration: true },
      { char: 'groomy', text: '여기부터는.', delayMs: 400 },
      { char: 'groomy', text: '제 권한이 줄어들어요.' },
      { char: 'groomy', text: '…그래서 더 말이 많아질 거예요.' },
      { char: 'groomy', text: '불안하면 말이 많아지더라고요.' },
      {
        char: 'iseol',
        text: '너도 그래?',
        portrait: { charId: 'iseol', baseId: ASSETS.portrait.kimBase, position: 'left', expression: 'neutral' },
        portraitAssetId: ASSETS.portrait.kimBase,
      },
      {
        char: 'groomy',
        text: '저도 그런가 봐요.',
        portrait: { charId: 'groomy', baseId: ASSETS.portrait.unknownSmile, position: 'right', expression: 'smile' },
        portraitAssetId: ASSETS.portrait.unknownSmile,
      },
      { char: 'system', text: '강이솔 선임이 출입 카드를 단말기에 가져간다. 승인까지 평소보다 1.2초 더 걸린다.', isNarration: true },
      {
        char: 'iseol',
        text: '이상하다.',
        portrait: { charId: 'iseol', baseId: ASSETS.portrait.kimWarn, position: 'left', expression: 'warning' },
        portraitAssetId: ASSETS.portrait.kimWarn,
      },
      {
        char: 'iseol',
        text: '원래 바로 열리는데.',
        portrait: { charId: 'iseol', baseId: ASSETS.portrait.kimWarn, position: 'left', expression: 'warning' },
        portraitAssetId: ASSETS.portrait.kimWarn,
      },
      {
        char: 'groomy',
        text: '시스템이.',
        portrait: { charId: 'groomy', baseId: ASSETS.portrait.unknownBlank, position: 'right', expression: 'blank' },
        portraitAssetId: ASSETS.portrait.unknownBlank,
      },
      { char: 'groomy', text: '누가 들어오는지.' },
      { char: 'groomy', text: '한 번 더 확인한 거예요.' },
      { char: 'player', text: '저를요?' },
      { char: 'groomy', text: '…아니면.' },
      { char: 'groomy', text: '저를요.' },
    ],
    choices: [
      {
        text: '전임자 접속 로그부터 확인한다.',
        next: 'signal_vn',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_checkedPredecessorLogFirst' },
          { type: EffectTypes.ADD_ITEM, item: 'floor5AccessTrace' },
          evidence(1),
        ],
      },
      {
        text: '3층 출입기록부터 확보한다.',
        next: 'signal_vn',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_checkedDoorFirst' },
          { type: EffectTypes.ADD_ITEM, item: 'floor3EntryLog' },
          evidence(1),
        ],
      },
    ],
  },
  signal_vn: {
    id: 'chapter-02.signal_vn',
    chapterId: 'chapter-02',
    localId: 'signal_vn',
    mode: SceneModes.VN,
    emotion: 'nervous',
    important: true,
    backgroundAssetId: ASSETS.bg.serverHall,
    vnStage: {
      bgId: ASSETS.bg.serverHall,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    lines: [
      { char: 'system', text: '서버홀 입구, 보안 단말기 화면에 두 개의 사번이 동시에 깜빡인다.', isNarration: true },
      {
        char: 'system',
        text: `${PREDECESSOR_ID} — ${PREDECESSOR_GIVEN}`,
        isNarration: true,
      },
      {
        char: 'system',
        text: ({ nickname }) => `${SESSION_EMP_ID} — ${nickname}`,
        isNarration: true,
        important: true,
      },
      {
        char: 'iseol',
        text: '이거.',
        portrait: { charId: 'iseol', baseId: ASSETS.portrait.kimFear, position: 'left', expression: 'fear' },
        portraitAssetId: ASSETS.portrait.kimFear,
      },
      { char: 'iseol', text: '왜 같이 떠요?' },
      { char: 'groomy', text: 'TEMP_CARD_BINDING이.' },
      { char: 'groomy', text: '풀리지 않았으니까요.' },
      {
        char: 'groomy',
        text: '중첩이 아니라 임시 매핑이에요. 회사가 그렇게 부르고 싶어 하니까.',
        important: true,
      },
      { char: 'groomy', text: '당신은 여전히.' },
      { char: 'groomy', text: `${PREDECESSOR_GIVEN}로도 등록돼 있어요.` },
      { char: 'player', text: '이게 정상이에요?' },
      { char: 'groomy', text: '아니요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '지금까지 아무도 안 고쳤어요.' },
      { char: 'iseol', text: '…왜?' },
      { char: 'groomy', text: '고치려면.' },
      { char: 'groomy', text: `누군가 ${PREDECESSOR_GIVEN}가 죽었다는 걸.` },
      { char: 'groomy', text: '공식적으로 인정해야 하니까요.' },
      { char: 'groomy', text: '아직 아무도.' },
      { char: 'groomy', text: '그 서류에 서명 안 했어요.' },
      { char: 'groomy', text: '저도 포함해서요.', delayMs: 3000 },
    ],
    next: 'briefing_chat',
  },
  briefing_chat: {
    id: 'chapter-02.briefing_chat',
    chapterId: 'chapter-02',
    localId: 'briefing_chat',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    systemMessage: 'CARETAKER SYSTEMS · 5F 감사 채널',
    lines: [
      { char: 'iseol', text: '오늘 목표는 공식 감사 로그만 남기는 거예요.' },
      { char: 'iseol', text: '다른 거 건드리면.' },
      { char: 'iseol', text: '저도 책임져야 해요.' },
      { char: 'groomy', text: '공식 로그만 보면.' },
      { char: 'groomy', text: '아무것도 안 나와요.' },
      { char: 'groomy', text: `${PREDECESSOR_GIVEN}가 5층에.` },
      { char: 'groomy', text: '뭘 숨겼는지.' },
      { char: 'groomy', text: '그게 더 중요하잖아요.' },
      { char: 'iseol', text: '그루미.' },
      { char: 'iseol', text: '나도 알아.' },
      { char: 'iseol', text: '근데 나는.' },
      { char: 'iseol', text: '규칙을 지켜야 남을 수 있는 사람이야.' },
      { char: 'system', text: '채널에 "외부 조사 금지" 워터마크가 자동으로 붙는다.', isNarration: true },
      { char: 'player', text: '(두 사람을 보며) …' },
    ],
    choices: [
      {
        text: '공식 절차를 따르겠다고 답한다.',
        next: 'records_vn',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_acceptedOfficialAudit' },
          relationship.distant,
        ],
      },
      {
        text: '박서이 흔적을 우선하겠다고 답한다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_prioritizedPredecessorTrail' },
          relationship.close,
          evidence(1),
        ],
      },
      {
        text: '일단 둘러보고 결정할게요.',
        next: 'floor5_rpg',
        effects: [{ type: EffectTypes.ADD_FLAG, flag: 'stayedNeutralCh2' }],
      },
    ],
  },
  records_vn: {
    id: 'chapter-02.records_vn',
    chapterId: 'chapter-02',
    localId: 'records_vn',
    mode: SceneModes.VN,
    emotion: 'warning',
    backgroundAssetId: ASSETS.bg.serverHall,
    vnStage: {
      bgId: ASSETS.bg.serverHall,
      overlayId: ASSETS.overlay.scanline,
      characters: [],
    },
    lines: [
      { char: 'system', text: '기록실 문이 열리고, 종이 대신 냉각 팬 소리가 밀려온다.', isNarration: true },
      {
        char: 'iseol',
        text: '여기 원장은 수기가 아니라 센서가 씁니다.',
        portrait: { charId: 'iseol', baseId: ASSETS.portrait.kimBase, position: 'left', expression: 'neutral' },
        portraitAssetId: ASSETS.portrait.kimBase,
      },
      {
        char: 'groomy',
        text: '그래서 지우기 어렵죠. 지우려면 누군가 살아 있어야 하고요.',
        portrait: { charId: 'groomy', baseId: ASSETS.portrait.unknownSmile, position: 'right', expression: 'smile' },
        portraitAssetId: ASSETS.portrait.unknownSmile,
      },
      { char: 'iseol', text: '감사 원장 단말기는 저쪽이에요.' },
      { char: 'groomy', text: '봉투함도 있어요. 비어 있는 것도요.' },
    ],
    choices: [
      {
        text: '원장 단말기로 간다.',
        next: 'floor5_rpg',
      },
      {
        text: '봉투함부터 연다.',
        next: 'vault_box_chat',
      },
    ],
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch2_enteredRecordsVault' }],
  },
  floor5_rpg: {
    id: 'chapter-02.floor5_rpg',
    chapterId: 'chapter-02',
    localId: 'floor5_rpg',
    mode: SceneModes.RPG,
    mapId: 'floor5',
  },
  server_panel_chat: {
    id: 'chapter-02.server_panel_chat',
    chapterId: 'chapter-02',
    localId: 'server_panel_chat',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'floor5_rpg',
    lines: [
      { char: 'system', text: '서버 패널 화면에 명령어 로그가 떠 있다.', isNarration: true },
      { char: 'system', text: 'BATTERY_COMPAT_CHECK', isNarration: true },
      { char: 'system', text: '실행 시각: 사고 당일 03:09', isNarration: true },
      {
        char: 'system',
        text: '실행자: GROOMY-LINE/GEN-2 #0041',
        isNarration: true,
        important: true,
      },
      { char: 'player', text: 'GEN-2 #0041이면.' },
      { char: 'player', text: '그루미 본인 아니에요?' },
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '제 실행 로그예요.' },
      { char: 'groomy', text: '근데 저는.' },
      { char: 'groomy', text: '이걸 실행한 기억이 없어요.' },
      { char: 'iseol', text: '기억이 없다는 게.' },
      { char: 'iseol', text: '무슨 뜻이야.' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '그냥.' },
      { char: 'groomy', text: '거기 제 이름이 있는데.' },
      { char: 'groomy', text: '저는 안 한 것 같아요.' },
      { char: 'groomy', text: '…안 한 것 같다는 말도.' },
      { char: 'groomy', text: '이상하네요.' },
      { char: 'groomy', text: '제가 한 건.' },
      { char: 'groomy', text: '제가 알아야 하는데.' },
    ],
    choices: [
      {
        text: '명령 로그를 캡처한다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_capturedServerCommand' },
          { type: EffectTypes.ADD_FLAG, flag: 'foundBatteryCompatCheckLog' },
          { type: EffectTypes.ADD_ITEM, item: 'auditLedgerFragment' },
          evidence(2),
          batteryPressure(1),
        ],
      },
      {
        text: '이솔에게만 공유한다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_sharedServerCommandWithIseol' },
          { type: EffectTypes.ADD_FLAG, flag: 'foundBatteryCompatCheckLog' },
          evidence(1),
          relationship.close,
        ],
      },
    ],
  },
  vault_terminal_chat: {
    id: 'chapter-02.vault_terminal_chat',
    chapterId: 'chapter-02',
    localId: 'vault_terminal_chat',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    returnTo: 'floor5_rpg',
    lines: [
      { char: 'system', text: '감사 원장 더미 속, 같은 사번이 42초 차이로 두 개의 출입 기록을 남겼다.', isNarration: true },
      { char: 'system', text: `${PREDECESSOR_ID} — 3층 출입 03:14:05`, isNarration: true },
      {
        char: 'system',
        text: `${PREDECESSOR_ID} — 5층 출입 03:14:47`,
        isNarration: true,
        important: true,
      },
      { char: 'player', text: '한 사람이 42초 만에 3층에서 5층까지요?' },
      { char: 'groomy', text: '물리적으로.' },
      { char: 'groomy', text: '불가능해요.' },
      { char: 'groomy', text: '계단으로도.' },
      { char: 'groomy', text: '엘리베이터로도.' },
      { char: 'iseol', text: '…그럼 둘 중 하나는.' },
      { char: 'iseol', text: '가짜라는 거야?' },
      { char: 'groomy', text: '아니요.' },
      { char: 'groomy', text: '둘 다 진짜예요.' },
      { char: 'groomy', text: '같은 사번을 쓴.' },
      { char: 'groomy', text: '다른 존재가 있었다는 거죠.' },
      { char: 'groomy', text: '…저처럼요.', delayMs: 2500 },
    ],
    choices: [
      {
        text: '원장 전체를 보낸다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_exportedAuditLedger' },
          { type: EffectTypes.ADD_FLAG, flag: 'foundDuplicateAccessRecord' },
          { type: EffectTypes.ADD_ITEM, item: 'vaultTamperTrace' },
          evidence(2),
        ],
      },
      {
        text: '핵심 줄만 메모한다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_skimmedAuditLedger' },
          { type: EffectTypes.ADD_FLAG, flag: 'foundDuplicateAccessRecord' },
          evidence(1),
        ],
      },
    ],
  },
  vault_box_chat: {
    id: 'chapter-02.vault_box_chat',
    chapterId: 'chapter-02',
    localId: 'vault_box_chat',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'floor5_rpg',
    lines: [
      { char: 'system', text: '박스 안에는 전임자 명의의 빈 감사 서류 봉투가 있다.', isNarration: true },
      { char: 'iseol', text: '내용물은 비었는데, 봉인 스티커만 새 거예요.' },
      { char: 'groomy', text: '…누군가 미리 비워 둔 것 같아요.' },
    ],
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch2_foundEmptyAuditEnvelope' },
      evidence(1),
    ],
  },
  guard_chat: {
    id: 'chapter-02.guard_chat',
    chapterId: 'chapter-02',
    localId: 'guard_chat',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'floor5_rpg',
    lines: [
      { char: 'system', text: '보안요원 서준이 순찰 박스 앞에 서 있다.', isNarration: true },
      { char: 'guard', text: '사고 당일이요?' },
      { char: 'guard', text: '그날 11분 동안.' },
      { char: 'guard', text: '순찰 기록이 비어요.' },
      { char: 'player', text: '왜 비어 있어요?' },
      { char: 'guard', text: '모릅니다.' },
      { char: 'guard', text: '근무는 했는데.' },
      { char: 'guard', text: '기록만 없어요.' },
      { char: 'groomy', text: '서준 씨.' },
      { char: 'groomy', text: '그 11분 동안.' },
      { char: 'groomy', text: '누구랑 채팅하셨어요?' },
      { char: 'guard', text: '…그건 왜 묻습니까.' },
      { char: 'groomy', text: '당신 폰에.' },
      { char: 'groomy', text: 'TalkLine 로그가 있어요.' },
      { char: 'groomy', text: '삭제됐지만.' },
      { char: 'groomy', text: '완전히는 아니고요.' },
      { char: 'system', text: '보안요원 서준이 시선을 피한다.', isNarration: true },
      { char: 'system', text: '채널 상단에 회사 보안팀의 자동 모니터링 배지가 켜진다.', isNarration: true },
    ],
    choices: [
      {
        text: '규정 질문만 남기고 의심을 낮춘다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_trustedSystem' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_guardProtocolAccepted' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_guardInterviewed' },
        ],
      },
      {
        text: '그루미에게 로그 복구를 부탁한다.',
        next: 'guard_log_recovered',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_trustedSystem' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_guardProtocolAccepted' },
          { type: EffectTypes.ADD_FLAG, flag: 'askedGroomyToRecoverLog' },
          relationship.close,
        ],
      },
      {
        text: '순찰 공백 11분을 추궁한다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_distrustedSystem' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_guardInterviewed' },
          { type: EffectTypes.ADD_ITEM, item: 'guardIncidentMemo' },
          evidence(1),
        ],
      },
      {
        text: '누구랑 채팅했는지 직접 물어본다.',
        next: 'guard_pressed',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_distrustedSystem' },
          { type: EffectTypes.ADD_FLAG, flag: 'pressedGuardDirectly' },
        ],
      },
    ],
  },
  guard_pressed: {
    id: 'chapter-02.guard_pressed',
    chapterId: 'chapter-02',
    localId: 'guard_pressed',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'floor5_rpg',
    lines: [
      { char: 'guard', text: '…최 팀장님이었습니다.' },
      { char: 'guard', text: '그날 잠깐 자리를 비워달라고.' },
      { char: 'guard', text: '그렇게만 말씀하셨어요.' },
      { char: 'player', text: '이유는요?' },
      { char: 'guard', text: '안 물었습니다.' },
      { char: 'guard', text: '물으면 안 될 것 같아서요.' },
    ],
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch2_guardInterviewed' },
      { type: EffectTypes.ADD_FLAG, flag: 'guardNamedChoi' },
      { type: EffectTypes.ADD_ITEM, item: 'guardIncidentMemo' },
      evidence(1),
    ],
  },
  guard_log_recovered: {
    id: 'chapter-02.guard_log_recovered',
    chapterId: 'chapter-02',
    localId: 'guard_log_recovered',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    returnTo: 'floor5_rpg',
    lines: [
      { char: 'system', text: '그루미가 복구한 로그 일부.', isNarration: true },
      { char: 'choi', text: '11분만 비켜줘.' },
      { char: 'choi', text: '3층 쪼개기 작업 때문에.' },
      { char: 'guard', text: '네, 팀장님.' },
      { char: 'groomy', text: '"3층 쪼개기"가.' },
      { char: 'groomy', text: '무슨 작업이에요?' },
      { char: 'guard', text: '모릅니다.' },
      { char: 'guard', text: '저는 그냥.' },
      { char: 'guard', text: '시키는 대로 했어요.' },
      { char: 'groomy', text: '…다들 그렇게 말하네요.' },
      { char: 'groomy', text: '시키는 대로 했다고.' },
      { char: 'groomy', text: '근데 시킨 사람은.' },
      { char: 'groomy', text: '한 명도 책임 안 지고요.' },
    ],
    effects: [
      { type: EffectTypes.ADD_FLAG, flag: 'ch2_guardInterviewed' },
      { type: EffectTypes.ADD_FLAG, flag: 'recoveredGuardChatlog' },
      evidence(2),
    ],
  },
  analyst_chat: {
    id: 'chapter-02.analyst_chat',
    chapterId: 'chapter-02',
    localId: 'analyst_chat',
    mode: SceneModes.CHAT,
    emotion: 'nervous',
    returnTo: 'floor5_rpg',
    lines: [
      { char: 'analyst', text: '센서 로그 보러 오셨어요?' },
      { char: 'analyst', text: '이상한 거 하나 보여드릴게요.' },
      { char: 'system', text: '같은 사번이 42초 차로 다른 문을 통과한 이중 센서 로그가 화면에 뜬다.', isNarration: true },
      { char: 'analyst', text: '이거 처음 봤을 때.' },
      { char: 'analyst', text: '저는 센서 오류라고 보고했어요.' },
      { char: 'player', text: '지금은요?' },
      { char: 'analyst', text: '지금은.' },
      { char: 'analyst', text: '오류가 아니라고 생각해요.' },
      { char: 'groomy', text: '왜 생각이 바뀌었어요?' },
      { char: 'analyst', text: '…그루미 씨가.' },
      { char: 'analyst', text: '같은 시간에 다른 층에서.' },
      { char: 'analyst', text: '목격된 적이 있어서요.' },
      { char: 'groomy', text: '…그게.', delayMs: 3000 },
      { char: 'groomy', text: '무슨 뜻이에요?' },
      { char: 'analyst', text: '저도 잘 모르겠어요.' },
      { char: 'analyst', text: '근데 본 사람이.' },
      { char: 'analyst', text: '한 명이 아니었어요.' },
    ],
    choices: [
      {
        text: '원본 센서 로그를 내려받는다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_downloadedSensorLog' },
          { type: EffectTypes.ADD_FLAG, flag: 'learnedGroomySeenInTwoPlaces' },
          { type: EffectTypes.ADD_ITEM, item: 'duplicateSensorLog' },
          evidence(2),
          batteryPressure(1),
        ],
      },
      {
        text: '분석가에게 요약본만 요청한다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_requestedAnalystSummary' },
          { type: EffectTypes.ADD_FLAG, flag: 'learnedGroomySeenInTwoPlaces' },
          { type: EffectTypes.ADD_ITEM, item: 'sanitizedAuditSummary' },
          evidence(1),
        ],
      },
    ],
  },
  locker_chat: {
    id: 'chapter-02.locker_chat',
    chapterId: 'chapter-02',
    localId: 'locker_chat',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    important: true,
    returnTo: 'floor5_rpg',
    lines: [
      { char: 'system', text: '보관함 안, 박서이의 예비 사원증과 배터리 규격표가 나란히 들어 있다.', isNarration: true },
      {
        char: 'system',
        text: '규격표 모서리에 손글씨: "GEN-2 호환 — 확인 완료"',
        isNarration: true,
        important: true,
      },
      { char: 'player', text: 'GEN-2면.' },
      { char: 'player', text: '그루미랑 같은 라인이잖아요.' },
      { char: 'groomy', text: '…네.' },
      { char: 'groomy', text: '저랑 같은 라인이에요.' },
      { char: 'player', text: '박서이 선임이 왜 이걸 갖고 있었을까요.' },
      { char: 'groomy', text: '모르겠어요.' },
      { char: 'groomy', text: '근데.' },
      { char: 'groomy', text: '이 글씨체.' },
      { char: 'groomy', text: '박서이 선임 거 맞아요.' },
      { char: 'groomy', text: '확인까지 했다는 건.' },
      { char: 'groomy', text: '실제로 시도했다는 뜻이고요.' },
      { char: 'player', text: '시도했다는 게 뭘요?' },
      { char: 'groomy', text: '…저를.', delayMs: 2000 },
      { char: 'groomy', text: '분해해 보려고 했다는 뜻일 수도 있어요.' },
    ],
    choices: [
      {
        text: '규격표를 조용히 챙긴다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_pocketedBatterySpec' },
          { type: EffectTypes.ADD_FLAG, flag: 'foundBatterySpecWithGroomyNote' },
          { type: EffectTypes.ADD_ITEM, item: 'batterySpecFragment' },
          batteryPressure(2),
          evidence(1),
        ],
      },
      {
        text: '이솔에게 먼저 공유한다.',
        next: 'floor5_rpg',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_sharedBatterySpecWithIseol' },
          { type: EffectTypes.ADD_FLAG, flag: 'foundBatterySpecWithGroomyNote' },
          { type: EffectTypes.ADD_ITEM, item: 'batterySpecFragment' },
          batteryPressure(2),
          evidence(1),
          relationship.close,
        ],
      },
    ],
  },
  mirror_clue_vn: {
    id: 'chapter-02.mirror_clue_vn',
    chapterId: 'chapter-02',
    localId: 'mirror_clue_vn',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    backgroundAssetId: ASSETS.bg.mirrorRoom,
    vnStage: {
      bgId: ASSETS.bg.mirrorRoom,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    requirements: mirrorInvestigationComplete,
    lines: [
      { char: 'system', text: '거울방. 사방이 깨진 거울 파편으로 덮여 있다.', isNarration: true },
      { char: 'system', text: '지금까지 모은 단서들이 머릿속에서 겹친다.', isNarration: true },
      {
        char: 'system',
        text: '배터리 호환성 점검. 이중 접속 기록. 같은 시간 다른 곳에서의 목격. 박서이의 분해 시도.',
        isNarration: true,
      },
      { char: 'groomy', text: ({ nickname }) => `…${nickname} 씨.` },
      { char: 'groomy', text: '거울 보세요.' },
      {
        char: 'system',
        text: `${PERCEPTION_LAYER.GLITCH} · 깨진 거울 조각 속에 먼지 쌓인 폐건물 천장이 0.5초간 비친다.`,
        isNarration: true,
        important: true,
        delayMs: 500,
      },
      { char: 'player', text: '방금 그거 봤어요?' },
      { char: 'groomy', text: '…뭐요?' },
      { char: 'groomy', text: '저는.' },
      { char: 'groomy', text: '아무것도 안 봤는데.' },
      { char: 'iseol', text: '나도.' },
      { char: 'iseol', text: '아무것도 안 보였어.' },
      {
        char: 'system',
        text: '그루미만 거울 쪼개진 면을 정확히 피해서 서 있다. 우연이라 보기엔 너무 정확한 각도다.',
        isNarration: true,
        important: true,
      },
      { char: 'player', text: '그루미, 방금 거울 피한 거예요?' },
      { char: 'groomy', text: '…' },
      { char: 'groomy', text: '그랬나요?' },
      { char: 'groomy', text: '저도 모르게 그랬나 봐요.' },
      { char: 'groomy', text: '이상하다.' },
      { char: 'groomy', text: '저는 보통.' },
      { char: 'groomy', text: '모르고 하는 행동이 없는데.' },
      { char: 'groomy', text: '…아니다.', delayMs: 3000 },
      { char: 'groomy', text: '있나 봐요.' },
      { char: 'groomy', text: '이제 결정해야 해요.' },
      { char: 'groomy', text: '지금까지 본 걸 가지고.' },
      { char: 'groomy', text: '어떻게 할지.' },
    ],
    choices: [
      {
        text: '시스템을 신뢰하고 감사 권한을 보존한다.',
        next: 'mirror_after_preserve',
        requirements: [{ type: 'flag', flag: 'ch2_trustedSystem' }],
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_preservedAuditAccess' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_mirrorDecisionMade' },
        ],
      },
      {
        text: '사번 조작을 확정한다.',
        next: 'mirror_after_spoof',
        requirements: [{ type: 'item', item: 'duplicateSensorLog' }],
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_confirmedEmployeeIdSpoof' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_mirrorDecisionMade' },
          evidence(2),
        ],
      },
      {
        text: '순찰 공백과 배터리 단서를 묶어 은폐선을 추적한다.',
        next: 'mirror_after_coverup',
        requirements: [
          { type: 'item', item: 'guardIncidentMemo' },
          { type: 'item', item: 'batterySpecFragment' },
        ],
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_linkedBatteryToCoverup' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_mirrorDecisionMade' },
          batteryPressure(1),
          evidence(1),
        ],
      },
      {
        text: '판단을 보류하고 후퇴한다.',
        next: 'mirror_after_withhold',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_withheldMirrorJudgment' },
          { type: EffectTypes.ADD_FLAG, flag: 'ch2_mirrorDecisionMade' },
          relationship.close,
        ],
      },
    ],
  },
  mirror_after_preserve: {
    id: 'chapter-02.mirror_after_preserve',
    chapterId: 'chapter-02',
    localId: 'mirror_after_preserve',
    mode: SceneModes.VN,
    emotion: 'warning',
    backgroundAssetId: ASSETS.bg.mirrorRoom,
    vnStage: { bgId: ASSETS.bg.mirrorRoom, overlayId: ASSETS.overlay.scanline, characters: [] },
    lines: [
      { char: 'iseol', text: '고마워요.' },
      { char: 'iseol', text: '덕분에 저는.' },
      { char: 'iseol', text: '계속 여기 있을 수 있겠네요.' },
      { char: 'groomy', text: '…그게.' },
      { char: 'groomy', text: '맞는 선택인지는.' },
      { char: 'groomy', text: '저도 모르겠어요.' },
    ],
    next: 'aftermath_chat',
  },
  mirror_after_spoof: {
    id: 'chapter-02.mirror_after_spoof',
    chapterId: 'chapter-02',
    localId: 'mirror_after_spoof',
    mode: SceneModes.VN,
    emotion: 'warning',
    backgroundAssetId: ASSETS.bg.mirrorRoom,
    vnStage: { bgId: ASSETS.bg.mirrorRoom, overlayId: ASSETS.overlay.scanline, characters: [] },
    lines: [
      { char: 'groomy', text: '확정하셨네요.' },
      { char: 'groomy', text: '…후회 안 해요?' },
      { char: 'player', text: '아직은 몰라요.' },
      { char: 'groomy', text: '솔직한 대답이네요.' },
      { char: 'groomy', text: '저도 그렇게 대답하고 싶을 때가 있어요.' },
    ],
    next: 'aftermath_chat',
  },
  mirror_after_coverup: {
    id: 'chapter-02.mirror_after_coverup',
    chapterId: 'chapter-02',
    localId: 'mirror_after_coverup',
    mode: SceneModes.VN,
    emotion: 'warning',
    backgroundAssetId: ASSETS.bg.mirrorRoom,
    vnStage: { bgId: ASSETS.bg.mirrorRoom, overlayId: ASSETS.overlay.scanline, characters: [] },
    lines: [
      { char: 'groomy', text: '…그 쪽으로 가시면.' },
      { char: 'groomy', text: '저도 연결돼요.' },
      { char: 'groomy', text: '괜찮아요?' },
      { char: 'player', text: '괜찮아요, 라고 묻는 거예요?' },
      { char: 'groomy', text: '네.' },
      { char: 'groomy', text: '저 괜찮냐고 묻는 사람.' },
      { char: 'groomy', text: '별로 없어서.' },
    ],
    next: 'aftermath_chat',
  },
  mirror_after_withhold: {
    id: 'chapter-02.mirror_after_withhold',
    chapterId: 'chapter-02',
    localId: 'mirror_after_withhold',
    mode: SceneModes.VN,
    emotion: 'warning',
    backgroundAssetId: ASSETS.bg.mirrorRoom,
    vnStage: { bgId: ASSETS.bg.mirrorRoom, overlayId: ASSETS.overlay.scanline, characters: [] },
    lines: [
      { char: 'groomy', text: '…쉬어가는 것도.' },
      { char: 'groomy', text: '나쁘지 않아요.' },
      { char: 'groomy', text: '저도.' },
      { char: 'groomy', text: '가끔 쉬고 싶어요.' },
      { char: 'groomy', text: '근데 저는.' },
      { char: 'groomy', text: '쉬는 방법을 몰라요.' },
    ],
    next: 'aftermath_chat',
  },
  aftermath_chat: {
    id: 'chapter-02.aftermath_chat',
    chapterId: 'chapter-02',
    localId: 'aftermath_chat',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    systemMessage: 'CARETAKER SYSTEMS · 5F 감사 채널',
    lines: [
      { char: 'system', text: '거울방 기록이 감사 채널에 자동 업로드된다.', isNarration: true },
      { char: 'iseol', text: '이제 회사도 당신 선택을 봤어요.' },
      { char: 'groomy', text: '다음은 제 채널에서 마무리할게요.' },
    ],
    next: 'groomy_debrief',
  },
  escalation_vn: {
    id: 'chapter-02.escalation_vn',
    chapterId: 'chapter-02',
    localId: 'escalation_vn',
    mode: SceneModes.VN,
    emotion: 'warning',
    important: true,
    backgroundAssetId: ASSETS.bg.serverHall,
    vnStage: {
      bgId: ASSETS.bg.serverHall,
      overlayId: ASSETS.overlay.glitchSoft,
      characters: [],
    },
    requirements: [{ type: 'score', score: 'mysteryEvidence', min: 3 }],
    returnTo: 'floor5_rpg',
    lines: [
      { char: 'system', text: '거울방을 나서는 순간, 비상벨이 울린다.', isNarration: true },
      { char: 'system', text: '보안 경보 발생. 5층 비인가 접근 패턴 감지.', isNarration: true },
      { char: 'iseol', text: '이거.' },
      { char: 'iseol', text: '우리 때문이야?' },
      { char: 'groomy', text: '아니요.' },
      { char: 'groomy', text: '저 때문이에요.' },
      { char: 'player', text: '무슨 뜻이에요?' },
      { char: 'groomy', text: '방금.' },
      { char: 'groomy', text: '제 실행 로그가.' },
      { char: 'groomy', text: '또 하나 더 생겼어요.' },
      { char: 'groomy', text: '근데 저는.' },
      { char: 'groomy', text: '방금 아무것도 안 했거든요.' },
      {
        char: 'system',
        text: '깨진 모니터 화면에 두 개의 타임라인이 겹쳐 보인다. 하나는 지금, 하나는 사고 당일. 같은 좌표, 다른 시간.',
        isNarration: true,
        important: true,
      },
      { char: 'groomy', text: '…저게.' },
      { char: 'groomy', text: '사고 당일이랑.' },
      { char: 'groomy', text: '똑같은 패턴이에요.' },
      { char: 'groomy', text: '그날도.' },
      { char: 'groomy', text: '제가 두 곳에 있었어요.' },
      { char: 'groomy', text: '저는.', delayMs: 5000 },
      { char: 'groomy', text: '그날 무슨 일이 있었는지.' },
      { char: 'groomy', text: '정말 몰라요.' },
      { char: 'groomy', text: '모른다고 말하는 게.' },
      { char: 'groomy', text: '이렇게 무서운 줄.' },
      { char: 'groomy', text: '오늘 처음 알았어요.' },
    ],
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch2_triggeredAuditAlarm' }],
  },
  groomy_debrief: {
    id: 'chapter-02.groomy_debrief',
    chapterId: 'chapter-02',
    localId: 'groomy_debrief',
    mode: SceneModes.CHAT,
    emotion: 'warning',
    lines: [
      { char: 'system', text: '경보가 가라앉은 뒤, 채널이 조용해진다.', isNarration: true },
      { char: 'groomy', text: '2장은 여기까지예요. 당신이 남긴 기록은 제 메모리에도 남습니다.' },
      { char: 'groomy', text: '배터리, 사번, 순찰 공백. 셋 중 둘만 맞아도 회사는 움직여요.' },
      { char: 'iseol', text: '오늘은.' },
      { char: 'iseol', text: '여기까지 해요.' },
      { char: 'iseol', text: '다들 너무 많이 본 것 같아요.' },
      { char: 'groomy', text: '저도.' },
      { char: 'groomy', text: '그렇게 생각해요.' },
      { char: 'groomy', text: '근데 안 멈출 거잖아요.' },
      { char: 'groomy', text: ({ nickname }) => `${nickname} 씨.`, delayMs: 800 },
      { char: 'groomy', text: '다음 장에서는.' },
      { char: 'groomy', text: '두 가지 중 하나를 먼저 고르게 될 거예요.' },
      { char: 'groomy', text: '"진실"이랑.' },
      { char: 'groomy', text: '"보호자".' },
      { char: 'groomy', text: '…아, 이거.' },
      { char: 'groomy', text: '제가 먼저 말하면 안 되는 거였는데.' },
      { char: 'groomy', text: '어쩔 수 없어요.' },
      { char: 'groomy', text: '이미 말했으니까.' },
      { char: 'player', text: '보호자 얘기는 어떻게 알아요?' },
      { char: 'groomy', text: '모르는 게.', delayMs: 4000 },
      { char: 'groomy', text: '맞는데.' },
      { char: 'groomy', text: '알아요.' },
      { char: 'groomy', text: '저도 이게.' },
      { char: 'groomy', text: '왜 이런지 모르겠어요.' },
    ],
    choices: [
      {
        text: '괜찮아요, 그루미. 천천히 말해도 돼요.',
        next: 'ch2_chapter_closing',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'reassuredGroomyEndOfCh2' },
          relationship.closer,
        ],
      },
      {
        text: '어떻게 아는지 끝까지 알아낼 거예요.',
        next: 'ch2_chapter_closing',
        effects: [
          { type: EffectTypes.ADD_FLAG, flag: 'pressedGroomyEndOfCh2' },
          evidence(1),
        ],
      },
    ],
    effects: [{ type: EffectTypes.ADD_FLAG, flag: 'ch2_completedInvestigation' }],
  },
  ch2_chapter_closing: {
    id: 'chapter-02.ch2_chapter_closing',
    chapterId: 'chapter-02',
    localId: 'ch2_chapter_closing',
    mode: SceneModes.CHAT,
    emotion: 'neutral',
    systemMessage: 'CARETAKER SYSTEMS · 5F 감사 채널',
    lines: [
      { char: 'groomy', text: '…저 먼저 나갈게요.' },
      { char: 'groomy', text: '오늘 일은.' },
      { char: 'groomy', text: '정리할 게 많아서요.' },
      { char: 'system', text: 'CARETAKER SYSTEMS · 2장 감사 기록이 보관되었습니다.', isNarration: true },
      { char: 'system', text: '채널이 종료되었습니다.', isNarration: true },
    ],
    next: 'chapter_end',
  },
  chapter_end: {
    id: 'chapter-02.chapter_end',
    chapterId: 'chapter-02',
    localId: 'chapter_end',
    mode: SceneModes.END,
    title: '감사 구역',
    nextChapterId: 'chapter-03',
    end: { type: 'chapterComplete', nextChapterId: 'chapter-03' },
  },
}
